using Content.Client.UserInterface.Controls;
using Content.Shared._RW.Recruitment;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RW.Recruitment.UI;

[GenerateTypedNameReferences]
public sealed partial class RecruitmentConfirmationWindow : FancyWindow
{
    public event Action? OnAcceptPressed;
    public event Action? OnDeclinePressed;

    public RecruitmentConfirmationWindow()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ => OnAcceptPressed?.Invoke();
        DeclineButton.OnPressed += _ => OnDeclinePressed?.Invoke();
    }

    public void UpdateState(RecruitmentConfirmationBuiState state)
    {
        OrganizationLabel.Text = Loc.GetString(state.OrganizationName);
        ImplantLabel.Text = state.ImplantName;

        WarningLabel.SetMessage(Loc.GetString("recruitment-ui-warning"));

        var localizedOrgName = Loc.GetString(state.OrganizationName);
        WarningText.SetMessage(Loc.GetString("recruitment-ui-warning-text",
            ("organization", localizedOrgName),
            ("implant", state.ImplantName)));
    }
}
