using Content.Client.UserInterface.Controls;
using Content.Shared._RW.Recruitment;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RW.Recruitment.UI;

[GenerateTypedNameReferences]
public sealed partial class RecruitmentMemberListWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public RecruitmentMemberListWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(RecruitmentMemberListBuiState state)
    {
        var localizedOrgName = Loc.GetString(state.OrganizationName);
        OrganizationLabel.Text = Loc.GetString("recruitment-member-list-organization",
            ("organization", localizedOrgName));
        MemberCountLabel.Text = Loc.GetString("recruitment-member-list-count",
            ("count", state.Members.Length));

        MembersContainer.RemoveAllChildren();

        if (state.Members.Length == 0)
        {
            NoMembersLabel.Visible = true;
            MemberScroller.Visible = false;
            return;
        }

        NoMembersLabel.Visible = false;
        MemberScroller.Visible = true;

        AddHeaderLabels();

        var dividerRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2),
        };

        var divider = new PanelContainer
        {
            StyleClasses = { "LowDivider" },
            HorizontalExpand = true,
        };
        dividerRow.AddChild(divider);

        MembersContainer.AddChild(dividerRow);
        MembersContainer.AddChild(new Control());
        MembersContainer.AddChild(new Control());

        foreach (var member in state.Members)
        {
            AddMemberLabels(member);
        }
    }

    private void AddHeaderLabels()
    {
        MembersContainer.AddChild(new Label
        {
            Text = Loc.GetString("recruitment-member-list-header-name"),
            StyleClasses = { "LabelHeading" },
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        });

        MembersContainer.AddChild(new Label
        {
            Text = Loc.GetString("recruitment-member-list-header-recruiter"),
            StyleClasses = { "LabelHeading" },
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        });

        MembersContainer.AddChild(new Label
        {
            Text = Loc.GetString("recruitment-member-list-header-time"),
            StyleClasses = { "LabelHeading" },
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        });
    }

    private void AddMemberLabels(RecruitmentMemberListBuiState.RecruitedMemberData member)
    {
        MembersContainer.AddChild(new Label
        {
            Text = "• " + member.Name,
            HorizontalAlignment = HAlignment.Center,
            HorizontalExpand = true,
        });

        MembersContainer.AddChild(new Label
        {
            Text = member.RecruitedBy,
            HorizontalAlignment = HAlignment.Center,
            HorizontalExpand = true,
        });

        var timeSince = _timing.CurTime - member.RecruitedAt;
        if (timeSince < TimeSpan.Zero)
            timeSince = TimeSpan.Zero;

        var timeText = FormatTimeSpan(timeSince);
        MembersContainer.AddChild(new Label
        {
            Text = timeText,
            HorizontalAlignment = HAlignment.Center,
            HorizontalExpand = true,
        });
    }

    private static string FormatTimeSpan(TimeSpan span)
    {
        var minutes = (int)span.TotalMinutes;
        var seconds = span.Seconds;

        return Loc.GetString("recruitment-member-list-time",
            ("minutes", minutes),
            ("seconds", seconds));
    }
}
