// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Administration.Managers;
using Content.Client.Audio;
using Content.Shared.CCVar;
using Content.Shared._Amour;
using Content.Goobstation.Common.CCVar; // Goob Station - Barks
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AudioTab : Control
{
    [Dependency] private readonly IAudioManager _audio = default!;
    [Dependency] private readonly IClientAdminManager _admin = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public AudioTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var masterVolume = Control.AddOptionPercentSlider(
            CVars.AudioMasterVolume,
            SliderVolumeMaster,
            scale: ContentAudioSystem.MasterVolumeMultiplier);
        masterVolume.ImmediateValueChanged += OnMasterVolumeSliderChanged;

        // Goob Station - Barks-start
        Control.AddOptionPercentSlider(
            GoobCVars.BarksVolume,
            SliderVolumeBarks,
            scale: ContentAudioSystem.BarksMultiplier);
        // Goob Station - Barks-end

        // Amour - TTS Volume
        Control.AddOptionPercentSlider(
            WhiteCVars.TtsVolume,
            SliderVolumeTTS,
            scale: ContentAudioSystem.MasterVolumeMultiplier);

        // Amour - Jukebox Volume
        Control.AddOptionPercentSlider(
            AmourCVars.JukeboxVolume,
            SliderVolumeJukebox,
            scale: 1f);

        InitializeVoiceTypeSelector(); // Amour - TTS

        // Orion-Start
        Control.AddOptionPercentSlider(
            CCVars.RadioVolume,
            SliderVolumeRadio,
            scale: ContentAudioSystem.RadioMultiplier);
        // Orion-End

        Control.AddOptionPercentSlider(
            CVars.MidiVolume,
            SliderVolumeMidi,
            scale: ContentAudioSystem.MidiVolumeMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbientMusicVolume,
            SliderVolumeAmbientMusic,
            scale: ContentAudioSystem.AmbientMusicMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbienceVolume,
            SliderVolumeAmbience,
            scale: ContentAudioSystem.AmbienceMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.LobbyMusicVolume,
            SliderVolumeLobby,
            scale: ContentAudioSystem.LobbyMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.InterfaceVolume,
            SliderVolumeInterface,
            scale: ContentAudioSystem.InterfaceMultiplier);

        // Goobstation - Highlight Chat Ping/Audio!
        Control.AddOptionPercentSlider(
            CCVars.ChatHighlightVolume,
            SliderHighlightVolume,
            scale: 1f);

        Control.AddOptionSlider(
            CCVars.MaxAmbientSources,
            SliderMaxAmbienceSounds,
            _cfg.GetCVar(CCVars.MinMaxAmbientSourcesConfigured),
            _cfg.GetCVar(CCVars.MaxMaxAmbientSourcesConfigured));

        Control.AddOptionCheckBox(CCVars.CombatModeSoundEnabled, CombatModeSoundCheckBox); // Orion
        Control.AddOptionCheckBox(CCVars.LobbyMusicEnabled, LobbyMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.RestartSoundsEnabled, RestartSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.EventMusicEnabled, EventMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.AdminSoundsEnabled, AdminSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.BwoinkSoundEnabled, BwoinkSoundCheckBox);

        Control.Initialize();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _admin.AdminStatusUpdated += UpdateAdminButtonsVisibility;
        UpdateAdminButtonsVisibility();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _admin.AdminStatusUpdated -= UpdateAdminButtonsVisibility;
    }


    private void UpdateAdminButtonsVisibility()
    {
        BwoinkSoundCheckBox.Visible = _admin.IsActive();
    }

    private void OnMasterVolumeSliderChanged(float value)
    {
        // TODO: I was thinking of giving OptionsTabControlRow a flag to "set CVar immediately", but I'm deferring that
        // until there's a proper system for enforcing people don't close the window with pending changes.
        _audio.SetMasterGain(value);
    }

    // Amour - TTS Start
    private void InitializeVoiceTypeSelector()
    {
        VoiceTypeSelector.AddItem(Loc.GetString("ui-options-voice-type-barks"), (int)CharacterVoiceType.Barks);
        VoiceTypeSelector.AddItem(Loc.GetString("ui-options-voice-type-tts"), (int)CharacterVoiceType.TTS);

        Control.AddOption(new OptionVoiceType(Control, _cfg, VoiceTypeSelector));
    }
    // Amour - TTS End
}

// Amour - TTS Start
/// <summary>
/// Custom option for VoiceType enum with OptionButton control.
/// </summary>
public sealed class OptionVoiceType : BaseOption
{
    private readonly IConfigurationManager _cfg;
    private readonly OptionButton _button;

    private CharacterVoiceType Value
    {
        get => (CharacterVoiceType)_button.SelectedId;
        set => _button.SelectId((int)value);
    }

    public OptionVoiceType(OptionsTabControlRow controller, IConfigurationManager cfg, OptionButton button)
        : base(controller)
    {
        _cfg = cfg;
        _button = button;

        _button.OnItemSelected += args =>
        {
            _button.SelectId(args.Id);
            ValueChanged();
        };
    }

    public override void LoadValue()
    {
        Value = _cfg.GetCVar(WhiteCVars.VoiceType);
    }

    public override void SaveValue()
    {
        _cfg.SetCVar(WhiteCVars.VoiceType, Value);
    }

    public override void ResetToDefault()
    {
        Value = WhiteCVars.VoiceType.DefaultValue;
    }

    public override bool IsModified()
    {
        return Value != _cfg.GetCVar(WhiteCVars.VoiceType);
    }

    public override bool IsModifiedFromDefault()
    {
        return Value != WhiteCVars.VoiceType.DefaultValue;
    }
}
// Amour - TTS End
