// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._RW.TTS;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RW.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSVoiceMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public event Action<TTSVoicePrototype>? OnVoiceSelected;
    public event Action<TTSVoicePrototype>? OnVoicePreview;

    private List<TTSVoicePrototype> _allVoices = new();
    private List<string> _allSources = new();
    private string? _currentSearch;
    private Sex? _currentSexFilter;
    private string? _currentSourceFilter;
    private TTSVoicePrototype? _selectedVoice;

    private const int SexFilterAll = 0;
    private const int SourceFilterAll = 0;

    public TTSVoiceMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        InitializeFilters();
        LoadVoices();

        SearchLineEdit.OnTextChanged += OnSearchChanged;
        SexFilterButton.OnItemSelected += OnSexFilterChanged;
        SourceFilterButton.OnItemSelected += OnSourceFilterChanged;
        VoiceList.OnItemSelected += OnVoiceListSelected;
        VoiceList.OnItemDeselected += OnVoiceListDeselected;
        PreviewButton.OnPressed += OnPreviewPressed;
    }

    private void InitializeFilters()
    {
        SexFilterButton.AddItem(_loc.GetString("humanoid-profile-editor-tts-voice-menu-sex-all"), SexFilterAll);
        SexFilterButton.AddItem(_loc.GetString("humanoid-profile-editor-tts-voice-menu-sex-male"), (int)Sex.Male + 1);
        SexFilterButton.AddItem(_loc.GetString("humanoid-profile-editor-tts-voice-menu-sex-female"), (int)Sex.Female + 1);
        SexFilterButton.AddItem(_loc.GetString("humanoid-profile-editor-tts-voice-menu-sex-unsexed"), (int)Sex.Unsexed + 1);
        SexFilterButton.SelectId(SexFilterAll);

        SourceFilterButton.AddItem(_loc.GetString("humanoid-profile-editor-tts-voice-menu-source-all"), SourceFilterAll);
        SourceFilterButton.SelectId(SourceFilterAll);
    }

    private void LoadVoices()
    {
        _allVoices = _prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(v => v.RoundStart)
            .OrderBy(v => Loc.GetString(v.Name))
            .ToList();

        _allSources = _allVoices
            .Select(v => v.Source)
            .Where(s => !string.IsNullOrEmpty(s))
            .Distinct()
            .OrderBy(s => s)
            .ToList();

        var sourceId = 1;
        foreach (var source in _allSources)
        {
            SourceFilterButton.AddItem(source, sourceId++);
        }

        PopulateVoiceList();
    }

    private void PopulateVoiceList()
    {
        VoiceList.Clear();
        _selectedVoice = null;

        var filteredVoices = _allVoices.AsEnumerable();

        if (!string.IsNullOrWhiteSpace(_currentSearch))
        {
            var searchLower = _currentSearch.ToLowerInvariant();
            filteredVoices = filteredVoices.Where(v =>
                Loc.GetString(v.Name).ToLowerInvariant().Contains(searchLower) ||
                v.ID.ToLowerInvariant().Contains(searchLower));
        }

        if (_currentSexFilter.HasValue)
        {
            filteredVoices = filteredVoices.Where(v => v.Sex == _currentSexFilter.Value);
        }

        if (!string.IsNullOrEmpty(_currentSourceFilter))
        {
            filteredVoices = filteredVoices.Where(v => v.Source == _currentSourceFilter);
        }

        foreach (var voice in filteredVoices)
        {
            var displayName = Loc.GetString(voice.Name);
            var sexIcon = voice.Sex switch
            {
                Sex.Male => "♂",
                Sex.Female => "♀",
                _ => "⚥"
            };

            var itemText = $"{sexIcon} {displayName}";
            if (!string.IsNullOrEmpty(voice.Source))
            {
                itemText += $" [{voice.Source}]";
            }

            var item = VoiceList.AddItem(itemText);
            item.Metadata = voice;
        }

        PreviewButton.Disabled = true;
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        _currentSearch = args.Text;
        PopulateVoiceList();
    }

    private void OnSexFilterChanged(OptionButton.ItemSelectedEventArgs args)
    {
        SexFilterButton.SelectId(args.Id);

        if (args.Id == SexFilterAll)
        {
            _currentSexFilter = null;
        }
        else
        {
            _currentSexFilter = (Sex)(args.Id - 1);
        }

        PopulateVoiceList();
    }

    private void OnSourceFilterChanged(OptionButton.ItemSelectedEventArgs args)
    {
        SourceFilterButton.SelectId(args.Id);

        if (args.Id == SourceFilterAll)
        {
            _currentSourceFilter = null;
        }
        else if (args.Id - 1 < _allSources.Count)
        {
            _currentSourceFilter = _allSources[args.Id - 1];
        }

        PopulateVoiceList();
    }

    private void OnVoiceListSelected(ItemList.ItemListSelectedEventArgs args)
    {
        var item = VoiceList[args.ItemIndex];
        if (item.Metadata is TTSVoicePrototype voice)
        {
            _selectedVoice = voice;
            PreviewButton.Disabled = false;
            OnVoiceSelected?.Invoke(voice);
        }
    }

    private void OnVoiceListDeselected(ItemList.ItemListDeselectedEventArgs args)
    {
        _selectedVoice = null;
        PreviewButton.Disabled = true;
    }

    private void OnPreviewPressed(BaseButton.ButtonEventArgs args)
    {
        if (_selectedVoice != null)
        {
            OnVoicePreview?.Invoke(_selectedVoice);
        }
    }

    public void SetSelectedVoice(string voiceId)
    {
        for (var i = 0; i < VoiceList.Count; i++)
        {
            var item = VoiceList[i];
            if (item.Metadata is TTSVoicePrototype voice && voice.ID == voiceId)
            {
                VoiceList[i].Selected = true;
                _selectedVoice = voice;
                PreviewButton.Disabled = false;
                return;
            }
        }
    }
}
