// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Clothing;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Loadouts;

// Amour edit start
public enum LoadoutSourceType
{
    UserSelected,
    InheritedFromBase,
    PersonalFluff,
    BoostySubscription
}
// Amour edit end

[GenerateTypedNameReferences]
public sealed partial class LoadoutContainer : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;

    private readonly EntityUid? _entity;

    // Amour edit start
    private LoadoutSourceType _sourceType = LoadoutSourceType.UserSelected;

    private static readonly Color ColorInheritedFromBase = new Color(0.4f, 0.7f, 0.9f, 1.0f);
    // Amour edit end

    public Button Select => SelectButton;

    public string? Text
    {
        get => SelectButton.Text;
        set => SelectButton.Text = value;
    }

    // Amour edit start
    public LoadoutSourceType SourceType
    {
        get => _sourceType;
        set
        {
            _sourceType = value;
            UpdateButtonStyle();
        }
    }

    private void UpdateButtonStyle()
    {
        if (!SelectButton.Pressed)
        {
            SelectButton.ModulateSelfOverride = null;
            return;
        }

        SelectButton.ModulateSelfOverride = _sourceType switch
        {
            LoadoutSourceType.InheritedFromBase => ColorInheritedFromBase,
            _ => null
        };
    }
    // Amour edit end

    public LoadoutContainer(ProtoId<LoadoutPrototype> proto, bool disabled, FormattedMessage? reason)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SelectButton.Disabled = disabled;

        if (disabled && reason != null)
        {
            var tooltip = new Tooltip();
            tooltip.SetMessage(reason);
            SelectButton.TooltipSupplier = _ => tooltip;
        }

        if (_protoManager.Resolve(proto, out var loadProto))
        {
            var ent = loadProto.DummyEntity ?? _entManager.System<LoadoutSystem>().GetFirstOrNull(loadProto);

            if (ent == null)
                return;

            _entity = _entManager.SpawnEntity(ent, MapCoordinates.Nullspace);
            Sprite.SetEntity(_entity);

            var spriteTooltip = new Tooltip();
            spriteTooltip.SetMessage(FormattedMessage.FromUnformatted(_entManager.GetComponent<MetaDataComponent>(_entity.Value).EntityDescription));

            TooltipSupplier = _ => spriteTooltip;
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (!disposing)
            return;

        _entManager.DeleteEntity(_entity);
    }

    public bool Pressed
    {
        get => SelectButton.Pressed;
        set => SelectButton.Pressed = value;
    }
}
