// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Amour.Loadouts.Effects;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutWindow : FancyWindow
{
    public event Action<string>? OnNameChanged;
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutPressed;
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutUnpressed;
    public event Action? OnRevertToBase; // Amour edit

    private List<LoadoutGroupContainer> _groups = new();

    public HumanoidCharacterProfile Profile;

    // CCvar.
    private int _maxLoadoutNameLength;

    // Amour edit start
    public LoadoutWindow(HumanoidCharacterProfile profile, RoleLoadout loadout, RoleLoadoutPrototype proto, ICommonSession session, IDependencyCollection collection, bool showRevertToBase = false)
    {
        RobustXamlLoader.Load(this);
        Profile = profile;

        RevertToBaseButton.Visible = showRevertToBase;
        RevertToBaseButton.OnPressed += _ => OnRevertToBase?.Invoke();
     // Amour edit end
        var protoManager = collection.Resolve<IPrototypeManager>();
        var configManager = collection.Resolve<IConfigurationManager>();

        _maxLoadoutNameLength = configManager.GetCVar(CCVars.MaxLoadoutNameLength);
        RoleNameEdit.IsValid = text => text.Length <= _maxLoadoutNameLength;

        // Hide if we can't edit the name.
        if (!proto.CanCustomizeName)
        {
            RoleNameBox.Visible = false;
        }
        else
        {
            var name = loadout.EntityName;

            LoadoutNameLabel.Text = proto.NameDataset == null ?
                Loc.GetString("loadout-name-edit-label") :
                Loc.GetString("loadout-name-edit-label-dataset");

            RoleNameEdit.ToolTip = Loc.GetString(
                "loadout-name-edit-tooltip",
                ("max", _maxLoadoutNameLength));
            RoleNameEdit.Text = name ?? string.Empty;
            RoleNameEdit.OnTextChanged += args => OnNameChanged?.Invoke(args.Text);
        }

        // Hide if no groups
        if (proto.Groups.Count == 0)
        {
            LoadoutGroupsContainer.Visible = false;
            SetSize = Vector2.Zero;
        }
        else
        {
            // Amour
            var allGroups = GetAllGroupsWithBaseCrew(proto, protoManager);

            foreach (var group in allGroups)
            {
                if (!protoManager.Resolve(group, out var groupProto))
                    continue;

                if (groupProto.Hidden)
                    continue;

                // Amour
                var hasAvailableLoadouts = HasAvailableLoadoutsForUser(groupProto, profile, loadout, session, collection, protoManager);
                if (!hasAvailableLoadouts)
                    continue;

                var container = new LoadoutGroupContainer(profile, loadout, protoManager.Index(group), session, collection);
                LoadoutGroupsContainer.AddTab(container, Loc.GetString(groupProto.Name));
                _groups.Add(container);

                container.OnLoadoutPressed += args =>
                {
                    OnLoadoutPressed?.Invoke(group, args);
                };

                container.OnLoadoutUnpressed += args =>
                {
                    OnLoadoutUnpressed?.Invoke(group, args);
                };
            }
        }
    }

    public void RefreshLoadouts(RoleLoadout loadout, ICommonSession session, IDependencyCollection collection)
    {
        foreach (var group in _groups)
        {
            group.RefreshLoadouts(Profile, loadout, session, collection);
        }
    }

    // Amour edit start
    private const string BaseCrewProtoId = "BaseCrew";
    private const string RoleSurvivalPrefix = "RoleSurvival";
    private const string JobBorgProtoId = "JobBorg";
    private const string JobStationAiProtoId = "JobStationAi";

    private static List<ProtoId<LoadoutGroupPrototype>> GetAllGroupsWithBaseCrew(RoleLoadoutPrototype proto, IPrototypeManager protoManager)
    {
        var result = new List<ProtoId<LoadoutGroupPrototype>>(proto.Groups);

        if (proto.ID == BaseCrewProtoId || proto.ID.StartsWith(RoleSurvivalPrefix) || proto.ID == JobBorgProtoId || proto.ID == JobStationAiProtoId)
            return result;

        if (protoManager.TryIndex<RoleLoadoutPrototype>(BaseCrewProtoId, out var baseCrew))
        {
            foreach (var baseGroup in baseCrew.Groups)
            {
                if (!result.Contains(baseGroup))
                    result.Add(baseGroup);
            }
        }

        return result;
    }

    /// <summary>
    /// Check if the given loadout group has any loadouts available to the current user.
    /// Groups with only UserNameLoadoutEffect or BoostyTierLoadoutEffect-restricted loadouts 
    /// will return false if none are valid for this user.
    /// </summary>
    private static bool HasAvailableLoadoutsForUser(
        LoadoutGroupPrototype groupProto,
        HumanoidCharacterProfile profile,
        RoleLoadout loadout,
        ICommonSession session,
        IDependencyCollection collection,
        IPrototypeManager protoManager)
    {
        foreach (var loadoutId in groupProto.Loadouts)
        {
            if (!protoManager.TryIndex<LoadoutPrototype>(loadoutId, out var loadoutProto))
                continue;

            // Check if this loadout has personal or booster restrictions
            var hasUserNameEffect = loadoutProto.Effects.Any(e => e is UserNameLoadoutEffect);
            var hasBoostyEffect = loadoutProto.Effects.Any(e => e is BoostyTierLoadoutEffect);

            if (hasUserNameEffect || hasBoostyEffect)
            {
                // For personal fluff and booster loadouts, check if this user can use it
                if (loadout.IsValid(profile, session, loadoutId, collection, out _))
                    return true; // At least one loadout is valid
            }
            else
            {
                // Non-restricted loadout - group has available content
                return true;
            }
        }

        return false;
    }
}
// Amour edit end
