using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RW.Chat.Systems.DirectionalEmote;

[GenerateTypedNameReferences]
public sealed partial class DirectionalEmoteWindow : FancyWindow
{
    public NetEntity Source { get; set; }
    public NetEntity Target { get; set; }
    public string Text { get; private set; } = "";
    public Action? AcceptPressed;
    public Action? MessageChanged;
    public Action? Closed;

    public DirectionalEmoteWindow()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ => AcceptPressed?.Invoke();
        MessageInput.OnTextChanged += e =>
        {
            Text = Rope.Collapse(e.TextRope).Trim();
            MessageChanged?.Invoke();
        };
        CloseButton.OnPressed += _ =>
        {
            Closed?.Invoke();
            Dispose();
        };
    }
}
