// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.FlavorText
{
    [GenerateTypedNameReferences]
    public sealed partial class FlavorText : Control
    {
        public Action<string>? OnFlavorTextChanged;
        // Orion-Start
        public Action<string>? OnCharacterTextChanged;
        public Action<string>? OnGreenTextChanged;
        public Action<string>? OnYellowTextChanged;
        public Action<string>? OnRedTextChanged;
        public Action<int>? OnTabChanged;
        // Orion-End

        public FlavorText()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var loc = IoCManager.Resolve<ILocalizationManager>();

            // Orion-Start
            FlavorTabs.SetTabTitle(0, Loc.GetString("flavor-tab-flavor"));
            FlavorTabs.SetTabTitle(1, Loc.GetString("flavor-tab-character"));
            FlavorTabs.SetTabTitle(2, Loc.GetString("flavor-tab-gyr"));
            FlavorTabs.SetTabTitle(3, Loc.GetString("flavor-tab-preview"));

            PreviewTabs.SetTabTitle(0, Loc.GetString("flavor-tab-flavor"));
            PreviewTabs.SetTabTitle(1, Loc.GetString("flavor-tab-character"));
            PreviewTabs.SetTabTitle(2, Loc.GetString("flavor-tab-gyr"));

            CFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("flavor-text-placeholder"));
            CFlavorTextInput.OnTextChanged += _ => FlavorTextChanged();

            CCharacterTextInput.Placeholder = new Rope.Leaf(loc.GetString("character-flavor-text-placeholder"));
            CCharacterTextInput.OnTextChanged += _ => CharacterTextChanged();



            CGreenTextInput.Placeholder = new Rope.Leaf(loc.GetString("green-flavor-text-placeholder"));
            CGreenTextInput.OnTextChanged += _ => GreenTextChanged();

            CYellowTextInput.Placeholder = new Rope.Leaf(loc.GetString("yellow-flavor-text-placeholder"));
            CYellowTextInput.OnTextChanged += _ => YellowTextChanged();

            CRedTextInput.Placeholder = new Rope.Leaf(loc.GetString("red-flavor-text-placeholder"));
            CRedTextInput.OnTextChanged += _ => RedTextChanged();

            PreviewTabs.OnTabChanged += FlavorTabChanged;
            // Orion-End
        }

        public void FlavorTextChanged()
        {
            OnFlavorTextChanged?.Invoke(Rope.Collapse(CFlavorTextInput.TextRope).Trim());
        }


        public void CharacterTextChanged()
        {
            OnCharacterTextChanged?.Invoke(Rope.Collapse(CCharacterTextInput.TextRope).Trim());
        }

        public void GreenTextChanged()
        {
            OnGreenTextChanged?.Invoke(Rope.Collapse(CGreenTextInput.TextRope).Trim());
        }

        public void YellowTextChanged()
        {
            OnYellowTextChanged?.Invoke(Rope.Collapse(CYellowTextInput.TextRope).Trim());
        }

        public void RedTextChanged()
        {
            OnRedTextChanged?.Invoke(Rope.Collapse(CRedTextInput.TextRope).Trim());
        }



        public void FlavorTabChanged(int tab)
        {
            OnTabChanged?.Invoke(tab);
        }
        // Orion-End
    }
}
