# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 7200 # 2 h # Amour-Edit
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 # 2 h # Amour-Edit
    - !type:DepartmentTimeRequirement
      department: Science
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 14400 # 4 h # Amour-Edit
    - !type:DepartmentTimeRequirement
      department: Command
      time: 28000 # 8 hours
    - !type:DiscordLinkRequirement
    - !type:AgeRequirement # Amour
      requiredAge: 23
      #any MRP using our code might eventually want to use it
    # - !type:SaturationRequirement # MisandryBox - no neon hair on captain
    #   hairColorSaturation: 0.30
#  guides: # goobstation | Orion-Edit: Removed because dont have this SOP
#  - Command
#  - Succession
#  - StandardProceduresSOP
#  - CaptainSOP
  goobcoins: 50 #Goob content
  # Orion-Start
  salary: 140
  payrollDepartmentAccount: Command
  # Orion-End
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Condemned # Goobstation - Nanotrasen owns your soul pal.
        soulOwnedNotDevil: true
      # Orion-Start
      - type: AdditionalLanguage
        speaks:
        - CorporateCodespeak
        understands:
        - CorporateCodespeak
      # Orion-End

- type: startingGear
  id: CaptainGear
  equipment:
   # shoes: ClothingShoesBootsLaceup - Goobstation
    eyes: ClothingEyesGlassesCommand
    #gloves: ClothingHandsGlovesCaptain - Goobstation, moved to loadouts
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation
    # - StationCharter

- type: chameleonOutfit
  id: CaptainChameleonOutfit
  job: Captain
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
