# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: BlueshieldOfficer
  name: job-name-bs
  description: job-description-bs
  playTimeTracker: JobBlueshieldOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 # 15 hours # Amour-Edit: Don't change this!
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours # Amour-Edit: Don't change this!
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours # Amour-Edit: Don't change this!
    - !type:DiscordLinkRequirement
    - !type:AgeRequirement
      requiredAge: 21
    - !type:SpeciesRequirement # Goob - None Felinid
      inverted: true
      species:
      - Felinid
#  guides: # Orion-Edit: Removed because dont have this SOP
#  - BlueshieldOfficerSOP
#  - Command
#  - Succession
  goobcoins: 45
  # Orion-Start
  salary: 120
  payrollDepartmentAccount: Command
  # Orion-End
  weight: 20
  startingGear: BlueshieldOfficerGear
  icon: "JobIconBlueshield"
  joinNotifyCrew: true
  supervisors: job-supervisors-ntr-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - CentralCommand
  - BlueshieldOfficer
  - Service
  - Hydroponics
  - Cargo
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, BluespaceLifelineImplant ] # Go big, or go home.
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Condemned
        soulOwnedNotDevil: true
      # Orion-Start
      - type: AdditionalLanguage
        speaks:
        - CorporateCodespeak
        understands:
        - CorporateCodespeak
      # Orion-End

- type: startingGear
  id: BlueshieldOfficerGear
  equipment:
    eyes: ClothingEyesGlassesBSO
    #gloves: ClothingHandsGlovesCombat - Goobstation, moved to loadouts
    id: BlueshieldPDA
    ears: ClothingHeadsetAltBlueshield
    belt: ClothingBeltMilitaryWebbingFilled
    pocket1: UniqueBlueshieldOfficerLockerTeleporter
  storage:
    back:
    - Flash
    - ClothingBSOMaskGasSwat
    - CombatKnife

- type: chameleonOutfit
  id: BlueshieldOfficerChameleonOutfit
  job: BlueshieldOfficer
  equipment:
    head: ClothingHeadHatBeretEliteNavyOfficer
    eyes: ClothingEyesGlassesBSO
    mask: ClothingMaskGasSecurity
    ears: ClothingHeadsetAltBlueshield
    outerClothing: ClothingBlueshieldArmourVest
    neck: ClothingNeckMantleBlueshield
    gloves: ClothingHandsGlovesCombat
    jumpsuit: ClothingUniformJumpsuitBlueshieldOfficer
    id: BlueshieldPDA
    back: ClothingBackpackBlueshield
    shoes: ClothingShoesBootsJack
