# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: NanotrasenRepresentative
  name: job-name-ntr
  description: job-description-ntr
  playTimeTracker: JobNanotrasenRepresentative
  requirements:
    - !type:AnyOfRequirement # Amour edit - Discord OR playtime
      requirements:
        - !type:DiscordLinkRequirement
        - !type:DepartmentTimeRequirement
          department: Command
          time: 7200 #2 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 90000 #25 hours # Amour-Edit
    - !type:AgeRequirement
      requiredAge: 21
  weight: 20
  startingGear: NanotrasenRepresentativeGear
  icon: "JobIconNanotrasenRepresentative"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  guides:
  # Amour-Edit-Start
  # - SpaceLaw # Disabled until guide is created
  # - SOP # Disabled until guide is created
  # - SOP-Alerts # Disabled until guide is created
  # Amour-Edit-End
  goobcoins: 40
  # Orion-Start
  salary: 120
  payrollDepartmentAccount: Command
  # Orion-End
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - CentralCommand
  - Service
  - Hydroponics
  - Kitchen
  - Cargo
  - Theatre
  - NanotrasenRepresentative
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Condemned
        soulOwnedNotDevil: true
      # Orion-Start
      - type: AdditionalLanguage
        speaks:
        - CorporateCodespeak
        understands:
        - CorporateCodespeak
      # Orion-End

- type: startingGear
  id: NanotrasenRepresentativeGear
  equipment:
    id: NanotrasenRepresentativePDA
    eyes: ClothingEyesGlassesCommand
    ears: ClothingHeadsetAltCentCom
    pocket1: UniqueNanorepLockerTeleporter
  storage:
    back:
    - Flash
    - TelescopicBaton
  # inhand:
  #   - ExecutiveBriefcaseEmpty # TODO: Maybe change this to not-empty, so that ntr wouldn't be poor at the start of every shift but whatever

- type: chameleonOutfit
  id: NanotrasenRepresentativeChameleonOutfit
  job: NanotrasenRepresentative
  equipment:
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskBreath
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesHeavyGoldenTrim
    jumpsuit: ClothingUniformJumpsuitNanotrasenRepresentative
    id: NanotrasenRepresentativePDA
    back: ClothingBackpackCentcomm
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatTophat
    neck: ClothingNeckScarfStripedCentcom
