# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 18000 #5 hrs
  - !type:DiscordLinkRequirement # RW
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  guides: # goobstation
  # RW-Edit-Start
  # - SpaceLaw # Disabled until guide is created
  # RW-Edit-End
  goobcoins: 30 #Goob content
  # RW-Start
  salary: 80
  payrollDepartmentAccount: Security
  # RW-End
  access:
  - Security
  - Brig
  - Maintenance
  - Detective
  - Cryogenics
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial # goobstation
    components:
      - type: SecurityStaff

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    #gloves: ClothingHandsGlovesForensic - Goobstation, moved to loadouts
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    belt: ClothingBeltHolsterFilled
    pocket1: WeaponDisabler # RW
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
#    - ClothingMaskGasSecurity # Goobstation # RW-Edit: Now in BoxSurvival

- type: chameleonOutfit
  id: DetectiveChameleonOutfit
  job: Detective
  hasMindShield: true
  equipment:
    head: ClothingHeadHatFedoraBrown
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckTieDet
    gloves: ClothingHandsGlovesForensic
