# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    # Amour-Edit-Start
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 25200 # 7 hrs
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 3600 # 1 h
    # Amour-Edit-End
    - !type:DiscordLinkRequirement # Amour
    - !type:AgeRequirement # Amour
      requiredAge: 23
    - !type:SpeciesRequirement # Amour
      inverted: true
      species:
      - Felinid
      - Resomi
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  guides: # goobstation
  # Amour-Edit-Start
  # - SpaceLaw # Disabled until guide is created
  # Amour-Edit-End
  goobcoins: 45 #Goob content
  # Orion-Start
  salary: 120
  payrollDepartmentAccount: Command
  # Orion-End
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: SecurityStaff # goobstation

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    #gloves: ClothingHandsGlovesCombat - Goobstation, moved to loadouts
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponDisabler # Orion-Edit: PistolMk58 > Disabler
  storage:
    back:
    - Flash
#    - MagazinePistol # Orion-Edit: Now in loadout

- type: chameleonOutfit
  id: HeadOfSecurityChameleonOutfit
  job: HeadOfSecurity
  hasMindShield: true
  equipment:
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckCloakHos
