# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 2.5h
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  guides: # goobstation
  # Orion-Edit-Start
  - SpaceLaw
  # - SOP-Security-Officer # Disabled until guide is created
  # - SOP-Security # Disabled until guide is created
  # Orion-Edit-End
  goobcoins: 30 #Goob content
  # Orion-Start
  salary: 85
  payrollDepartmentAccount: Security
  # Orion-End
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial # goobstation
    components:
      - type: SecurityStaff

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    pocket1: WeaponDisabler # Orion-Edit: PistolMk58 > Disabler
  storage:
    back:
    - Flash
#    - MagazinePistol # Orion-Edit: Now in loadout

- type: chameleonOutfit
  id: SecurityOfficerChameleonOutfit
  job: SecurityOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
    gloves: ClothingHandsGlovesColorBlack
