# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 5h
    - !type:RoleTimeRequirement # Goobstation
      role: JobBrigmedic
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hrs
  weight: 5
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  guides: # goobstation
  - SpaceLaw
  # Orion-Edit-Start
  # - SOP-Security-Warden # Disabled until guide is created
  # - SOP-Security # Disabled until guide is created
  # Orion-Edit-End
  - KravMaga
  goobcoins: 35 #Goob content
  # Orion-Start
  salary: 90
  payrollDepartmentAccount: Security
  # Orion-End
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial # goobstation
    components:
      - type: SecurityStaff

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity # Goobstation | Orion-Edit - OP
    id: WardenPDA
    ears: ClothingHeadsetAltWarden # Goobstation
    pocket1: WeaponDisabler # Orion-Edit: PistolMk58 > Disabler
  storage:
    back:
    - Flash
#    - MagazinePistol # Orion-Edit: Now in loadout
#    - ClothingMaskGasSecurity # Goobstation # Orion-Edit: Now in BoxSurvival

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
