// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Orion.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class TechnologyCardControl : Control
{
    public Action? OnPressed;

    public TechnologyCardControl(TechnologyPrototype technology, IPrototypeManager prototypeManager, SpriteSystem spriteSys, FormattedMessage description, List<ResearchPointAmount> pointBalances, bool hasAccess) // Orion-Edit
    {
        RobustXamlLoader.Load(this);

        var discipline = prototypeManager.Index(technology.Discipline);
        Background.ModulateSelfOverride = discipline.Color;

        DisciplineTexture.Texture = spriteSys.Frame0(discipline.Icon);
        TechnologyNameLabel.Text = Loc.GetString(technology.Name);
        var message = new FormattedMessage();
        message.AddMarkupOrThrow(Loc.GetString("research-console-tier-discipline-info",
            ("tier", technology.Tier), ("color", discipline.Color), ("discipline", Loc.GetString(discipline.Name))));
        TierLabel.SetMessage(message);
        UnlocksLabel.SetMessage(description);

        TechnologyTexture.Texture = spriteSys.Frame0(technology.Icon);

        if (!hasAccess)
            ResearchButton.ToolTip = Loc.GetString("research-console-no-access-popup");

        // Orion-Edit-Start
        var hasSufficientPoints = technology.PointCosts.All(cost =>
            pointBalances.Any(balance => balance.Type == cost.Type && balance.Amount >= cost.Amount));

        ResearchButton.Disabled = !hasSufficientPoints || !hasAccess;
        // Orion-Edit-End
        ResearchButton.OnPressed += _ => OnPressed?.Invoke();
    }
}
