using Content.Client.UserInterface.Controls;
using Content.Shared._RW.GameFlowControl;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.IoC;
using System.Linq;

namespace Content.Client._RW.GameFlowControl;

[GenerateTypedNameReferences]
public sealed partial class GameFlowControlWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly GameFlowControlEui _eui;
    private List<string> _allRules = new();
    private string? _selectedRule;

    private string? _currentScheduler;
    private float _lastMinInterval = -1f;
    private float _lastMaxInterval = -1f;
    private float _lastChaosScore = -1f;

    public GameFlowControlWindow(GameFlowControlEui eui)
    {
        IoCManager.InjectDependencies(this);
        _eui = eui;

        RobustXamlLoader.Load(this);

        ReleaseBtn.OnPressed += _ => _eui.SendMessage(new ReleaseControlMsg());
        ApplyIntervalBtn.OnPressed += OnApplyInterval;
        ApplyChaosBtn.OnPressed += OnApplyChaos;
        RunRuleBtn.OnPressed += OnRunRule;
        RunRuleBtn.Disabled = true;

        SearchEdit.OnTextChanged += _ => PopulateRulesList();
        RulesList.OnItemSelected += OnRuleSelected;
        RulesList.OnItemDeselected += OnRuleDeselected;

        MinIntervalSpin.InitDefaultButtons();
        MaxIntervalSpin.InitDefaultButtons();
        TimeLeftSpin.InitDefaultButtons();
        ChaosScoreSpin.InitDefaultButtons();
    }

    public void UpdateState(GameFlowControlEuiState state)
    {
        // 1. Occupier status
        if (state.OccupierName != null)
        {
            OccupierLabel.Text = Loc.GetString("game-flow-control-occupier-label", ("username", state.OccupierName));
        }
        else
        {
            OccupierLabel.Text = Loc.GetString("game-flow-control-unoccupied-label");
        }

        // 2. Scheduler details
        SchedulerTypeLabel.Text = $"Active Scheduler: {state.ActiveScheduler}";
        
        if (_currentScheduler != state.ActiveScheduler)
        {
            _currentScheduler = state.ActiveScheduler;
            _lastMinInterval = state.MinInterval;
            _lastMaxInterval = state.MaxInterval;
            _lastChaosScore = state.ChaosScore;

            MinIntervalSpin.Value = (int)state.MinInterval;
            MaxIntervalSpin.Value = (int)state.MaxInterval;
            ChaosScoreSpin.Value = (int)state.ChaosScore;
        }
        else
        {
            if (state.MinInterval != _lastMinInterval)
            {
                _lastMinInterval = state.MinInterval;
                MinIntervalSpin.Value = (int)state.MinInterval;
            }
            if (state.MaxInterval != _lastMaxInterval)
            {
                _lastMaxInterval = state.MaxInterval;
                MaxIntervalSpin.Value = (int)state.MaxInterval;
            }
            if (state.ChaosScore != _lastChaosScore)
            {
                _lastChaosScore = state.ChaosScore;
                ChaosScoreSpin.Value = (int)state.ChaosScore;
            }
        }

        if (!TimeLeftSpin.LineEditControl.HasKeyboardFocus())
            TimeLeftSpin.Value = (int)state.TimeUntilNext;

        // Hide/Show Chaos Meter depending on SecretPlus scheduler active
        var isSecretPlus = state.ActiveScheduler == "SecretPlus";
        ChaosSection.Visible = isSecretPlus;

        // 3. Pending approvals container
        PendingContainer.DisposeAllChildren();
        if (state.PendingRules.Count == 0)
        {
            PendingContainer.AddChild(new Label
            {
                Text = "No events pending approval.",
                StyleClasses = { "Dimmed" }
            });
        }
        else
        {
            foreach (var rule in state.PendingRules)
            {
                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 8,
                    HorizontalExpand = true
                };

                // Localize rule name if prototype exists
                var displayName = GetRuleDisplayName(rule.RuleId);

                row.AddChild(new Label
                {
                    Text = $"{displayName} ({rule.TimeLeft:F1}s)",
                    HorizontalExpand = true,
                    ClipText = true
                });

                var approve = new Button { Text = Loc.GetString("game-flow-control-approve") };
                approve.OnPressed += _ => _eui.SendMessage(new ApproveRuleMsg(rule.Entity));
                row.AddChild(approve);

                var deny = new Button { Text = Loc.GetString("game-flow-control-deny") };
                deny.OnPressed += _ => _eui.SendMessage(new DenyRuleMsg(rule.Entity));
                row.AddChild(deny);

                PendingContainer.AddChild(row);
            }
        }

        // 4. Past rules (History)
        HistoryContainer.DisposeAllChildren();
        if (state.PastRules.Count == 0)
        {
            HistoryContainer.AddChild(new Label
            {
                Text = Loc.GetString("game-flow-control-history-empty"),
                StyleClasses = { "Dimmed" }
            });
        }
        else
        {
            foreach (var past in state.PastRules.AsEnumerable().Reverse())
            {
                var displayName = GetRuleDisplayName(past.RuleId);
                HistoryContainer.AddChild(new Label
                {
                    Text = $"[{past.Time}] {displayName}"
                });
            }
        }

        // 5. Update rules database if changed
        if (!_allRules.SequenceEqual(state.AllRules))
        {
            _allRules = state.AllRules;
            PopulateRulesList();
        }
    }

    private void PopulateRulesList()
    {
        RulesList.Clear();
        var filter = SearchEdit.Text.Trim();

        foreach (var rule in _allRules)
        {
            var displayName = rule;
            if (_prototypeManager.TryIndex<EntityPrototype>(rule, out var proto) && !string.IsNullOrEmpty(proto.Name))
            {
                var localized = Loc.GetString(proto.Name);
                if (!string.IsNullOrEmpty(localized))
                    displayName = $"{localized} ({rule})";
            }

            if (!string.IsNullOrEmpty(filter) && !displayName.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            var item = new ItemList.Item(RulesList)
            {
                Text = displayName,
                Metadata = rule
            };

            RulesList.Add(item);
        }

        // Keep Run button state updated
        UpdateRunButton();
    }

    private void OnRuleSelected(ItemList.ItemListSelectedEventArgs args)
    {
        _selectedRule = args.ItemList[args.ItemIndex].Metadata as string;
        UpdateRunButton();
    }

    private void OnRuleDeselected(ItemList.ItemListDeselectedEventArgs args)
    {
        _selectedRule = null;
        UpdateRunButton();
    }

    private void UpdateRunButton()
    {
        RunRuleBtn.Disabled = string.IsNullOrEmpty(_selectedRule);
    }

    private void OnRunRule(BaseButton.ButtonEventArgs args)
    {
        if (string.IsNullOrEmpty(_selectedRule))
            return;

        _eui.SendMessage(new TriggerRuleMsg(_selectedRule));
    }

    private void OnApplyInterval(BaseButton.ButtonEventArgs args)
    {
        _eui.SendMessage(new SetIntervalMsg(MinIntervalSpin.Value, MaxIntervalSpin.Value, TimeLeftSpin.Value));
    }

    private void OnApplyChaos(BaseButton.ButtonEventArgs args)
    {
        _eui.SendMessage(new SetChaosMsg(ChaosScoreSpin.Value));
    }

    private string GetRuleDisplayName(string ruleId)
    {
        var cleanId = ruleId;
        var suffix = "";
        if (cleanId.EndsWith(" (Pending)"))
        {
            cleanId = cleanId.Substring(0, cleanId.Length - " (Pending)".Length);
            suffix = " (Pending)";
        }

        if (_prototypeManager.TryIndex<EntityPrototype>(cleanId, out var proto) && !string.IsNullOrEmpty(proto.Name))
        {
            var localized = Loc.GetString(proto.Name);
            if (!string.IsNullOrEmpty(localized))
                return localized + suffix;
        }

        return ruleId;
    }
}
