using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Guidebook;
using Content.Client.Lobby;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Amour.Humanoid.Prototypes;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;

namespace Content.Client._Orion.Lobby.UI;

//
// License-Identifier: AGPL-3.0-or-later
//

[GenerateTypedNameReferences]
public sealed partial class SpeciesWindow : FancyWindow
{
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;

    public event Action<ProtoId<SpeciesPrototype>>? ChooseAction;
    public ProtoId<SpeciesPrototype> CurrentSpecies;

    public HumanoidCharacterProfile Profile;
    private readonly IPrototypeManager _proto;
    private readonly LobbyUIController _uIController;
    private readonly IResourceManager _resMan;

    public SpeciesWindow(HumanoidCharacterProfile profile,
                        IPrototypeManager proto,
                        LobbyUIController uIController,
                        IResourceManager resManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Select.OnPressed += _ => ChooseAction?.Invoke(CurrentSpecies);

        Title = Loc.GetString("species-window-title");

        Profile = profile;
        _proto = proto;
        _uIController = uIController;
        _resMan = resManager;

        var protoList = _proto.EnumeratePrototypes<SpeciesPrototype>().Where(x => x.RoundStart).ToList();
        protoList.Sort((x, y) => Loc.GetString(x.Name)[0].CompareTo(Loc.GetString(y.Name)[0]));

        AddLabel(Loc.GetString("species-category-label-classic"));
        foreach (var item in protoList.Where(x => x.Category == SpeciesCategory.Classic))
        {
            var button = new SpeciesButton(item)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = Profile.Species == item.ID,
                Text = Loc.GetString(item.Name),
                Margin = new Thickness(5f, 5f),
            };
            button.OnToggled += _ => SelectSpecies(item.ID);
            SpeciesContainer.AddChild(button);
        }

        AddLabel(Loc.GetString("species-category-label-unusual"));
        foreach (var item in protoList.Where(x => x.Category == SpeciesCategory.Unusual))
        {
            var button = new SpeciesButton(item)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = Profile.Species == item.ID,
                Text = Loc.GetString(item.Name),
                Margin = new Thickness(5f, 5f),
            };
            button.OnToggled += _ => SelectSpecies(item.ID);
            SpeciesContainer.AddChild(button);
        }

        AddLabel(Loc.GetString("species-category-label-special"));
        foreach (var item in protoList.Where(x => x.Category == SpeciesCategory.Special))
        {
            var button = new SpeciesButton(item)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = Profile.Species == item.ID,
                Text = Loc.GetString(item.Name),
                Margin = new Thickness(5f, 5f),
            };
            button.OnToggled += _ => SelectSpecies(item.ID);
            SpeciesContainer.AddChild(button);
        }

        CurrentSpecies = Profile.Species;
        SelectSpecies(Profile.Species);
    }

    private void AddLabel(string text)
    {
        var container = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
        };
        var label = new Label()
        {
            Text = text,
            StyleClasses = { StyleBase.ClassLowDivider },
            Margin = new(2f, 2f),
            HorizontalAlignment = HAlignment.Center,
        };
        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };
        container.AddChild(label);
        container.AddChild(separator);

        SpeciesContainer.AddChild(container);
    }

    public void SelectSpecies(ProtoId<SpeciesPrototype> protoId)
    {
        DetailInfoContainer.DisposeAllChildren();

        foreach (var item in SpeciesContainer.Children)
        {
            if (item is not SpeciesButton button)
                continue;
            button.Pressed = protoId == button.Proto;
        }

        var proto = _proto.Index(protoId);
        CurrentSpecies = protoId;

            JobPrototype? jobProto = null;
        var highJob = Profile.JobPriorities.FirstOrDefault(x => x.Value == JobPriority.High);
        if (!string.IsNullOrEmpty(highJob.Key) && _proto.TryIndex(highJob.Key, out var job))
            jobProto = job;

        var previewProfile = Profile;
        previewProfile = previewProfile.WithSpecies(protoId);
        previewProfile = previewProfile.WithBodyType(GetPreviewBodyType(proto, previewProfile.BodyType)); // Amour

        var skin = proto.SkinColoration;
        switch (skin)
        {
            case HumanoidSkinColor.HumanToned:
                {
                    var tone = SkinColor.HumanSkinToneFromColor(Profile.Appearance.SkinColor);
                    var color = SkinColor.HumanSkinTone((int)tone);

                    previewProfile = previewProfile.WithCharacterAppearance(previewProfile.Appearance.WithSkinColor(color));
                    break;
                }
            case HumanoidSkinColor.Hues:
                {
                    break;
                }
            case HumanoidSkinColor.TintedHues:
                {
                    var color = SkinColor.TintedHues(Profile.Appearance.SkinColor);

                    previewProfile = previewProfile.WithCharacterAppearance(previewProfile.Appearance.WithSkinColor(color));
                    break;
                }
            case HumanoidSkinColor.VoxFeathers:
                {
                    var color = SkinColor.ClosestVoxColor(Profile.Appearance.SkinColor);

                    previewProfile = previewProfile.WithCharacterAppearance(previewProfile.Appearance.WithSkinColor(color));
                    break;
                }
            case HumanoidSkinColor.NoColor:
                {
                    var color = Color.White;

                    previewProfile = previewProfile.WithCharacterAppearance(previewProfile.Appearance.WithSkinColor(color));
                    break;
                }
            case HumanoidSkinColor.AnimalFur:
                {
                    var color = SkinColor.ClosestAnimalFurColor(Profile.Appearance.SkinColor);

                    previewProfile = previewProfile.WithCharacterAppearance(previewProfile.Appearance.WithSkinColor(color));
                    break;
                }
        }

        var mob = _uIController.LoadProfileEntity(previewProfile, jobProto, ClothingDisplayMode.HideAll);
        Mob.SetEntity(mob);

        var loadoutMob = _uIController.LoadProfileEntity(previewProfile, jobProto, ClothingDisplayMode.ShowAll);
        JobLoadout.SetEntity(loadoutMob);

        Select.Disabled = Profile.Species == protoId;

        var prosConsContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
            MaxWidth = 380f,
        };
        var prosConsLabel = new RichTextLabel()
        {
            Text = Loc.GetString("ui-species-pros-cons"),
            StyleClasses = { StyleBase.ClassLowDivider },
            Margin = new(2f, 2f),
        };
        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };
        prosConsContainer.AddChild(prosConsLabel);
        prosConsContainer.AddChild(separator);
        DetailInfoContainer.AddChild(prosConsContainer);

        if (proto.Pros.Count <= 0 && proto.Special.Count <= 0 && proto.Cons.Count <= 0)
        {
            var noProsConsLabel = new RichTextLabel()
            {
                Text = Loc.GetString("ui-species-no-pros-cons"),
                Margin = new(4f),
            };
            DetailInfoContainer.AddChild(noProsConsLabel);
        }
        else
        {
            if (proto.Pros.Count > 0)
            {
                foreach (var item in proto.Pros)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "[color=#13f244]- " + Loc.GetString(item) + "[/color]",
                        StyleClasses = { StyleBase.ClassLowDivider },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }

            if (proto.Special.Count > 0)
            {
                foreach (var item in proto.Special)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "- " + Loc.GetString(item),
                        StyleClasses = { StyleBase.ClassLowDivider },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }

            if (proto.Cons.Count > 0)
            {
                foreach (var item in proto.Cons)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "[color=#d63636]- " + Loc.GetString(item) + "[/color]",
                        StyleClasses = { StyleBase.ClassLowDivider },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }
        }

        if (!proto.Description.HasValue)
            return;

        // Take race descriptions text from .xml files, so we need to find and use the content from the specified file
        // Everything works the same way as in the guidebook (yes, you can insert images here)
        using var file = _resMan.ContentFileReadText(proto.Description.Value);
        _parsingMan.TryAddMarkup(DetailInfoContainer, file.ReadToEnd());
    }

    // Amour start
    private string GetPreviewBodyType(SpeciesPrototype species, string currentBodyType)
    {
        var validBodyTypes = species.BodyTypes
            .Where(id => _proto.TryIndex<BodyTypePrototype>(id, out var bodyType) &&
                !bodyType.SexRestrictions.Contains(Profile.Sex.ToString()))
            .ToList();

        if (validBodyTypes.Contains(currentBodyType))
            return currentBodyType;

        if (validBodyTypes.Count > 0)
            return validBodyTypes[0];

        return species.BodyTypes.FirstOrDefault() ?? currentBodyType;
    }
    // Amour end

    private sealed partial class SpeciesButton(ProtoId<SpeciesPrototype> proto) : Button
    {
        public readonly ProtoId<SpeciesPrototype> Proto = proto;
    }
}
