using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Guidebook;
using Content.Client.Stylesheets;
using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared._Amour.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._Orion.Lobby.UI;

//
// SPDX-License-Identifier: AGPL-3.0-or-later
//

[GenerateTypedNameReferences]
public sealed partial class SpeciesWindow : FancyWindow
{
    private readonly DocumentParsingManager _parsingMan;
    private ProtoId<SpeciesPrototype> _currentSpecies;
    private readonly HumanoidCharacterProfile _profile;
    private readonly IPrototypeManager _proto;
    private readonly IResourceManager _resMan;
    private readonly LobbyUIController _uIController;

    public SpeciesWindow(SpeciesWindowContext context)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _profile = context.Profile;
        _currentSpecies = _profile.Species;
        _proto = context.PrototypeManager;
        _resMan = context.ResourceManager;
        _parsingMan = context.ParsingManager;
        _uIController = context.UIController;

        Select.OnPressed += _ => context.OnChosen(_currentSpecies);
        OnClose += context.OnClosed;

        Title = Loc.GetString("species-window-title");

        var protoList = _proto.EnumeratePrototypes<SpeciesPrototype>().Where(x => x.RoundStart).ToList();
        protoList.Sort((x, y) => string.Compare(Loc.GetString(x.Name), Loc.GetString(y.Name), StringComparison.CurrentCulture));

        AddSpeciesCategory("species-category-label-classic", SpeciesCategory.Classic, protoList);
        AddSpeciesCategory("species-category-label-unusual", SpeciesCategory.Unusual, protoList);
        AddSpeciesCategory("species-category-label-special", SpeciesCategory.Special, protoList);
        AddSpeciesCategory("species-category-label-sponsor", SpeciesCategory.Sponsor, protoList);

        SelectSpecies(_profile.Species);
    }

    private void AddSpeciesCategory(string labelKey, SpeciesCategory category, IEnumerable<SpeciesPrototype> prototypes)
    {
        var categoryPrototypes = prototypes.Where(x => x.Category == category).ToList();
        if (categoryPrototypes.Count == 0)
            return;

        AddLabel(Loc.GetString(labelKey));

        foreach (var item in categoryPrototypes)
        {
            var button = new SpeciesButton(item.ID)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = _profile.Species == item.ID,
                Text = Loc.GetString(item.Name),
                Margin = new Thickness(5f, 5f),
            };
            button.OnToggled += args =>
            {
                if (!args.Pressed)
                    return;

                SelectSpecies(item.ID);
            };

            SpeciesContainer.AddChild(button);
        }
    }

    private void AddLabel(string text)
    {
        var container = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
        };

        var label = new Label()
        {
            Text = text,
            StyleClasses = { StyleClass.LowDivider },
            Margin = new(2f, 2f),
            HorizontalAlignment = HAlignment.Center,
        };

        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };

        container.AddChild(label);
        container.AddChild(separator);

        SpeciesContainer.AddChild(container);
    }

    private void SelectSpecies(ProtoId<SpeciesPrototype> protoId)
    {
        DetailInfoContainer.DisposeAllChildren();

        foreach (var item in SpeciesContainer.Children)
        {
            if (item is not SpeciesButton button)
                continue;

            button.Pressed = protoId == button.Proto;
        }

        var proto = _proto.Index(protoId);
        _currentSpecies = protoId;

        JobPrototype? jobProto = null;
        var highJob = _profile.JobPriorities.FirstOrDefault(x => x.Value == JobPriority.High);
        if (!string.IsNullOrEmpty(highJob.Key) && _proto.TryIndex(highJob.Key, out var job))
            jobProto = job;

        var previewProfile = _profile;
        previewProfile = previewProfile.WithSpecies(protoId);
        previewProfile = previewProfile.WithBodyType(GetPreviewBodyType(proto, previewProfile.BodyType));

        var skin = proto.SkinColoration;
        var strategy = _proto.Index<SkinColorationPrototype>(skin).Strategy;
        var color = _profile.Appearance.SkinColor;
        switch (strategy.InputType)
        {
            case SkinColorationStrategyInput.Unary:
                try
                {
                    var tone = strategy.ToUnary(color);
                    color = strategy.FromUnary(tone);
                }
                catch (InvalidOperationException)
                {
                    color = Color.White;
                }
                break;

            case SkinColorationStrategyInput.Color:
                color = strategy.ClosestSkinColor(color);
                break;
        }

        previewProfile = previewProfile.WithCharacterAppearance(previewProfile.Appearance.WithSkinColor(color));

        var mob = _uIController.LoadProfileEntity(previewProfile, jobProto, ClothingDisplayMode.HideAll);
        Mob.SetEntity(mob);

        var loadoutMob = _uIController.LoadProfileEntity(previewProfile, jobProto, ClothingDisplayMode.ShowAll);
        JobLoadout.SetEntity(loadoutMob);

        Select.Disabled = _profile.Species == protoId;

        var prosConsContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
            MaxWidth = 380f,
        };

        var prosConsLabel = new RichTextLabel()
        {
            Text = Loc.GetString("ui-species-pros-cons"),
            StyleClasses = { StyleClass.LowDivider },
            Margin = new(2f, 2f),
        };

        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };

        prosConsContainer.AddChild(prosConsLabel);
        prosConsContainer.AddChild(separator);
        DetailInfoContainer.AddChild(prosConsContainer);

        if (proto.Pros.Count <= 0 && proto.Special.Count <= 0 && proto.Cons.Count <= 0)
        {
            var noProsConsLabel = new RichTextLabel()
            {
                Text = Loc.GetString("ui-species-no-pros-cons"),
                Margin = new(4f),
            };
            prosConsContainer.AddChild(noProsConsLabel);
        }
        else
        {
            if (proto.Pros.Count > 0)
            {
                foreach (var item in proto.Pros)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "[color=#13f244]- " + Loc.GetString(item) + "[/color]",
                        StyleClasses = { StyleClass.LowDivider },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }

            if (proto.Special.Count > 0)
            {
                foreach (var item in proto.Special)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "- " + Loc.GetString(item),
                        StyleClasses = { StyleClass.LowDivider },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }

            if (proto.Cons.Count > 0)
            {
                foreach (var item in proto.Cons)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "[color=#d63636]- " + Loc.GetString(item) + "[/color]",
                        StyleClasses = { StyleClass.LowDivider },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }
        }

        if (!proto.Description.HasValue)
            return;

        // Take race descriptions text from .xml files, so we need to find and use the content from the specified file.
        // Everything works the same way as in the guidebook (yes, you can insert images here)
        if (!_resMan.TryContentFileRead(proto.Description.Value, out var file))
            return;

        using (file)
        using (var reader = new StreamReader(file))
        {
            _parsingMan.TryAddMarkup(DetailInfoContainer, reader.ReadToEnd());
        }
    }

    private string GetPreviewBodyType(SpeciesPrototype species, string currentBodyType)
    {
        var validBodyTypes = species.BodyTypes
            .Where(id => _proto.TryIndex<BodyTypePrototype>(id, out var bodyType) &&
                !bodyType.SexRestrictions.Contains(_profile.Sex.ToString()))
            .ToList();

        if (validBodyTypes.Contains(currentBodyType))
            return currentBodyType;

        if (validBodyTypes.Count > 0)
            return validBodyTypes[0];

        return species.BodyTypes.FirstOrDefault() ?? currentBodyType;
    }

    private sealed class SpeciesButton(string proto) : Button
    {
        public readonly string Proto = proto;
    }
}

public sealed record SpeciesWindowContext(
    HumanoidCharacterProfile Profile,
    IPrototypeManager PrototypeManager,
    IResourceManager ResourceManager,
    DocumentParsingManager ParsingManager,
    LobbyUIController UIController,
    Action<ProtoId<SpeciesPrototype>> OnChosen,
    Action OnClosed);
