- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodCultist
  name: Blood Cultist Role
  components:
  - type: MindRole
    antagPrototype: BloodCultist
    roleType: TeamAntagonist
    subtype: role-subtype-blood-cultist
  - type: BloodCultistRole

# Morph

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleMorph
  name: Ghost Role (Morph)
  components:
  - type: MindRole
    antagPrototype: Morph
    roleType: TeamAntagonist
    exclusiveAntag: true
  - type: MorphRole

# InteQ

- type: entity
  parent: [ BaseMindRoleAntag, MindRoleGhostRoleNeutral ]
  id: MindRoleGhostRoleInteQAntagonist
  name: Ghost Role (InteQ Antagonist)
  components:
  - type: MindRole
    roleType: InteQ
    antagPrototype: GenericTeamAntagonist

# Cortical Borer

- type: entity
  parent: [ BaseMindRoleAntag, MindRoleGhostRoleNeutral ]
  id: MindRoleCorticalBorer
  name: Ghost Role (Cortical Borer)
  components:
  - type: MindRole
    antagPrototype: CorticalBorer
    roleType: SoloAntagonist
    exclusiveAntag: true
  - type: CorticalBorerRole
