# SPDX-License-Identifier: MIT

contact_links:
  - name: Сообщить об уязвимости
    url: https://github.com/red-wing-ss14/Reserve-Station?tab=security-ov-file
    about: Пожалуйста, свяжитесь с нашей администрацией о любых уязвимостях приватно, чтобы избежать дополнительных рисков.
  - name: Предложить изменение
    url: https://discord.gg/WXZvqzZ2Fc
    about: Предложить нововведения и изменения можно на нашем сервере. Хочешь, чтобы твой запрос кто-то обязательно реализовал? Посети наш баунти трекер!
