using System.Globalization;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Orion.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyCardWindow : DefaultWindow
{
    public EconomyCardWindow()
    {
        RobustXamlLoader.Load(this);

        ApplyStaticStyling();
    }

    private void ApplyStaticStyling()
    {
        CardPanel.PanelOverride = Panel("#151A24", "#2B3445", 1, 8, 8);
        BalancePanel.PanelOverride = Panel("#141A22", "#2B3445", 1, 6, 6);
        WithdrawPanel.PanelOverride = Panel("#121822", "#2B3445", 1, 6, 6);


        BrandLabel.FontColorOverride = Color.FromHex("#D7B56D");
        MaskedAccountLabel.FontColorOverride = Color.FromHex("#F2F4F8");
        AccountCaptionLabel.FontColorOverride = Color.FromHex("#9AA4B2");

        AvailableBalanceTitleLabel.FontColorOverride = Color.FromHex("#9AA4B2");
        BalanceValueLabel.FontColorOverride = Color.FromHex("#67E8A5");

        WithdrawStatusLabel.FontColorOverride = Color.FromHex("#9AA4B2");
        ManualAccountWarning.FontColorOverride = Color.FromHex("#E06C75");

        WithdrawButton.ModulateSelfOverride = Color.FromHex("#53C78F");
    }

    private static StyleBoxFlat Panel(string background, string border, int borderSize, int h, int v)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(borderSize),
            ContentMarginLeftOverride = h,
            ContentMarginRightOverride = h,
            ContentMarginTopOverride = v,
            ContentMarginBottomOverride = v,
        };
    }

    public string FormatCredits(int amount)
    {
        return Loc.GetString("economy-card-balance-value", ("balance", amount.ToString("N0", CultureInfo.InvariantCulture)));
    }

    public string MaskAccountId(string? accountId)
    {
        if (string.IsNullOrWhiteSpace(accountId))
            return Loc.GetString("economy-card-no-account");

        var trimmed = accountId.Trim();
        var suffix = trimmed.Length <= 4 ? trimmed : trimmed[^4..];
        return $"•••• •••• •••• {suffix}";
    }
}
