using System.Numerics;
using Content.Shared.Labels.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Funkystation.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class VendingMachineGridSlot : PanelContainer
{
    [Dependency] private IPrototypeManager _protoManager = null!;
    [Dependency] private ILocalizationManager _loc = null!;

    private const float SlotWidth = 84f;
    private const float PriceBarHeight = 18f;
    private const float SlotHeight = 84f + PriceBarHeight;
    private const float ItemSize = 64f;
    private const float BadgeSize = 20f;
    private const float SoldOverlayHeight = 22f;
    private const float AnimDuration = 0.55f;
    private const float DropDistance = 20f;
    private const float IconScale = 2.5f;
    private readonly Vector2 _restingPos;
    private bool _animating;
    private float _animElapsed;
    private bool _pendingSoldOut;

    // price tag colors
    private static readonly Color FreeColor = Color.FromHex("#66ccff");
    private static readonly Color AffordableColor = Color.FromHex("#8fe08f");
    private static readonly Color UnaffordableColor = Color.FromHex("#ff6b6b");

    // highlighting
    private readonly StyleBoxFlat _normalStyle = new() { BackgroundColor = new Color(30, 30, 40), BorderColor = new Color(90, 90, 105), BorderThickness = new Thickness(1) };
    private readonly StyleBoxFlat _rowMatchStyle = new() { BackgroundColor = new Color(40, 50, 70), BorderColor = new Color(120, 140, 190), BorderThickness = new Thickness(2) };
    private readonly StyleBoxFlat _exactMatchStyle = new() { BackgroundColor = new Color(40, 70, 40), BorderColor = new Color(100, 255, 100), BorderThickness = new Thickness(2) };

    public bool SoldOut { get; private set; }

    public int Price { get; private set; }

    public VendingMachineGridSlot()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Stop;

        MinSize = SetSize = new Vector2(SlotWidth, SlotHeight);

        PanelOverride = _normalStyle;

        SlotLayout.SetSize = new Vector2(SlotWidth, SlotHeight);
        LayoutContainer.SetPosition(SlotLayout, Vector2.Zero);

        // the item sits centered in whatever is left above the price bar
        var itemAreaHeight = SlotHeight - PriceBarHeight;
        _restingPos = new Vector2((SlotWidth - ItemSize) / 2f, (itemAreaHeight - ItemSize) / 2f);
        ItemSprite.SetSize = new Vector2(ItemSize, ItemSize);
        ItemSprite.Scale = new Vector2(IconScale, IconScale);
        LayoutContainer.SetPosition(ItemSprite, _restingPos);

        LayoutContainer.SetPosition(CodeLabel, new Vector2(2f, 2f));

        AmountBadge.SetSize = new Vector2(BadgeSize, BadgeSize);
        LayoutContainer.SetPosition(AmountBadge, new Vector2(SlotWidth - BadgeSize - 2f, 2f));

        PriceBar.SetSize = new Vector2(SlotWidth, PriceBarHeight);
        LayoutContainer.SetPosition(PriceBar, new Vector2(0f, SlotHeight - PriceBarHeight));

        SoldOverlay.SetSize = new Vector2(SlotWidth, SoldOverlayHeight);
        LayoutContainer.SetPosition(SoldOverlay, new Vector2(0f, (itemAreaHeight - SoldOverlayHeight) / 2f));
    }

    public void SetItem(EntProtoId protoId, string code, uint amount, bool soldOut, int price, bool affordable)
    {
        CodeLabel.Text = code;
        ItemSprite.SetPrototype(protoId);

        if (_protoManager.TryIndex(protoId, out var proto))
        {
            var tooltipText = proto.Name;

            if (proto.Components.TryGetValue("Label", out var labelEntry) &&
                labelEntry.Component is LabelComponent label &&
                !string.IsNullOrWhiteSpace(label.CurrentLabel))
            {
                var labelText = _loc.TryGetString(label.CurrentLabel, out var localized)
                    ? localized
                    : label.CurrentLabel;

                tooltipText = $"{proto.Name} ({labelText})";
            }

            ToolTip = string.IsNullOrWhiteSpace(proto.Description)
                ? tooltipText
                : $"{tooltipText}\n{proto.Description}";
        }

        SetPrice(price, affordable);
        SetAmount(amount, soldOut);
    }

    public void SetPrice(int price, bool affordable)
    {
        Price = price;

        if (price <= 0)
        {
            PriceLabel.Text = Loc.GetString("vending-machine-keypad-price-free");
            PriceLabel.FontColorOverride = FreeColor;
            return;
        }

        PriceLabel.Text = Loc.GetString("vending-machine-keypad-price-value", ("amount", price));
        PriceLabel.FontColorOverride = affordable ? AffordableColor : UnaffordableColor;
    }

    public void SetAmount(uint amount, bool soldOut)
    {
        AmountLabel.Text = amount.ToString();
        SoldOut = soldOut;

        if (_animating)
        {
            _pendingSoldOut = soldOut;
            return;
        }

        ApplySoldOutState(soldOut);
    }

    public void SetHighlight(bool isRowMatch, bool isExactMatch)
    {
        if (isExactMatch)
            PanelOverride = _exactMatchStyle;
        else if (isRowMatch)
            PanelOverride = _rowMatchStyle;
        else
            PanelOverride = _normalStyle;
    }

    private void ApplySoldOutState(bool soldOut)
    {
        SoldOverlay.Visible = soldOut;
        ItemSprite.Visible = true;
        ItemSprite.Modulate = soldOut ? Color.White.WithAlpha(0.3f) : Color.White;
        AmountBadge.Visible = !soldOut;
    }

    public void PlayVendAnimation()
    {
        _animating = true;
        _animElapsed = 0f;
        _pendingSoldOut = SoldOverlay.Visible;

        ItemSprite.Visible = true;
        ItemSprite.Modulate = Color.White;
        LayoutContainer.SetPosition(ItemSprite, _restingPos);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_animating)
            return;

        _animElapsed += args.DeltaSeconds;
        var t = Math.Clamp(_animElapsed / AnimDuration, 0f, 1f);

        var pos = _restingPos + new Vector2(0f, DropDistance * t);
        LayoutContainer.SetPosition(ItemSprite, pos);
        ItemSprite.Modulate = Color.White.WithAlpha(1f - t);

        if (t >= 1f)
        {
            _animating = false;
            LayoutContainer.SetPosition(ItemSprite, _restingPos);
            ItemSprite.Modulate = Color.White;

            ApplySoldOutState(_pendingSoldOut);
        }
    }
}
