using Content.Client.UserInterface.Controls;
using Content.Shared._RW.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RW.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class DestructiveAnalyzerMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public event Action? OnServerButtonPressed;
    public event Action<string>? OnMethodSelected;
    public event Action? OnAnalyzePressed;
    public event Action? OnEjectPressed;

    public DestructiveAnalyzerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        AnalyzeButton.OnPressed += _ => OnAnalyzePressed?.Invoke();
        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
        MethodOption.OnItemSelected += args =>
        {
            if (MethodOption.GetItemMetadata(args.Id) is not string id)
                return;

            OnMethodSelected?.Invoke(id);
        };
    }

    private string LocalizeMethod(string methodId)
    {
        const string prefix = "reveal:";
        if (methodId.StartsWith(prefix, StringComparison.Ordinal))
        {
            var technologyId = methodId[prefix.Length..];
            var technologyName = technologyId;
            if (_prototype.TryIndex<TechnologyPrototype>(technologyId, out var technology))
                technologyName = Loc.GetString(technology.Name);

            return Loc.GetString("research-machine-destructive-method-reveal-technology", ("technology", technologyName));
        }

        var key = $"research-machine-destructive-method-{methodId.ToLowerInvariant()}";
        return _loc.TryGetString(key, out var localized)
            ? localized
            : Loc.GetString("research-machine-destructive-method-unknown");
    }

    private static string FormatServerName(string name)
    {
        const string prefix = "RND-Server";
        if (!name.StartsWith(prefix, StringComparison.Ordinal))
            return name;

        var suffix = name[prefix.Length..].TrimStart();
        return string.IsNullOrWhiteSpace(suffix)
            ? Loc.GetString("research-server-name-base")
            : Loc.GetString("research-server-name-with-suffix", ("suffix", suffix));
    }

    public void UpdateState(DestructiveAnalyzerBoundInterfaceState state)
    {
        ServerLabel.Text = state.ConnectedServerName == null
            ? Loc.GetString("research-machine-common-server-none")
            : Loc.GetString("research-machine-common-server-current", ("name", FormatServerName(state.ConnectedServerName)));

        InsertedItemLabel.Text = Loc.GetString("research-machine-common-labeled-value",
            ("label", Loc.GetString("research-machine-common-last-subject")),
            ("value", state.InsertedItem ?? Loc.GetString("research-machine-common-none")));
        if (state.InsertedItemEntity is { } net && _entManager.TryGetEntity(net, out var uid))
            InsertedItemSprite.SetEntity(uid);
        else
            InsertedItemSprite.SetEntity(null);

        MethodOption.Clear();

        MethodContainer.Visible = state.Methods.Count > 0;
        MethodOption.Visible = state.Methods.Count > 0;
        for (var i = 0; i < state.Methods.Count; i++)
        {
            var method = state.Methods[i];
            MethodOption.AddItem(LocalizeMethod(method), i);
            MethodOption.SetItemMetadata(i, method);
            if (method == state.SelectedMethod)
                MethodOption.SelectId(i);
        }

        var subject = string.IsNullOrWhiteSpace(state.LastSubject)
            ? Loc.GetString("research-machine-common-none")
            : state.LastSubject;
        var result = string.IsNullOrWhiteSpace(state.LastResult)
            ? Loc.GetString("research-machine-common-none")
            : state.LastResult;

        LastSubjectLabel.Text = $"{Loc.GetString("research-machine-common-last-subject")}: {subject}";
        LastResultLabel.Text = $"{Loc.GetString("research-machine-common-last-result")}: {result}";

        EjectButton.Disabled = state.InsertedItem == null;
    }
}
