using Content.Client.UserInterface.Controls;
using Content.Shared._RW.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RW.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ExperiScannerMenu : FancyWindow
{
    public event Action? OnServerButtonPressed;

    public ExperiScannerMenu()
    {
        RobustXamlLoader.Load(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
    }

    public void UpdateState(ExperiScannerBoundInterfaceState state)
    {
        ServerLabel.Text = state.ConnectedServerName == null
            ? Loc.GetString("research-machine-common-server-none")
            : Loc.GetString("research-machine-common-server-current", ("name", ResearchExperimentUiHelpers.FormatServerName(state.ConnectedServerName)));

        OperationsContainer.RemoveAllChildren();
        foreach (var experiment in state.Experiments)
        {
            OperationsContainer.AddChild(ResearchExperimentUiHelpers.BuildExperimentEntry(experiment));
        }

        if (state.Experiments.Count == 0)
        {
            OperationsContainer.AddChild(new Label
            {
                Text = Loc.GetString("research-experi-scanner-no-experiments"),
                Modulate = Color.Gray,
            });
        }

        LastOperationLabel.SetMessage(ResearchExperimentUiHelpers.CreateLastOperationMessage(state.LastResult));
    }
}
