using Content.Client.UserInterface.Controls;
using Content.Shared._RW.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RW.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ExperimentalDestructiveScannerMenu : FancyWindow
{
    public event Action? OnServerButtonPressed;
    public event Action? OnPerformPressed;

    public ExperimentalDestructiveScannerMenu()
    {
        RobustXamlLoader.Load(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        PerformButton.OnPressed += _ => OnPerformPressed?.Invoke();
    }

    public void UpdateState(ExperimentalDestructiveScannerBoundInterfaceState state)
    {
        ServerLabel.Text = state.ConnectedServerName == null
            ? Loc.GetString("research-machine-common-server-none")
            : Loc.GetString("research-machine-common-server-current", ("name", ResearchExperimentUiHelpers.FormatServerName(state.ConnectedServerName)));

        InsertedItemLabel.Text = Loc.GetString("research-machine-common-labeled-value",
            ("label", Loc.GetString("research-machine-experimental-destructive-scanner-status")),
            ("value", state.InsertedItem ?? Loc.GetString("research-machine-common-none")));

        OperationsContainer.RemoveAllChildren();
        foreach (var experiment in state.Experiments)
        {
            OperationsContainer.AddChild(ResearchExperimentUiHelpers.BuildExperimentEntry(experiment));
        }

        if (state.Experiments.Count == 0)
        {
            OperationsContainer.AddChild(new Label
            {
                Text = Loc.GetString("research-machine-experimental-destructive-scanner-operations-empty"),
                Modulate = Color.Gray,
            });
        }

        LastOperationLabel.SetMessage(ResearchExperimentUiHelpers.CreateLastOperationMessage(state.LastResult));
    }
}
