using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RW.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleLogWindow : FancyWindow
{
    public FancyResearchConsoleLogWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetExperimentEntries(List<Control> entries)
    {
        ExperimentsContainer.RemoveAllChildren();

        foreach (var entry in entries)
        {
            ExperimentsContainer.AddChild(entry);
        }
    }

    public void SetLogsMessage(FormattedMessage message)
    {
        LogsLabel.SetMessage(message);
    }
}
