using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._RW.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RW.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchServerControlMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public event Action<int>? OnToggleRequested;

    public ResearchServerControlMenu()
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);
    }

    private string LocalizePointType(string type)
    {
        var key = $"research-point-type-{type.ToLowerInvariant()}";
        return _loc.TryGetString(key, out var localized) ? localized : type;
    }

    private string FormatPointsPerSecond(int points)
    {
        return Loc.GetString("research-server-control-points-per-second", ("amount", points));
    }

    private static string FormatServerName(string name)
    {
        const string prefix = "RND-Server";
        if (!name.StartsWith(prefix, StringComparison.Ordinal))
            return name;

        var suffix = name[prefix.Length..].TrimStart();
        return string.IsNullOrWhiteSpace(suffix)
            ? Loc.GetString("research-server-name-base")
            : Loc.GetString("research-server-name-with-suffix", ("suffix", suffix));
    }

    public void Populate(List<ResearchServerControlEntry> servers)
    {
        ServerEntries.DisposeAllChildren();

        foreach (var server in servers)
        {
            var generation = string.Join(", ", server.PointGeneration.Select(p => $"{LocalizePointType(p.Type)}: {FormatPointsPerSecond(p.Amount)}"));
            var balances = string.Join(", ", server.Balances.Select(p => $"{LocalizePointType(p.Type)}: {p.Amount}"));

            var entryContainer = new PanelContainer
            {
                HorizontalExpand = true,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#23232A"),
                    BorderColor = Color.FromHex("#4A4A56"),
                    BorderThickness = new Thickness(1),
                },
            };

            var line = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(8),
                SeparationOverride = 3,
            };

            var nameRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 6,
                HorizontalExpand = true,
            };
            var icon = new SpriteView
            {
                Scale = new Vector2(1.5f, 1.5f),
                VerticalAlignment = VAlignment.Center,
                OverrideDirection = Direction.South,
            };

            if (_entityManager.TryGetEntity(server.ServerEntity, out var serverUid))
                icon.SetEntity(serverUid);

            nameRow.AddChild(icon);
            nameRow.AddChild(new Label
            {
                Text = $"#{server.Id} {FormatServerName(server.Name)}",
                HorizontalExpand = true,
            });
            line.AddChild(nameRow);

            line.AddChild(new Label { Text = Loc.GetString("research-server-control-network", ("network", server.NetworkId)) });
            line.AddChild(new Label
            {
                Text = server.IsNetworkAuthority
                    ? Loc.GetString("research-server-control-network-authority")
                    : Loc.GetString("research-server-control-network-forwarded", ("authorityId", server.NetworkAuthorityId)),
                Modulate = server.IsNetworkAuthority ? Color.LightGreen : Color.LightGray,
            });

            line.AddChild(new Label { Text = Loc.GetString("research-server-control-generation", ("state", Loc.GetString(server.GenerationEnabled ? "research-server-control-state-enabled" : "research-server-control-state-disabled")), ("total", server.TotalPointsPerSecond)) });
            line.AddChild(new Label { Text = Loc.GetString("research-server-control-generation-by-type", ("generation", generation)) });
            line.AddChild(new Label { Text = Loc.GetString("research-server-control-balances", ("balances", balances)) });
            line.AddChild(new Label { Text = Loc.GetString("research-server-control-logs", ("count", server.LogCount)) });

            var toggle = new Button
            {
                Text = server.GenerationEnabled ? Loc.GetString("research-server-control-disable") : Loc.GetString("research-server-control-enable"),
                HorizontalExpand = true,
            };
            var id = server.Id;
            toggle.OnPressed += _ => OnToggleRequested?.Invoke(id);
            line.AddChild(toggle);

            entryContainer.AddChild(line);
            ServerEntries.AddChild(entryContainer);
        }

        if (servers.Count == 0)
        {
            ServerEntries.AddChild(new Label
            {
                Text = Loc.GetString("research-server-control-empty"),
                Modulate = Color.Gray,
            });
        }
    }
}
