# SPDX-License-Identifier: AGPL-3.0-or-later

- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  # Orion-Start
  weight: -7
  buttonStyle: ButtonColorCargoDepartment
  # Orion-End
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - ShaftMiner # Lavaland Change
  - Bitrunner # Orion

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  # Orion-Start
  weight: -8
  buttonStyle: ButtonColorCivilianDepartment
  # Orion-End
  roles:
  - Bartender
  - Botanist
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - ServiceWorker
  - PartyMaker # event-restricted, Goobstation

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  # Orion-Start
  weight: -2
  buttonStyle: ButtonColorCentralCommandDepartment
  # Orion-End
  roles:
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - HecuOperative
  - BlueshieldOfficer # Goobstation - Start
  - NanotrasenRepresentative
  - NanotrasenCareerTrainer
  - NavyOfficer
  - NavyCaptain
  - NavyOfficerUndercover
  - SpecialOperationsOfficer
  - Diplomat
  - GovernmentMan # Goobstation - End
#  editorHidden: true # Orion-Edit: true > false
#  weight: 120 # Orion-Edit: Moved

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  # Orion-Start
  weight: -1
  buttonStyle: ButtonColorCommandDepartment
  # Orion-End
  roles:
  - Captain
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  # Orion-Edit-Start: Now it only in (CentralCommand)
#  - BlueshieldOfficer # Goobstation
#  - NanotrasenRepresentative # Goobstation
#  - NanotrasenCareerTrainer # Goobstation
  # Orion-Edit-End
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - HecuOperative
  - CommandMaid # event-restricted, Goobstation
  primary: false
#  weight: 100 # Orion-Edit: Moved

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  # Orion-Start
  weight: -4
  buttonStyle: ButtonColorEngineeringDepartment
  # Orion-End
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  # Orion-Start
  weight: -6
  buttonStyle: ButtonColorMedicalDepartment
  # Orion-End
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - Virologist # Gooby goob ba gooby goob ba

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#DE3A3A"
  # Orion-Start
  weight: -3
  buttonStyle: ButtonColorSecurityDepartment
  # Orion-End
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  - Brigmedic # Goob
  - SecurityClown # event-restricted, Goob

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#D381C9"
  # Orion-Start
  weight: -5
  buttonStyle: ButtonColorScienceDepartment
  # Orion-End
  roles:
  - ResearchDirector
  - Scientist
  - ResearchAssistant
  - Roboticist #Goob

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  # Orion-Start
  weight: -9
  buttonStyle: ButtonColorSiliconDepartment
  # Orion-End
  roles:
  - Borg
  - StationAi

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  # Orion-Start
  weight: -42
  buttonStyle: ButtonColorSpecificDepartment
  # Orion-End
  roles:
  - RadioHost # Goobstation
  - Reporter
  - Psychologist
  primary: false
