using System.Linq;
using System.Numerics;
using Content.Client._Orion.RichText;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.DetailExaminable;
using Content.Shared._Orion.RichText;
using Content.Shared.CCVar;
using Content.Shared.Inventory;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Orion.DetailExaminable;

//
// License-Identifier: GPL-3.0-or-later
//

[GenerateTypedNameReferences]
public sealed partial class DetailExaminableWindow : FancyWindow
{
    private readonly List<Direction> _rotationSequence = new()
    {
        Direction.East,
        Direction.North,
        Direction.West,
        Direction.South,
    };

    private int _currentDirectionIndex = 3;
    private EntityUid? _currentEntity;
    private SpriteView? _spriteView;

    public DetailExaminableWindow()
    {
        RobustXamlLoader.Load(this);

        RotateLeftButton.OnPressed += _ => RotateDirection(-1);
        RotateRightButton.OnPressed += _ => RotateDirection(1);
    }

    private void RotateDirection(int step)
    {
        _currentDirectionIndex = (_currentDirectionIndex + step + _rotationSequence.Count) % _rotationSequence.Count;
        UpdateSpriteDirection();
    }

    private void UpdateSpriteDirection()
    {
        if (_currentEntity == null || TargetPreview == null)
            return;

        TargetPreview.RemoveAllChildren();

        _spriteView = new SpriteView // TODO: Better view for 32x48* sprites
        {
            OverrideDirection = _rotationSequence[_currentDirectionIndex],
            Scale = new Vector2(8f, 8f),
//            MaxSize = new Vector2(64, 256), // This killing 32x48* sprites
            MinSize = new Vector2(32, 128),
            Stretch = SpriteView.StretchMode.Fit,
        };

        _spriteView.SetEntity(_currentEntity.Value);
        TargetPreview.AddChild(_spriteView);
    }



    public void UpdateState(DetailExaminableEuiState state, IEntityManager entManager)
    {
        var config = IoCManager.Resolve<IConfigurationManager>();
        _currentEntity = entManager.GetEntity(state.Target);

        var isClothed = IsCharacterClothed(_currentEntity.Value, entManager);

        PreviewTabs.SetTabTitle(0, Loc.GetString("flavor-tab-flavor"));
        PreviewTabs.SetTabTitle(1, Loc.GetString("flavor-tab-character"));
        PreviewTabs.SetTabTitle(2, Loc.GetString("flavor-tab-gyr"));

        // Hide things if they are disabled in CCVars
        var showTraits = config.GetCVar(CCVars.FlavorTraitsEnabled);
        var showFlavor = config.GetCVar(CCVars.FlavorText);
        var showGyr = config.GetCVar(CCVars.FlavorGyrEnabled);

        PreviewTabs.SetTabVisible(0, showFlavor);
        PreviewTabs.SetTabVisible(1, showTraits);
        PreviewTabs.SetTabVisible(2, showGyr);

        var prototypeManager = IoCManager.Resolve<IPrototypeManager>();
        var species = prototypeManager.TryIndex(state.Species, out var speciesProto)
            ? Loc.GetString(speciesProto.Name)
            : state.Species.ToString();
        var sex = Loc.GetString($"humanoid-profile-editor-sex-{state.Sex.ToString().ToLower()}-text");
        var gender = Loc.GetString($"humanoid-profile-editor-pronouns-{state.Gender.ToString().ToLower()}-text");

        PreviewNameText.Text = state.Name;
        PreviewGenderText.Text = $"{species} | {sex} | {gender}";

        UpdateSpriteDirection();

        SetDescriptionMarkup(PreviewAppearanceText, state.FlavorText, "detail-examinable-empty-flavor");


        if (showTraits)
            SetDescriptionMarkup(PreviewTraitsText, state.CharacterFlavorText, "detail-examinable-empty-character");

        if (showGyr)
        {
            PreviewGYRContainer.RemoveAllChildren();

            PreviewGYRContainer.AddChild(CreateSectionHeader("humanoid-profile-editor-gyr-green", Color.Green, useStripeBack: true));
            CreateGyrTextLabel(GetContentWithEmptyMessage(state.GreenFlavorText, "detail-examinable-empty-green"));

            PreviewGYRContainer.AddChild(CreateSectionHeader("humanoid-profile-editor-gyr-yellow", Color.Yellow, useStripeBack: true));
            CreateGyrTextLabel(GetContentWithEmptyMessage(state.YellowFlavorText, "detail-examinable-empty-yellow"));

            PreviewGYRContainer.AddChild(CreateSectionHeader("humanoid-profile-editor-gyr-red", Color.Red, useStripeBack: true));
            CreateGyrTextLabel(GetContentWithEmptyMessage(state.RedFlavorText, "detail-examinable-empty-red"));
        }


        Badge.Visible = PlayerBadge();
    }

    private static string GetContentWithEmptyMessage(string content, string emptyMessageKey)
    {
        if (string.IsNullOrWhiteSpace(content))
            return Loc.GetString(emptyMessageKey);

        return content;
    }

    private void CreateGyrTextLabel(string text)
    {
        var label = new RichTextLabel
        {
            VerticalExpand = true,
        };

        SetDescriptionMarkup(label, text + "\n");
        PreviewGYRContainer.AddChild(label);
    }


    private Control CreateSectionHeader(string text, Color? color = null, bool useStripeBack = true)
    {
        var label = new Label
        {
            Text = Loc.GetString(text),
            StyleClasses = { "LabelBig" },
            Align = Label.AlignMode.Center,
        };

        if (color.HasValue)
            label.FontColorOverride = color.Value;

        if (!useStripeBack)
            return label;

        var stripe = new StripeBack();
        stripe.AddChild(label);
        return stripe;
    }

    private bool PlayerBadge() // TODO: Something like donator, coder, owner badges
    {
        if (_currentEntity == null)
            return false;

        var playerManager = IoCManager.Resolve<IPlayerManager>();
        if (!playerManager.TryGetSessionByEntity(_currentEntity.Value, out var session))
            return false;

        var playerName = session.Name;
        var ckeyToMatch = playerName.StartsWith("localhost@", StringComparison.OrdinalIgnoreCase)
            ? playerName.Substring("localhost@".Length)
            : playerName;

        var ckeyLower = ckeyToMatch.ToLowerInvariant();
        var grantedCKeys = new[] { "puroslavking" };

        return grantedCKeys.Contains(ckeyLower);
    }

    private bool IsCharacterClothed(EntityUid entity, IEntityManager entManager) // Hide NSFW flavor if character is clothed
    {
        if (entity == EntityUid.Invalid)
            return false;

        var inventorySystem = entManager.System<InventorySystem>();

        return inventorySystem.TryGetSlotEntity(entity, "outerClothing", out _) ||
               inventorySystem.TryGetSlotEntity(entity, "jumpsuit", out _);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _spriteView?.Dispose();
            _spriteView = null;

            TargetPreview?.RemoveAllChildren();
        }

        base.Dispose(disposing);
    }

    private static void SetDescriptionMarkup(RichTextLabel label, string content)
    {
        var safeContent = SafeMarkup.SanitizeBasic(content);
        label.SetMessage(FormattedMessage.FromMarkupPermissive(safeContent), SafeMarkupTags.Basic);
    }

    private static void SetDescriptionMarkup(RichTextLabel label, string content, string emptyMessageKey)
    {
        SetDescriptionMarkup(label, GetContentWithEmptyMessage(content, emptyMessageKey));
    }
}
