- type: job
  id: Bitrunner
  name: job-name-bitrunner
  description: job-description-bitrunner
  playTimeTracker: JobBitrunner
  setPreference: false # TODO
  startingGear: CargoTechGear # TODO
  icon: "JobIconBitrunner"
  supervisors: job-supervisors-qm
  goobcoins: 20 #Goob content
  # Orion-Start
  salary: 40
  payrollDepartmentAccount: Cargo
  # Orion-End
  access:
  - Cargo
  - Bitrun
  - Maintenance
  extendedAccess:
  - Salvage
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard
