// SPDX-License-Identifier: MIT

using System.Linq;
using Content.Shared._Amour.Loadouts.Effects;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    [Dependency] private readonly MarkingManager _markingManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!; // Amour

    private readonly SpriteSystem _sprite;

    public Action<MarkingSet>? OnMarkingAdded;
    public Action<MarkingSet>? OnMarkingRemoved;
    public Action<MarkingSet>? OnMarkingColorChange;
    public Action<MarkingSet>? OnMarkingRankChange;

    private List<Color> _currentMarkingColors = new();

    // Amour edit start: gradient-mode state for the currently selected marking.
    private List<Color> _currentSecondaryColors = new();
    private List<BoxContainer> _currentGradientContainers = new();
    private bool _currentUseGradient;
    private float _currentGradientPosition;
    private float _currentGradientBlur;
    // Amour edit end

    private ItemList.Item? _selectedMarking;
    private ItemList.Item? _selectedUnusedMarking;
    private MarkingCategories _selectedMarkingCategory = MarkingCategories.Chest;

    private MarkingSet _currentMarkings = new();

    private List<MarkingCategories> _markingCategories = Enum.GetValues<MarkingCategories>().ToList();

    private string _currentSpecies = SharedHumanoidAppearanceSystem.DefaultSpecies;
    private Sex _currentSex = Sex.Unsexed;
    public Color CurrentSkinColor = Color.White;
    public Color CurrentEyeColor = Color.Black;
    public Marking? HairMarking;
    public Marking? FacialHairMarking;

    private readonly HashSet<MarkingCategories> _ignoreCategories = new();

    public string IgnoreCategories
    {
        get => string.Join(',',  _ignoreCategories);
        set
        {
            _ignoreCategories.Clear();
            var split = value.Split(',');
            foreach (var category in split)
            {
                if (!Enum.TryParse(category, out MarkingCategories categoryParse))
                {
                    continue;
                }

                _ignoreCategories.Add(categoryParse);
            }

            SetupCategoryButtons();
        }
    }

    public bool Forced { get; set; }

    private bool _ignoreSpecies;

    public bool IgnoreSpecies
    {
        get => _ignoreSpecies;
        set
        {
            _ignoreSpecies = value;
            Populate(CMarkingSearch.Text);
        }
    }

    public void SetData(List<Marking> newMarkings, string species, Sex sex, Color skinColor, Color eyeColor)
    {
        var pointsProto = _prototypeManager
            .Index<SpeciesPrototype>(species).MarkingPoints;
        _currentMarkings = new(newMarkings, pointsProto, _markingManager);

        if (!IgnoreSpecies)
        {
            _currentMarkings.EnsureSpecies(species, skinColor, _markingManager, null); // should be validated server-side but it can't hurt // Amour add null
        }

        _currentSpecies = species;
        _currentSex = sex;
        CurrentSkinColor = skinColor;
        CurrentEyeColor = eyeColor;

        Populate(CMarkingSearch.Text);
        PopulateUsed();
    }

    public void SetData(MarkingSet set, string species, Sex sex, Color skinColor, Color eyeColor)
    {
        _currentMarkings = set;

        if (!IgnoreSpecies)
        {
            _currentMarkings.EnsureSpecies(species, skinColor, _markingManager, null); // should be validated server-side but it can't hurt // Amour add null
        }

        _currentSpecies = species;
        _currentSex = sex;
        CurrentSkinColor = skinColor;
        CurrentEyeColor = eyeColor;

        Populate(CMarkingSearch.Text);
        PopulateUsed();
    }

    public void SetSkinColor(Color color) => CurrentSkinColor = color;
    public void SetEyeColor(Color color) => CurrentEyeColor = color;

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entityManager.System<SpriteSystem>();

        CMarkingCategoryButton.OnItemSelected +=  OnCategoryChange;
        CMarkingsUnused.OnItemSelected += item =>
            _selectedUnusedMarking = CMarkingsUnused[item.ItemIndex];

        CMarkingAdd.OnPressed += _ =>
            MarkingAdd();

        CMarkingsUsed.OnItemSelected += OnUsedMarkingSelected;

        CMarkingRemove.OnPressed += _ =>
            MarkingRemove();

        CMarkingRankUp.OnPressed += _ => SwapMarkingUp();
        CMarkingRankDown.OnPressed += _ => SwapMarkingDown();

        CMarkingSearch.OnTextChanged += args => Populate(args.Text);
    }

    private void SetupCategoryButtons()
    {
        CMarkingCategoryButton.Clear();

        var validCategories = new List<MarkingCategories>();
        for (var i = 0; i < _markingCategories.Count; i++)
        {
            var category = _markingCategories[i];
            var markings = GetMarkings(category);
            if (_ignoreCategories.Contains(category) ||
                markings.Count == 0)
            {
                continue;
            }

            validCategories.Add(category);
            CMarkingCategoryButton.AddItem(Loc.GetString($"markings-category-{category.ToString()}"), i);
        }

        if (validCategories.Contains(_selectedMarkingCategory))
        {
            CMarkingCategoryButton.SelectId(_markingCategories.IndexOf(_selectedMarkingCategory));
        }
        else if (validCategories.Count > 0)
        {
            _selectedMarkingCategory = validCategories[0];
        }
        else
        {
            _selectedMarkingCategory = MarkingCategories.Chest;
        }
    }

    private string GetMarkingName(MarkingPrototype marking) => Loc.GetString($"marking-{marking.ID}");

    // Amour start
    private static bool MarkingSupportsGradient(MarkingPrototype marking) =>
        marking.SupportsGradient ||
        marking.MarkingCategory is MarkingCategories.Hair or MarkingCategories.FacialHair;

    private static bool UsesSharedColorControls(MarkingPrototype marking) =>
        marking.MarkingCategory == MarkingCategories.BodyGradient &&
        marking.BodyParts is { Count: > 0 };

    private static Color ToSelectorColor(Color color) => new(color.RByte, color.GByte, color.BByte);

    // Amour end
    private List<string> GetMarkingStateNames(MarkingPrototype marking)
    {
        List<string> result = new();
        foreach (var markingState in marking.Sprites)
        {
            switch (markingState)
            {
                case SpriteSpecifier.Rsi rsi:
                    result.Add(Loc.GetString($"marking-{marking.ID}-{rsi.RsiState}"));
                    break;
                case SpriteSpecifier.Texture texture:
                    result.Add(Loc.GetString($"marking-{marking.ID}-{texture.TexturePath.Filename}"));
                    break;
            }
        }

        return result;
    }

    private IReadOnlyDictionary<string, MarkingPrototype> GetMarkings(MarkingCategories category)
    {
        return IgnoreSpecies
            ? _markingManager.MarkingsByCategoryAndSex(category, _currentSex)
            : _markingManager.MarkingsByCategoryAndSpeciesAndSex(category, _currentSpecies, _currentSex);
    }

    public void Populate(string filter)
    {
        SetupCategoryButtons();

        CMarkingsUnused.Clear();
        _selectedUnusedMarking = null;

        var sortedMarkings = GetMarkings(_selectedMarkingCategory).Values.Where(m =>
            m.ID.ToLower().Contains(filter.ToLower()) ||
            GetMarkingName(m).ToLower().Contains(filter.ToLower())
        ).OrderBy(p => GetMarkingName(p));

        // Amour edit start
        var currentUserName = _playerManager.LocalSession?.Name ?? string.Empty;
        if (currentUserName.StartsWith("localhost@", StringComparison.OrdinalIgnoreCase))
            currentUserName = currentUserName.Substring("localhost@".Length);
        

        // Get Boosty tier for current player (only available on server, on client returns null)
        IBoostyTierManager? tierManager = null;
        IoCManager.Instance?.TryResolveType(out tierManager);
        var localSession = _playerManager.LocalSession;
        var playerTier = localSession != null ? tierManager?.GetPlayerTier(localSession) : null;
        var playerTierLevel = playerTier?.TierLevel ?? 0;
        var hasTierManager = tierManager != null && localSession != null;
        // Amour edit end
        

        foreach (var marking in sortedMarkings)
        {
            if (_currentMarkings.TryGetMarking(_selectedMarkingCategory, marking.ID, out _))
            {
                continue;
            }

            // Amour edit start
            if (marking.AllowedUsers != null && marking.AllowedUsers.Count > 0)
            {
                var isAllowed = marking.AllowedUsers.Any(u =>
                    string.Equals(u, currentUserName, StringComparison.OrdinalIgnoreCase));
                if (!isAllowed)
                    continue;
            }

            if (hasTierManager && marking.MinBoostyTier > 0 && playerTierLevel < marking.MinBoostyTier)
            {
                continue;
            }
            // Amour edit end

            var item = CMarkingsUnused.AddItem($"{GetMarkingName(marking)}", _sprite.Frame0(marking.Sprites[0]));
            item.Metadata = marking;
        }

        CMarkingPoints.Visible = _currentMarkings.PointsLeft(_selectedMarkingCategory) != -1;
    }

    // Populate the used marking list. Returns a list of markings that weren't
    // valid to add to the marking list.
    public void PopulateUsed()
    {
        CMarkingsUsed.Clear();
        CMarkingColors.Visible = false;
        _selectedMarking = null;

        if (!IgnoreSpecies)
        {
            _currentMarkings.EnsureSpecies(_currentSpecies, null, _markingManager, null); // Amour add null
        }

        // walk backwards through the list for visual purposes
        foreach (var marking in _currentMarkings.GetReverseEnumerator(_selectedMarkingCategory))
        {
            if (!_markingManager.TryGetMarking(marking, out var newMarking))
            {
                continue;
            }

            var text = Loc.GetString(marking.Forced ? "marking-used-forced" : "marking-used", ("marking-name", $"{GetMarkingName(newMarking)}"),
                ("marking-category", Loc.GetString($"markings-category-{newMarking.MarkingCategory}")));

            var _item = new ItemList.Item(CMarkingsUsed)
            {
                Text = text,
                Icon = _sprite.Frame0(newMarking.Sprites[0]),
                Selectable = true,
                Metadata = newMarking,
                IconModulate = marking.MarkingColors[0]
            };

            CMarkingsUsed.Add(_item);
        }

        // since all the points have been processed, update the points visually
        UpdatePoints();
    }

    private void SwapMarkingUp()
    {
        if (_selectedMarking == null)
        {
            return;
        }

        var i = CMarkingsUsed.IndexOf(_selectedMarking);
        if (ShiftMarkingRank(i, -1))
        {
            OnMarkingRankChange?.Invoke(_currentMarkings);
        }
    }

    private void SwapMarkingDown()
    {
        if (_selectedMarking == null)
        {
            return;
        }

        var i = CMarkingsUsed.IndexOf(_selectedMarking);
        if (ShiftMarkingRank(i, 1))
        {
            OnMarkingRankChange?.Invoke(_currentMarkings);
        }
    }

    private bool ShiftMarkingRank(int src, int places)
    {
        if (src + places >= CMarkingsUsed.Count || src + places < 0)
        {
            return false;
        }

        var visualDest = src + places; // what it would visually look like
        var visualTemp = CMarkingsUsed[visualDest];
        CMarkingsUsed[visualDest] = CMarkingsUsed[src];
        CMarkingsUsed[src] = visualTemp;

        switch (places)
        {
            // i.e., we're going down in rank
            case < 0:
                _currentMarkings.ShiftRankDownFromEnd(_selectedMarkingCategory, src);
                break;
            // i.e., we're going up in rank
            case > 0:
                _currentMarkings.ShiftRankUpFromEnd(_selectedMarkingCategory, src);
                break;
            // do nothing?
            // ReSharper disable once RedundantEmptySwitchSection
            default:
                break;
        }

        return true;
    }



    // repopulate in case markings are restricted,
    // and also filter out any markings that are now invalid
    // attempt to preserve any existing markings as well:
    // it would be frustrating to otherwise have all markings
    // cleared, imo
    public void SetSpecies(string species)
    {
        _currentSpecies = species;
        var markingList = _currentMarkings.GetForwardEnumerator().ToList();

        var speciesPrototype = _prototypeManager.Index<SpeciesPrototype>(species);

        _currentMarkings = new(markingList, speciesPrototype.MarkingPoints, _markingManager, _prototypeManager);
        _currentMarkings.EnsureSpecies(species, null, _markingManager);
        _currentMarkings.EnsureSexes(_currentSex, _markingManager);

        Populate(CMarkingSearch.Text);
        PopulateUsed();
    }

    public void SetSex(Sex sex)
    {
        _currentSex = sex;
        var markingList = _currentMarkings.GetForwardEnumerator().ToList();

        var speciesPrototype = _prototypeManager.Index<SpeciesPrototype>(_currentSpecies);

        _currentMarkings = new(markingList, speciesPrototype.MarkingPoints, _markingManager, _prototypeManager);
        _currentMarkings.EnsureSpecies(_currentSpecies, null, _markingManager, null); // Amour add null
        _currentMarkings.EnsureSexes(_currentSex, _markingManager);

        Populate(CMarkingSearch.Text);
        PopulateUsed();
    }

    private void UpdatePoints()
    {
        var count = _currentMarkings.PointsLeft(_selectedMarkingCategory);
        if (count > -1)
        {
            CMarkingPoints.Text = Loc.GetString("marking-points-remaining", ("points", count));
        }
    }

    private void OnCategoryChange(OptionButton.ItemSelectedEventArgs category)
    {
        CMarkingCategoryButton.SelectId(category.Id);
        _selectedMarkingCategory = _markingCategories[category.Id];
        Populate(CMarkingSearch.Text);
        PopulateUsed();
        UpdatePoints();
    }

    // TODO: This should be using ColorSelectorSliders once that's merged, so
    private void OnUsedMarkingSelected(ItemList.ItemListSelectedEventArgs item)
    {
        _selectedMarking = CMarkingsUsed[item.ItemIndex];
        var prototype = (MarkingPrototype) _selectedMarking.Metadata!;

        if (prototype.ForcedColoring)
        {
            CMarkingColors.Visible = false;

            return;
        }

        _currentMarkingColors.Clear();
        // Amour edit start
        _currentSecondaryColors.Clear();
        _currentGradientContainers.Clear();

        var listingForSelected = _currentMarkings.Markings[_selectedMarkingCategory];
        var selectedMarking = listingForSelected[listingForSelected.Count - 1 - item.ItemIndex];
        var supportsGradient = MarkingSupportsGradient(prototype);
        var usesSharedColorControls = UsesSharedColorControls(prototype);
        _currentUseGradient = supportsGradient && selectedMarking.UseGradient;
        _currentGradientPosition = Marking.ClampGradientPosition(selectedMarking.GradientPosition);
        _currentGradientBlur = Marking.ClampGradientBlur(selectedMarking.GradientBlur);
        // Amour edit end

        CMarkingColors.RemoveAllChildren();

        // Amour edit start
        if (supportsGradient)
        {
            var gradientToggleContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
            };
            var gradientCheck = new CheckBox
            {
                Text = Loc.GetString("marking-gradient-toggle"),
                Pressed = _currentUseGradient,
            };
            gradientCheck.OnToggled += args =>
            {
                _currentUseGradient = args.Pressed;
                foreach (var c in _currentGradientContainers)
                    c.Visible = _currentUseGradient;
                GradientStateChanged();
            };
            gradientToggleContainer.AddChild(gradientCheck);
            CMarkingColors.AddChild(gradientToggleContainer);
        }
        List<ColorSelectorSliders> colorSliders = new();

        if (usesSharedColorControls)
        {
            var currentColor = selectedMarking.MarkingColors.Count > 0
                ? ToSelectorColor(selectedMarking.MarkingColors[0])
                : Color.White;

            for (var i = 0; i < prototype.Sprites.Count; i++)
                _currentMarkingColors.Add(currentColor);

            // Amour edit start
            var secondarySource = selectedMarking.SecondaryMarkingColors;
            var secondaryStart = secondarySource is { Count: > 0 }
                ? ToSelectorColor(secondarySource[0])
                : currentColor;
            for (var i = 0; i < prototype.Sprites.Count; i++)
                _currentSecondaryColors.Add(secondaryStart);
            // Amour edit end

            var colorContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
            };
            var colorSelector = new ColorSelectorSliders
            {
                SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv,
                Color = currentColor,
            };
            colorContainer.AddChild(new Label { Text = Loc.GetString("marking-body-gradient-primary-color") });
            colorContainer.AddChild(colorSelector);
            CMarkingColors.AddChild(colorContainer);

            colorSelector.OnColorChanged += _ =>
            {
                for (var i = 0; i < _currentMarkingColors.Count; i++)
                    _currentMarkingColors[i] = colorSelector.Color;

                ColorChanged(0);
            };

            if (supportsGradient)
                AddGradientEditor(prototype, true, new List<string>());

            CMarkingColors.Visible = true;
            return;
        }

        var stateNames = GetMarkingStateNames(prototype);
        // Amour edit end
        for (int i = 0; i < prototype.Sprites.Count; i++)
        {
            var colorContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
            };

            CMarkingColors.AddChild(colorContainer);

            ColorSelectorSliders colorSelector = new ColorSelectorSliders();
            colorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            colorSliders.Add(colorSelector);

            colorContainer.AddChild(new Label { Text = $"{stateNames[i]} color:" });
            colorContainer.AddChild(colorSelector);

            var listing = _currentMarkings.Markings[_selectedMarkingCategory];

            var color = listing[listing.Count - 1 - item.ItemIndex].MarkingColors[i];
            // Amour start
            /*             var currentColor = new Color(
                color.RByte,
                color.GByte,
                color.BByte
            );
            */ 
            var currentColor = ToSelectorColor(color);
            // Amour end
            colorSelector.Color = currentColor;
            _currentMarkingColors.Add(currentColor);
            // Amour edit start
            var secondarySource = selectedMarking.SecondaryMarkingColors;
            var secondaryStart = secondarySource != null && i < secondarySource.Count
                ? ToSelectorColor(secondarySource[i])
                : currentColor;
            while (_currentSecondaryColors.Count <= i)
                _currentSecondaryColors.Add(secondaryStart);
            _currentSecondaryColors[i] = secondaryStart;
            // Amour edit end
            var colorIndex = _currentMarkingColors.Count - 1;

            Action<Color> colorChanged = _ =>
            {
                _currentMarkingColors[colorIndex] = colorSelector.Color;

                ColorChanged(colorIndex);
            };
            colorSelector.OnColorChanged += colorChanged;

        }

        if (supportsGradient)
            AddGradientEditor(prototype, false, stateNames);

        CMarkingColors.Visible = true;
    }

    // Amour edit start
    private void AddGradientEditor(MarkingPrototype prototype, bool usesSharedColorControls, IReadOnlyList<string> stateNames)
    {
        var editor = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            Visible = _currentUseGradient,
        };
        _currentGradientContainers.Add(editor);
        CMarkingColors.AddChild(editor);

        editor.AddChild(BuildGradientSliderRow(
            "marking-gradient-position",
            0,
            100,
            Math.Clamp((int) MathF.Round(Marking.ClampGradientPosition(_currentGradientPosition) * 100f), 0, 100),
            value =>
            {
                _currentGradientPosition = value / 100f;
                GradientStateChanged();
            }));
        editor.AddChild(BuildGradientSliderRow(
            "marking-gradient-blur",
            10,
            100,
            Math.Clamp((int) MathF.Round(Marking.ClampGradientBlur(_currentGradientBlur) * 100f), 10, 100),
            value =>
            {
                _currentGradientBlur = value / 100f;
                GradientStateChanged();
            }));
        AddGradientColorControls(editor, prototype, usesSharedColorControls, stateNames);
    }

    private BoxContainer BuildGradientSliderRow(
        string labelId,
        int minimum,
        int maximum,
        int value,
        Action<int> onValueChanged)
    {
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
        };
        row.AddChild(new Label { Text = Loc.GetString(labelId) });

        var slider = new SliderIntInput
        {
            MinValue = minimum,
            MaxValue = maximum,
            Value = Math.Clamp(value, minimum, maximum),
            HorizontalExpand = true,
        };
        slider.OnValueChanged += onValueChanged;
        row.AddChild(slider);
        return row;
    }

    private void AddGradientColorControls(
        BoxContainer editor,
        MarkingPrototype prototype,
        bool usesSharedColorControls,
        IReadOnlyList<string> stateNames)
    {
        var colorControlCount = usesSharedColorControls ? 1 : prototype.Sprites.Count;
        for (var colorIndex = 0; colorIndex < colorControlCount; colorIndex++)
        {
            var layerIndex = colorIndex;
            var selector = new ColorSelectorSliders
            {
                SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv,
                Color = ToSelectorColor(_currentSecondaryColors[layerIndex]),
            };
            var label = usesSharedColorControls
                ? Loc.GetString("marking-body-gradient-secondary-color")
                : layerIndex >= stateNames.Count
                    ? Loc.GetString("marking-gradient-color")
                    : Loc.GetString("marking-gradient-layer-color", ("layer", stateNames[layerIndex]));

            editor.AddChild(new Label { Text = label });
            editor.AddChild(selector);
            selector.OnColorChanged += _ =>
            {
                if (usesSharedColorControls)
                {
                    for (var i = 0; i < _currentSecondaryColors.Count; i++)
                        _currentSecondaryColors[i] = selector.Color;
                }
                else
                {
                    _currentSecondaryColors[layerIndex] = selector.Color;
                }

                GradientStateChanged();
            };
        }
    }
    // Amour edit end

    private void ColorChanged(int colorIndex)
    {
        if (_selectedMarking is null) return;
        var markingPrototype = (MarkingPrototype) _selectedMarking.Metadata!;
        int markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, markingPrototype.ID);

        if (markingIndex < 0) return;

        _selectedMarking.IconModulate = _currentMarkingColors[colorIndex];

        var marking = new Marking(_currentMarkings.Markings[_selectedMarkingCategory][markingIndex]);
        // Amour edit start
        if (UsesSharedColorControls(markingPrototype))
        {
            var color = _currentMarkingColors[colorIndex];
            for (var i = 0; i < marking.MarkingColors.Count; i++)
                marking.SetColor(i, color);
        }
        else
        {
            marking.SetColor(colorIndex, _currentMarkingColors[colorIndex]);
        }

        ApplyCurrentGradient(marking);
        // Amour edit end
        _currentMarkings.Replace(_selectedMarkingCategory, markingIndex, marking);

        OnMarkingColorChange?.Invoke(_currentMarkings);
    }

    // Amour edit start: persist gradient toggle and secondary colors into the marking set.
    private void GradientStateChanged()
    {
        if (_selectedMarking is null)
            return;
        var markingPrototype = (MarkingPrototype) _selectedMarking.Metadata!;
        var markingIndex = _currentMarkings.FindIndexOf(_selectedMarkingCategory, markingPrototype.ID);
        if (markingIndex < 0)
            return;

        var marking = new Marking(_currentMarkings.Markings[_selectedMarkingCategory][markingIndex]);
        ApplyCurrentGradient(marking);

        _currentMarkings.Replace(_selectedMarkingCategory, markingIndex, marking);
        OnMarkingColorChange?.Invoke(_currentMarkings);
    }

    private void ApplyCurrentGradient(Marking marking)
    {
        marking.UseGradient = _currentUseGradient;
        marking.GradientPosition = Marking.ClampGradientPosition(_currentGradientPosition);
        marking.GradientBlur = Marking.ClampGradientBlur(_currentGradientBlur);
        for (var i = 0; i < _currentSecondaryColors.Count; i++)
            marking.SetGradientColor(i, _currentSecondaryColors[i]);
    }
    // Amour edit end
    private void MarkingAdd()
    {
        if (_selectedUnusedMarking is null) return;

        if (_currentMarkings.PointsLeft(_selectedMarkingCategory) == 0 && !Forced)
        {
            return;
        }

        var marking = (MarkingPrototype) _selectedUnusedMarking.Metadata!;
        var markingObject = marking.AsMarking();

        // We need add hair markings in cloned set manually because _currentMarkings doesn't have it
        var markingSet = new MarkingSet(_currentMarkings);
        if (HairMarking != null)
        {
            markingSet.AddBack(MarkingCategories.Hair, HairMarking);
        }
        if (FacialHairMarking != null)
        {
            markingSet.AddBack(MarkingCategories.FacialHair, FacialHairMarking);
        }

        if (!_markingManager.MustMatchSkin(_currentSpecies, marking.BodyPart, out var _, _prototypeManager))
        {
            // Do default coloring
            var colors = MarkingColoring.GetMarkingLayerColors(
                marking,
                CurrentSkinColor,
                CurrentEyeColor,
                markingSet
            );
            for (var i = 0; i < colors.Count; i++)
            {
                markingObject.SetColor(i, colors[i]);
            }
        }
        else
        {
            // Color everything in skin color
            for (var i = 0; i < marking.Sprites.Count; i++)
            {
                markingObject.SetColor(i, CurrentSkinColor);
            }
        }

        markingObject.Forced = Forced;
        // Amour edit start: dedicated gradient markings should render as gradients immediately.
        if (MarkingSupportsGradient(marking))
        {
            markingObject.UseGradient = true;
            for (var i = 0; i < markingObject.MarkingColors.Count; i++)
                markingObject.SetGradientColor(i, markingObject.MarkingColors[i]);
        }
        // Amour edit end

        _currentMarkings.AddBack(_selectedMarkingCategory, markingObject);

        UpdatePoints();

        CMarkingsUnused.Remove(_selectedUnusedMarking);
        var item = new ItemList.Item(CMarkingsUsed)
        {
            Text = Loc.GetString("marking-used", ("marking-name", $"{GetMarkingName(marking)}"), ("marking-category", Loc.GetString($"markings-category-{marking.MarkingCategory}"))),
            Icon = _sprite.Frame0(marking.Sprites[0]),
            Selectable = true,
            Metadata = marking,
        };
        CMarkingsUsed.Insert(0, item);

        _selectedUnusedMarking = null;
        OnMarkingAdded?.Invoke(_currentMarkings);
    }

    private void MarkingRemove()
    {
        if (_selectedMarking is null) return;

        var marking = (MarkingPrototype) _selectedMarking.Metadata!;

        _currentMarkings.Remove(_selectedMarkingCategory, marking.ID);

        UpdatePoints();

        CMarkingsUsed.Remove(_selectedMarking);

        if (marking.MarkingCategory == _selectedMarkingCategory)
        {
            var item = CMarkingsUnused.AddItem($"{GetMarkingName(marking)}", _sprite.Frame0(marking.Sprites[0]));
            item.Metadata = marking;
        }
        _selectedMarking = null;
        CMarkingColors.Visible = false;
        OnMarkingRemoved?.Invoke(_currentMarkings);
    }
}
