// SPDX-FileCopyrightText: 2022 Flipp Syder <76629141+vulppine@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 DEATHB4DEFEAT <77995199+DEATHB4DEFEAT@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Aidenkrz <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2024 to4no_fix <156101927+chavonadelal@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Amour.Loadouts.Effects;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class SingleMarkingPicker : BoxContainer
{
    [Dependency] private readonly MarkingManager _markingManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!; // Amour

    private readonly SpriteSystem _sprite;

    /// <summary>
    ///     What happens if a marking is selected.
    ///     It will send the 'slot' (marking index)
    ///     and the selected marking's ID.
    /// </summary>
    public Action<(int slot, string id)>? OnMarkingSelect;
    /// <summary>
    ///     What happens if a slot is removed.
    ///     This will send the 'slot' (marking index).
    /// </summary>
    public Action<int>? OnSlotRemove;

    /// <summary>
    ///     What happens when a slot is added.
    /// </summary>
    public Action? OnSlotAdd;

    /// <summary>
    ///     What happens if a marking's color is changed.
    ///     Sends a 'slot' number, and the marking in question.
    /// </summary>
    public Action<(int slot, Marking marking)>? OnColorChanged;

    // RW start
    [Robust.Shared.ViewVariables.ViewVariables(Robust.Shared.ViewVariables.VVAccess.ReadWrite)]
    public bool ShowGradient { get; set; } = true;

    private bool _currentUseGradient;
    private float _currentGradientPosition;
    private float _currentGradientBlur;
    private List<Color> _currentSecondaryColors = new();
    private List<BoxContainer> _currentGradientContainers = new();
    // RW end

    // current selected slot
    private int _slot = -1;
    private int Slot
    {
        get
        {
            if (_markings == null || _markings.Count == 0)
            {
                _slot = -1;
            }
            else if (_slot == -1)
            {
                _slot = 0;
            }

            return _slot;
        }
        set
        {
            if (_markings == null || _markings.Count == 0)
            {
                _slot = -1;
                return;
            }

            _slot = value;
            _ignoreItemSelected = true;

            foreach (var item in MarkingList)
            {
                item.Selected = (string) item.Metadata! == _markings[_slot].MarkingId;
            }

            _ignoreItemSelected = false;
            PopulateColors();
        }
    }

    // amount of slots to show
    private int _totalPoints;

    private bool _ignoreItemSelected;

    private MarkingCategories _category;
    public MarkingCategories Category
    {
        get => _category;
        set
        {
            _category = value;
            CategoryName.Text = Loc.GetString($"markings-category-{_category}");

            if (!string.IsNullOrEmpty(_species))
            {
                PopulateList(Search.Text);
            }
        }
    }
    private IReadOnlyDictionary<string, MarkingPrototype>? _markingPrototypeCache;

    private string? _species;
    private List<Marking>? _markings;

    private int PointsLeft
    {
        get
        {
            if (_markings == null)
            {
                return 0;
            }

            if (_totalPoints < 0)
            {
                return -1;
            }

            return _totalPoints - _markings.Count;
        }
    }

    private int PointsUsed => _markings?.Count ?? 0;

    public SingleMarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entityManager.System<SpriteSystem>();
        MarkingList.OnItemSelected += SelectMarking;
        AddButton.OnPressed += _ =>
        {
            OnSlotAdd!();
        };

        SlotSelector.OnItemSelected += args =>
        {
            Slot = args.Button.SelectedId;
        };

        RemoveButton.OnPressed += _ =>
        {
            OnSlotRemove!(_slot);
        };

        Search.OnTextChanged += args =>
        {
            PopulateList(args.Text);
        };
    }

    public void UpdateData(List<Marking> markings, string species, int totalPoints)
    {
        _markings = markings;
        _species = species;
        _totalPoints = totalPoints;

        _markingPrototypeCache = _markingManager.MarkingsByCategoryAndSpecies(Category, _species);

        Visible = _markingPrototypeCache.Count != 0;
        if (_markingPrototypeCache.Count == 0)
        {
            return;
        }

        PopulateList(Search.Text);
        PopulateColors();
        PopulateSlotSelector();
    }

    public void PopulateList(string filter)
    {
        if (string.IsNullOrEmpty(_species))
        {
            throw new ArgumentException("Tried to populate marking list without a set species!");
        }

        _markingPrototypeCache ??= _markingManager.MarkingsByCategoryAndSpecies(Category, _species);

        MarkingSelectorContainer.Visible = _markings != null && _markings.Count != 0;
        if (_markings == null || _markings.Count == 0)
        {
            return;
        }

        MarkingList.Clear();

        var sortedMarkings = _markingPrototypeCache.Where(m =>
            m.Key.ToLower().Contains(filter.ToLower()) ||
            GetMarkingName(m.Value).ToLower().Contains(filter.ToLower())
        ).OrderBy(p => Loc.GetString($"marking-{p.Key}"));

        // Amour edit start
        var localSession = _playerManager.LocalSession;
        var currentUserName = localSession?.Name ?? string.Empty;
        if (currentUserName.StartsWith("localhost@", StringComparison.OrdinalIgnoreCase))
            currentUserName = currentUserName.Substring("localhost@".Length);

        // Get Boosty tier for current player (only available on server, on client returns null)
        IBoostyTierManager? tierManager = null;
        IoCManager.Instance?.TryResolveType(out tierManager);
        var playerTier = localSession != null ? tierManager?.GetPlayerTier(localSession) : null;
        var playerTierLevel = playerTier?.TierLevel ?? 0;
        var hasTierManager = tierManager != null && localSession != null;

        foreach (var (id, marking) in sortedMarkings)
        {
            // Check AllowedUsers
            if (marking.AllowedUsers != null && marking.AllowedUsers.Count > 0)
            {
                var isAllowed = marking.AllowedUsers.Any(u =>
                    string.Equals(u, currentUserName, StringComparison.OrdinalIgnoreCase));
                if (!isAllowed)
                    continue;
            }
            
            // Check MinBoostyTier - on client, skip tier check (let server validate)
            if (hasTierManager && marking.MinBoostyTier > 0 && playerTierLevel < marking.MinBoostyTier)
            {
                continue;
            }
        // Amour edit end

            var item = MarkingList.AddItem(Loc.GetString($"marking-{id}"), _sprite.Frame0(marking.Sprites[0]));
            item.Metadata = marking.ID;

            if (_markings[Slot].MarkingId == id)
            {
                _ignoreItemSelected = true;
                item.Selected = true;
                _ignoreItemSelected = false;
            }
        }
    }

    // RW start
    private void PopulateColors()
    {
        if (_markings == null
            || _markings.Count == 0
            || !_markingManager.TryGetMarking(_markings[Slot], out var proto))
        {
            return;
        }

        var marking = _markings[Slot];

        ColorSelectorContainer.DisposeAllChildren();
        ColorSelectorContainer.RemoveAllChildren();

        if (marking.MarkingColors.Count != proto.Sprites.Count)
        {
            marking = new Marking(marking.MarkingId, proto.Sprites.Count);
        }

        var supportsGradient = ShowGradient && MarkingSupportsGradient(proto); // RW
        _currentUseGradient = supportsGradient && marking.UseGradient;
        _currentGradientPosition = Marking.ClampGradientPosition(marking.GradientPosition);
        _currentGradientBlur = Marking.ClampGradientBlur(marking.GradientBlur);

        _currentSecondaryColors.Clear();
        _currentGradientContainers.Clear();

        if (supportsGradient)
        {
            var gradientToggleContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
            };
            var gradientCheck = new CheckBox
            {
                Text = Loc.GetString("marking-gradient-toggle"),
                Pressed = _currentUseGradient,
            };
            gradientCheck.OnToggled += args =>
            {
                _currentUseGradient = args.Pressed;
                foreach (var c in _currentGradientContainers)
                    c.Visible = _currentUseGradient;

                ApplyCurrentGradient(marking);
                _markings[Slot] = marking;
                OnColorChanged!((_slot, marking));
            };
            gradientToggleContainer.AddChild(gradientCheck);
            ColorSelectorContainer.AddChild(gradientToggleContainer);
        }

        var stateNames = GetMarkingStateNames(proto);

        for (var i = 0; i < marking.MarkingColors.Count; i++)
        {
            var colorContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true
            };
            ColorSelectorContainer.AddChild(colorContainer);

            var selector = new ColorSelectorSliders
            {
                HorizontalExpand = true
            };
            selector.Color = marking.MarkingColors[i];
            selector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;

            colorContainer.AddChild(new Label { Text = $"{stateNames[i]} color:" });
            colorContainer.AddChild(selector);

            var colorIndex = i;
            selector.OnColorChanged += color =>
            {
                marking.SetColor(colorIndex, color);
                ApplyCurrentGradient(marking);
                _markings[Slot] = marking;
                OnColorChanged!((_slot, marking));
            };

            var secondarySource = marking.SecondaryMarkingColors;
            var secondaryStart = secondarySource != null && i < secondarySource.Count
                ? ToSelectorColor(secondarySource[i])
                : ToSelectorColor(marking.MarkingColors[i]);
            while (_currentSecondaryColors.Count <= i)
                _currentSecondaryColors.Add(secondaryStart);
            _currentSecondaryColors[i] = secondaryStart;
        }

        if (supportsGradient)
        {
            AddGradientEditor(marking, proto, stateNames);
        }
    }

    private static bool MarkingSupportsGradient(MarkingPrototype marking) =>
        marking.SupportsGradient ||
        marking.MarkingCategory is MarkingCategories.Hair or MarkingCategories.FacialHair;

    private static Color ToSelectorColor(Color color) => new(color.RByte, color.GByte, color.BByte);

    private List<string> GetMarkingStateNames(MarkingPrototype marking)
    {
        var stateNames = new List<string>();
        foreach (var sprite in marking.Sprites)
        {
            switch (sprite)
            {
                case SpriteSpecifier.Rsi rsi:
                    stateNames.Add(rsi.RsiState);
                    break;
                case SpriteSpecifier.Texture texture:
                    stateNames.Add(texture.TexturePath.Filename);
                    break;
                default:
                    stateNames.Add(Loc.GetString("marking-unknown-state"));
                    break;
            }
        }
        return stateNames;
    }

    private void AddGradientEditor(Marking marking, MarkingPrototype prototype, IReadOnlyList<string> stateNames)
    {
        var editor = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            Visible = _currentUseGradient,
            HorizontalExpand = true
        };
        _currentGradientContainers.Add(editor);
        ColorSelectorContainer.AddChild(editor);

        editor.AddChild(BuildGradientSliderRow(
            "marking-gradient-position",
            0,
            100,
            Math.Clamp((int) MathF.Round(Marking.ClampGradientPosition(_currentGradientPosition) * 100f), 0, 100),
            value =>
            {
                _currentGradientPosition = value / 100f;
                ApplyCurrentGradient(marking);
                _markings![Slot] = marking;
                OnColorChanged!((_slot, marking));
            }));
        editor.AddChild(BuildGradientSliderRow(
            "marking-gradient-blur",
            10,
            100,
            Math.Clamp((int) MathF.Round(Marking.ClampGradientBlur(_currentGradientBlur) * 100f), 10, 100),
            value =>
            {
                _currentGradientBlur = value / 100f;
                ApplyCurrentGradient(marking);
                _markings![Slot] = marking;
                OnColorChanged!((_slot, marking));
            }));
        AddGradientColorControls(editor, marking, prototype, stateNames);
    }

    private BoxContainer BuildGradientSliderRow(
        string labelId,
        int minimum,
        int maximum,
        int value,
        Action<int> onValueChanged)
    {
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };
        row.AddChild(new Label { Text = Loc.GetString(labelId) });

        var slider = new SliderIntInput
        {
            MinValue = minimum,
            MaxValue = maximum,
            Value = Math.Clamp(value, minimum, maximum),
            HorizontalExpand = true,
        };
        slider.OnValueChanged += onValueChanged;
        row.AddChild(slider);
        return row;
    }

    private void AddGradientColorControls(
        BoxContainer editor,
        Marking marking,
        MarkingPrototype prototype,
        IReadOnlyList<string> stateNames)
    {
        for (var colorIndex = 0; colorIndex < prototype.Sprites.Count; colorIndex++)
        {
            var layerIndex = colorIndex;
            var selector = new ColorSelectorSliders
            {
                SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv,
                Color = ToSelectorColor(_currentSecondaryColors[layerIndex]),
                HorizontalExpand = true
            };
            var label = layerIndex >= stateNames.Count
                ? Loc.GetString("marking-gradient-color")
                : Loc.GetString("marking-gradient-layer-color", ("layer", stateNames[layerIndex]));

            editor.AddChild(new Label { Text = label });
            editor.AddChild(selector);
            selector.OnColorChanged += _ =>
            {
                _currentSecondaryColors[layerIndex] = selector.Color;
                ApplyCurrentGradient(marking);
                _markings![Slot] = marking;
                OnColorChanged!((_slot, marking));
            };
        }
    }

    private void ApplyCurrentGradient(Marking marking)
    {
        marking.UseGradient = _currentUseGradient;
        marking.GradientPosition = Marking.ClampGradientPosition(_currentGradientPosition);
        marking.GradientBlur = Marking.ClampGradientBlur(_currentGradientBlur);
        for (var i = 0; i < _currentSecondaryColors.Count; i++)
            marking.SetGradientColor(i, _currentSecondaryColors[i]);
    }
    // RW end

    private void SelectMarking(ItemList.ItemListSelectedEventArgs args)
    {
        if (_ignoreItemSelected)
        {
            return;
        }

        var id = (string) MarkingList[args.ItemIndex].Metadata!;
        if (!_markingManager.Markings.TryGetValue(id, out var proto))
        {
            throw new ArgumentException("Attempted to select non-existent marking.");
        }

        var oldMarking = _markings![Slot];
        _markings[Slot] = proto.AsMarking();

        for (var i = 0; i < _markings[Slot].MarkingColors.Count && i < oldMarking.MarkingColors.Count; i++)
        {
            _markings[Slot].SetColor(i, oldMarking.MarkingColors[i]);
        }

        // RW start
        _markings[Slot].UseGradient = oldMarking.UseGradient;
        _markings[Slot].GradientPosition = oldMarking.GradientPosition;
        _markings[Slot].GradientBlur = oldMarking.GradientBlur;
        if (oldMarking.SecondaryMarkingColors != null)
        {
            for (var i = 0; i < _markings[Slot].MarkingColors.Count && i < oldMarking.SecondaryMarkingColors.Count; i++)
            {
                _markings[Slot].SetGradientColor(i, oldMarking.SecondaryMarkingColors[i]);
            }
        }
        // RW end

        PopulateColors();

        OnMarkingSelect!((_slot, id));
    }

    // Slot logic

    private void PopulateSlotSelector()
    {
        SlotSelector.Visible = Slot >= 0;
        Search.Visible = Slot >= 0;
        AddButton.HorizontalExpand = Slot < 0;
        RemoveButton.HorizontalExpand = Slot < 0;
        AddButton.Disabled = PointsLeft == 0 && _totalPoints > -1 ;
        RemoveButton.Disabled = PointsUsed == 0;
        SlotSelector.Clear();

        if (Slot < 0)
        {
            return;
        }

        for (var i = 0; i < PointsUsed; i++)
        {
            SlotSelector.AddItem(Loc.GetString("marking-slot", ("number", $"{i + 1}")), i);

            if (i == _slot)
            {
                SlotSelector.SelectId(i);
            }
        }
    }

    private string GetMarkingName(MarkingPrototype marking)
    {
        return Loc.GetString($"marking-{marking.ID}");
    }
}