using System.Linq;
using Content.Shared._RW.ResponseForce;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RW.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
public sealed partial class ResponseForceWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly List<ResponseForceTeamPrototype> _teams;

    public ResponseForceWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _teams = _prototype.EnumeratePrototypes<ResponseForceTeamPrototype>()
            .Where(team => !team.Abstract)
            .OrderBy(team => Loc.GetString(team.ResponseForceName))
            .ToList();

        foreach (var team in _teams)
        {
            TeamSelection.AddItem(Loc.GetString(team.ResponseForceName));
        }

        TeamSelection.OnItemSelected += args =>
        {
            TeamSelection.SelectId(args.Id);
            UpdateCommand();
        };

        if (_teams.Count == 0)
        {
            TeamSelection.Disabled = true;
            CallButton.Disabled = true;
            return;
        }

        TeamSelection.SelectId(0);
        UpdateCommand();
    }

    private void UpdateCommand()
    {
        var selected = TeamSelection.SelectedId;

        if (selected < 0 || selected >= _teams.Count)
            return;

        var team = _teams[selected];
        CallButton.Command = $"callresponseforce {team.ID}";
    }
}
