using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RW.ReadyManifest;

[GenerateTypedNameReferences]
public sealed partial class ReadyManifestUi : DefaultWindow
{
    private readonly IPrototypeManager _prototypeManager;
    private readonly Dictionary<string, BoxContainer> _jobCategories;
    private readonly SpriteSystem _spriteSystem;

    public ReadyManifestUi()
    {
        RobustXamlLoader.Load(this);
        _jobCategories = new Dictionary<string, BoxContainer>();
        _prototypeManager = IoCManager.Resolve<IPrototypeManager>();
        _spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
    }

    public void RebuildUI(Dictionary<ProtoId<JobPrototype>, List<string>> jobCharacters)
    {
        ReadyManifestListing.DisposeAllChildren();

        _jobCategories.Clear();
        var departments = new List<DepartmentPrototype>();

        foreach (var department in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
        {
            if (department.EditorHidden)
                continue;

            departments.Add(department);
        }

        departments.Sort(DepartmentUIComparer.Instance);

        foreach (var department in departments)
        {
            var departmentName = Loc.GetString($"department-{department.ID}");
            BoxContainer? category = null;

            var jobs = department.Roles
                .Select(jobId => _prototypeManager.Index(jobId))
                .OrderBy(job => job.Name)
                .ToArray();

            Array.Sort(jobs, JobUIComparer.Instance);

            foreach (var job in jobs)
            {
                if (!jobCharacters.TryGetValue(job.ID, out var characters) || characters.Count == 0)
                    continue;

                if (category == null)
                {
                    category = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Vertical,
                        HorizontalExpand = true,
                        Name = department.ID,
                        ToolTip = Loc.GetString("humanoid-profile-editor-jobs-amount-in-department-tooltip",
                            ("departmentName", departmentName)),
                    };

                    var stripe = new StripeBack();
                    var label = new Label
                    {
                        StyleClasses = { "LabelBig" },
                        Text = Loc.GetString($"department-{department.ID}"),
                        Align = Label.AlignMode.Center,
                    };
                    stripe.AddChild(label);
                    category.AddChild(stripe);

                    _jobCategories[department.ID] = category;
                    ReadyManifestListing.AddChild(category);
                }

                var gridContainer = new GridContainer()
                {
                    HorizontalExpand = true,
                    Columns = 2,
                };

                var jobContainer = new BoxContainer()
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                };

                var title = new RichTextLabel()
                {
                    HorizontalExpand = true,
                };
                title.SetMessage(job.LocalizedName + ":");

                var icon = new TextureRect
                {
                    TextureScale = new Vector2(2, 2),
                    VerticalAlignment = VAlignment.Center,
                    Margin = new Thickness(0, 0, 4, 0),
                };

                var readyCount = new RichTextLabel()
                {
                    HorizontalExpand = true,
                };
                readyCount.SetMessage(characters.Count.ToString());

                var jobIcon = _prototypeManager.Index(job.Icon);
                icon.Texture = _spriteSystem.Frame0(jobIcon.Icon);
                jobContainer.AddChild(icon);
                jobContainer.AddChild(title);
                gridContainer.AddChild(jobContainer);
                gridContainer.AddChild(readyCount);
                category.AddChild(gridContainer);

                var namesContainer = new BoxContainer()
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    Margin = new Thickness(20, 0, 0, 5),
                };

                foreach (var characterName in characters.OrderBy(n => n))
                {
                    var nameLabel = new Label()
                    {
                        Text = "• " + characterName,
                        FontColorOverride = Color.LightGray,
                    };
                    namesContainer.AddChild(nameLabel);
                }

                category.AddChild(namesContainer);
            }
        }
    }
}
