// SPDX-FileCopyrightText: 2022 E F R <602406+Efruit@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr.@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <jmaster9999@gmail.com>
// SPDX-FileCopyrightText: 2022 Moony <moonheart08@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 wrexbe <wrexbe@protonmail.com>
// SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Kara <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._RW.UserInterface.Systems.Chat.RichText;
using Content.Client.UserInterface.Systems.Chat;
using Content.Shared.Administration;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.Bwoink
{
    [GenerateTypedNameReferences]
    public sealed partial class BwoinkPanel : BoxContainer
    {
        // RW start
        [Dependency] private readonly IPrototypeManager _emojiPrototypeManager = default!;
        // RW end

        private readonly Action<string> _messageSender;

        public int Unread { get; private set; } = 0;
        public DateTime LastMessage { get; private set; } = DateTime.MinValue;
        private List<string> PeopleTyping { get; set; } = new();
        public event Action<string>? InputTextChanged;

        public BwoinkPanel(Action<string> messageSender)
        {
            RobustXamlLoader.Load(this);
            // RW start
            IoCManager.InjectDependencies(this);
            // RW end

            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);
            msg.AddText(Loc.GetString("bwoink-system-messages-being-relayed-to-discord"));
            msg.Pop();
            RelayedToDiscordLabel.SetMessage(msg);

            _messageSender = messageSender;

            OnVisibilityChanged += c =>
            {
                if (c.Visible)
                {
                    Unread = 0;
                    // RW start
                    var controller = IoCManager.Resolve<IUserInterfaceManager>().GetUIController<ChatUIController>();
                    EmojiBtn.SetAvailable(controller.IsEmojiAllowed(ChatChannel.Admin));
                    // RW end
                }
            };
            SenderLineEdit.OnTextEntered += Input_OnTextEntered;
            SenderLineEdit.OnTextChanged += Input_OnTextChanged;
            
            // RW start
            var chatController = IoCManager.Resolve<IUserInterfaceManager>().GetUIController<ChatUIController>();
            EmojiBtn.SetAvailable(chatController.IsEmojiAllowed(ChatChannel.Admin));

            EmojiBtn.OnEmojiPicked += emoji =>
            {
                SenderLineEdit.InsertAtCursor(emoji);
                SenderLineEdit.GrabKeyboardFocus();
            };
            // RW end
            
            UpdateTypingIndicator();
        }

        private void Input_OnTextEntered(LineEdit.LineEditEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(args.Text))
                return;

            _messageSender.Invoke(args.Text);
            SenderLineEdit.Clear();
        }

        private void Input_OnTextChanged(LineEdit.LineEditEventArgs args)
        {
            // RW start
            if (RewriteEmojiAliases())
                return;
            // RW end

            InputTextChanged?.Invoke(args.Text);
        }

        // RW start
        private bool _suppressEmojiAliasRewrite;

        private bool RewriteEmojiAliases()
        {
            if (_suppressEmojiAliasRewrite)
                return false;

            var controller = IoCManager.Resolve<IUserInterfaceManager>().GetUIController<ChatUIController>();
            if (!controller.IsEmojiAllowed(ChatChannel.Admin))
                return false;

            var input = SenderLineEdit;
            var rewritten = ChatEmoji.ReplaceAliases(
                input.Text,
                input.CursorPosition,
                _emojiPrototypeManager,
                out var newCursorPosition);

            if (string.Equals(rewritten, input.Text, StringComparison.Ordinal))
                return false;

            _suppressEmojiAliasRewrite = true;
            try
            {
                input.SetText(rewritten);
                input.CursorPosition = newCursorPosition;
                input.SelectionStart = newCursorPosition;
            }
            finally
            {
                _suppressEmojiAliasRewrite = false;
            }

            return true;
        }
        // RW end

        public void ReceiveLine(SharedBwoinkSystem.BwoinkTextMessage message)
        {
            if (!Visible)
                Unread++;

            // RW start
            var controller = IoCManager.Resolve<IUserInterfaceManager>().GetUIController<ChatUIController>();
            var emojiAllowed = controller.IsEmojiAllowed(ChatChannel.Admin);
            var processedText = ChatEmojiRichText.ReplaceEmojiMarkup(message.Text, emojiAllowed, _emojiPrototypeManager);
            // RW end

            var formatted = new FormattedMessage(1);
            formatted.AddMarkupOrThrow($"[color=gray]{message.SentAt.ToShortTimeString()}[/color] {processedText}"); // RW
            TextOutput.AddMessage(formatted);
            LastMessage = message.SentAt;
        }

        private void UpdateTypingIndicator()
        {
            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);

            var text = PeopleTyping.Count == 0
                ? string.Empty
                : Loc.GetString("bwoink-system-typing-indicator",
                    ("players", string.Join(", ", PeopleTyping)),
                    ("count", PeopleTyping.Count));

            msg.AddText(text);
            msg.Pop();

            TypingIndicator.SetMessage(msg);
        }

        public void UpdatePlayerTyping(string name, bool typing)
        {
            if (typing)
            {
                if (PeopleTyping.Contains(name))
                    return;

                PeopleTyping.Add(name);
                Timer.Spawn(TimeSpan.FromSeconds(10), () =>
                {
                    if (Disposed)
                        return;

                    PeopleTyping.Remove(name);
                    UpdateTypingIndicator();
                });
            }
            else
            {
                PeopleTyping.Remove(name);
            }

            UpdateTypingIndicator();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            InputTextChanged = null;
        }
    }
}