// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo.BUI;
using Content.Shared.Materials;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class CargoPalletMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!; // Orion

    public Action? SellRequested;
    public Action? AppraiseRequested;

    public CargoPalletMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // Orion

        // Orion-Start
        TabContainer.SetTabTitle(0, Loc.GetString("cargo-pallet-tab-sales"));
        TabContainer.SetTabTitle(1, Loc.GetString("cargo-pallet-tab-analytics"));
        // Orion-End

        SellButton.OnPressed += OnSellPressed;
        AppraiseButton.OnPressed += OnAppraisePressed;
    }

    // Orion-Start
    public void UpdateState(CargoPalletConsoleInterfaceState state)
    {
        SetEnabled(state.Enabled);
        SetAppraisal(state.Appraisal);
        SetCount(state.Count);
        BuildMarketAnalytics(state);
    }

    private void BuildMarketAnalytics(CargoPalletConsoleInterfaceState state)
    {
        IncreasedContainer.RemoveAllChildren();
        DecreasedContainer.RemoveAllChildren();
        RecentContainer.RemoveAllChildren();

        var increased = state.ActiveChanges.Where(c => c.Multiplier > 1f).OrderByDescending(c => c.Multiplier).ToList();
        var decreased = state.ActiveChanges.Where(c => c.Multiplier < 1f).OrderBy(c => c.Multiplier).ToList();

        foreach (var change in increased)
        {
            IncreasedContainer.AddChild(BuildChangeRow(change));
        }

        foreach (var change in decreased)
        {
            DecreasedContainer.AddChild(BuildChangeRow(change));
        }

        foreach (var change in state.RecentChanges.OrderByDescending(c => c.Sequence).Take(12))
        {
            RecentContainer.AddChild(BuildChangeRow(change, true));
        }

        NoChangesLabel.Visible = state.ActiveChanges.Count == 0 && state.RecentChanges.Count == 0;
    }

    private Control BuildChangeRow(CargoPalletMarketChangeData change, bool withSequence = false)
    {
        var materialName = change.MaterialProto;
        if (_prototype.TryIndex<MaterialPrototype>(change.MaterialProto, out var material) && !string.IsNullOrWhiteSpace(material.Name))
            materialName = Loc.GetString(material.Name);

        var percent = (change.Multiplier - 1f) * 100f;
        var sequence = withSequence && change.Sequence > 0
            ? Loc.GetString("cargo-pallet-market-sequence", ("sequence", change.Sequence))
            : string.Empty;
        var roundedPercent = MathF.Round(MathF.Abs(percent), 1);
        var roundedMultiplier = MathF.Round(change.Multiplier, 1);
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
        };

        if (withSequence)
            row.AddChild(MakeCell(sequence, 0.7f));

        row.AddChild(MakeCell(materialName, 1.3f));
        row.AddChild(MakeCell($"{(change.Multiplier >= 1f ? "+" : "-")}{roundedPercent:0.#}%", 0.7f));
        row.AddChild(MakeCell($"x{roundedMultiplier:0.#}", 0.6f));

        return row;
    }

    private static Control MakeCell(string text, float ratio)
    {
        var label = new Label
        {
            Text = text,
            ClipText = true,
            Margin = new Thickness(2, 1),
            HorizontalExpand = true,
        };

        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            SizeFlagsStretchRatio = ratio,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1A1B20"),
            },
            MinHeight = 22,
        };
        panel.AddChild(label);
        return panel;
    }
    // Orion-End

    private void SetAppraisal(int amount) // Orion-Edit: Was public
    {
        AppraisalLabel.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", amount.ToString()));
    }

    private void SetCount(int count) // Orion-Edit: Was public
    {
        CountLabel.Text = count.ToString();
    }

    private void SetEnabled(bool enabled) // Orion-Edit: Was public
    {
        AppraiseButton.Disabled = !enabled;
        SellButton.Disabled = !enabled;
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }

    private void OnAppraisePressed(BaseButton.ButtonEventArgs obj)
    {
        AppraiseRequested?.Invoke();
    }
}
