using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo.Components;
using Content.Shared.Cargo.Prototypes;
using Content.Shared.CCVar;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class FundingAllocationMenu : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly EntityQuery<StationBankAccountComponent> _bankQuery;

    public event Action<Dictionary<ProtoId<CargoAccountPrototype>, int>, double, double>? OnSavePressed;

    private EntityUid? _station;
    private bool _allowPrimaryAccountAllocation;
    private bool _allowPrimaryCutAdjustment;
    private bool _lockboxCutEnabled;

    private double _primaryCut;
    private double _lockboxCut;

//    private readonly HashSet<Control> _addedControls = new(); // Orion-Edit
    // Orion-Start
    private readonly HashSet<Control> _distributionControls = new();
    private readonly HashSet<Control> _economyAccountControls = new();

    private readonly HashSet<Control> _transactionControls = new();

    private EntityUid? _entriesStation;
    private List<ProtoId<CargoAccountPrototype>> _entriesAccounts = new();
    // Orion-End
    private readonly List<SpinBox> _spinBoxes = new();
    private readonly Dictionary<ProtoId<CargoAccountPrototype>, RichTextLabel> _balanceLabels = new();

    public FundingAllocationMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _bankQuery = _entityManager.GetEntityQuery<StationBankAccountComponent>();

        // Orion-Start
        TabContainer.SetTabTitle(0, Loc.GetString("cargo-funding-alloc-console-tab-distribution"));
        TabContainer.SetTabTitle(1, Loc.GetString("cargo-funding-alloc-console-tab-economy"));
        // Orion-End

        PrimaryCut.ValueChanged += args =>
        {
            _primaryCut = args.Value / 100.0; // Orion-Edit
            UpdateButtonDisabled();
        };

        LockboxCut.ValueChanged += args =>
        {
            _lockboxCut = 1.0 - args.Value / 100.0; // Orion-Edit
            UpdateButtonDisabled();
        };

        SaveButton.OnPressed += _ =>
        {
            if (!_entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank))
                return;

            // Orion-Edit-Start
            var accounts = EditableAccounts(bank)
                .OrderBy(p => p.Key)
                .Select(p => p.Key)
                .ToList();

            var editedPercents = new Dictionary<ProtoId<CargoAccountPrototype>, int>();
            for (var i = 0; i < accounts.Count; i++)
            {
                editedPercents.Add(accounts[i], _spinBoxes[i].Value);
            }

            OnSavePressed?.Invoke(editedPercents, _primaryCut, _lockboxCut);
            // Orion-Edit-End
            SaveButton.Disabled = true;
        };

        // Orion-Edit-Start
        _cfg.OnValueChanged(CCVars.AllowPrimaryAccountAllocation,
            enabled =>
            {
                _allowPrimaryAccountAllocation = enabled;
                RefreshUi();
            },
            true);
        _cfg.OnValueChanged(CCVars.AllowPrimaryCutAdjustment,
            enabled =>
        {
            _allowPrimaryCutAdjustment = enabled;
            RefreshUi();
        },
            true);
        _cfg.OnValueChanged(CCVars.LockboxCutEnabled,
            enabled =>
        {
            _lockboxCutEnabled = enabled;
            RefreshUi();
        },
            true);
        // Orion-Edit-End

        BuildEntries();
    }

    private IEnumerable<KeyValuePair<ProtoId<CargoAccountPrototype>, int>> EditableAccounts(StationBankAccountComponent bank)
    {
        foreach (var kvp in bank.Accounts)
        {
            if (_allowPrimaryAccountAllocation || kvp.Key != bank.PrimaryAccount)
                yield return kvp;
        }
    }

    // Orion-Start
    private void BuildEconomy(FundingAllocationConsoleBuiState state)
    {
        EconomyAccountsContainer.RemoveAllChildren();
        TransactionsContainer.RemoveAllChildren();
        _economyAccountControls.Clear();
        _transactionControls.Clear();

        BuildEconomyHeaders();

        var accountsByEntity = state.EconomyAccounts.ToDictionary(a => a.Account);

        NoAccountsLabel.Visible = state.EconomyAccounts.Count == 0;
        foreach (var account in state.EconomyAccounts.OrderBy(a => a.AccountId))
        {
            var roleText = string.IsNullOrWhiteSpace(account.JobId)
                ? Loc.GetString("cargo-funding-alloc-console-economy-role-none")
                : LocalizeJob(account.JobId);

            if (string.IsNullOrWhiteSpace(roleText))
                roleText = Loc.GetString("cargo-funding-alloc-console-economy-role-none");

            var row = CreateRowContainer();
            row.AddChild(CreateCell(MaskAccountCode(account.AccountId), 130f));
            row.AddChild(CreateCell(account.AccountName, 1f));
            row.AddChild(CreateCell(roleText, 1f));
            row.AddChild(CreateCell(Loc.GetString("cargo-funding-alloc-console-money", ("amount", account.Balance)), 130f));

            EconomyAccountsContainer.AddChild(row);
            _economyAccountControls.Add(row);
        }

        NoTransactionsLabel.Visible = state.Transactions.Count == 0;
        foreach (var transaction in state.Transactions.OrderByDescending(t => t.Time).ThenByDescending(t => t.Index))
        {
            accountsByEntity.TryGetValue(transaction.Account, out var mainAccount);
            accountsByEntity.TryGetValue(transaction.Counterparty ?? default, out var counterpartyAccount);

            var incoming = transaction.Delta > 0;
            var operationType = incoming
                ? Loc.GetString("cargo-funding-alloc-console-economy-operation-income")
                : Loc.GetString("cargo-funding-alloc-console-economy-operation-expense");

            var unknownText = Loc.GetString("cargo-funding-alloc-console-economy-unknown");
            var from = incoming
                ? counterpartyAccount?.AccountName ?? unknownText
                : mainAccount?.AccountName ?? unknownText;
            var to = incoming
                ? mainAccount?.AccountName ?? unknownText
                : counterpartyAccount?.AccountName ?? unknownText;

            switch (incoming)
            {
                case true when transaction.Reason == "payroll":
                    from = LocalizeDepartmentCode(mainAccount?.DepartmentId);
                    break;
                case false when transaction.Reason == "vending-purchase":
                    to = LocalizeDepartmentCode(ParseVendingPurchaseData(transaction.ReasonData).DepartmentId);
                    break;
                case false when transaction.Reason == "cargo-private-purchase":
                    to = LocalizeDepartmentCode("Cargo");
                    break;
                case true when transaction.Reason == "cargo-private-purchase-refund":
                    from = LocalizeDepartmentCode("Cargo");
                    break;
            }

            var row = CreateRowContainer();
            row.AddChild(CreateCell(operationType, 110f));
            row.AddChild(CreateCell(Loc.GetString("cargo-funding-alloc-console-money", ("amount", transaction.Delta)), 110f));
            row.AddChild(CreateCell(from, 1f));
            row.AddChild(CreateCell(to, 1f));
            row.AddChild(CreateCell(LocalizeReason(transaction.Reason, transaction.ReasonData), 2f));
            row.AddChild(CreateCell(FormatDuration(transaction.Time), 90f));

            TransactionsContainer.AddChild(row);
            _transactionControls.Add(row);
        }
    }


    private void BuildEconomyHeaders()
    {
        var accountHeader = CreateHeaderRow(new[]
        {
            Loc.GetString("cargo-funding-alloc-console-economy-number"),
            Loc.GetString("cargo-funding-alloc-console-economy-user"),
            Loc.GetString("cargo-funding-alloc-console-economy-role"),
            Loc.GetString("cargo-funding-alloc-console-economy-balance"),
        },
        new[] { 130f, 1f, 1f, 130f });

        EconomyAccountsContainer.AddChild(accountHeader);
        _economyAccountControls.Add(accountHeader);

        var transactionHeader = CreateHeaderRow(new[]
        {
            Loc.GetString("cargo-funding-alloc-console-economy-operation"),
            Loc.GetString("cargo-funding-alloc-console-economy-amount"),
            Loc.GetString("cargo-funding-alloc-console-economy-from"),
            Loc.GetString("cargo-funding-alloc-console-economy-to"),
            Loc.GetString("cargo-funding-alloc-console-economy-reason"),
            Loc.GetString("cargo-funding-alloc-console-economy-time"),
        },
        new[] { 110f, 110f, 1f, 1f, 2f, 90f });

        TransactionsContainer.AddChild(transactionHeader);
        _transactionControls.Add(transactionHeader);
    }

    private static BoxContainer CreateHeaderRow(string[] titles, float[] widths)
    {
        var row = CreateRowContainer();
        for (var i = 0; i < titles.Length; i++)
        {
            row.AddChild(CreateCell(titles[i], widths[i], true));
        }

        return row;
    }

    private static BoxContainer CreateRowContainer()
    {
        return new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
        };
    }

    private static Control CreateCell(string text, float width, bool header = false)
    {
        var label = new Label
        {
            Text = text,
            ClipText = true,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(2, 1),
        };

        if (header)
            label.FontColorOverride = Color.FromHex("#B9B9C2");

        var container = new PanelContainer
        {
            MinWidth = (int) MathF.Max(width > 10 ? width : 80, 80),
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = header ? Color.FromHex("#1F2025") : Color.FromHex("#17181D"),
            },
            SizeFlagsStretchRatio = width > 10 ? 0.01f : width,
        };

        container.AddChild(label);
        return container;
    }

    private static string MaskAccountCode(string accountId)
    {
        return accountId.Length <= 4
            ? "####"
            : $"######{accountId[^4..]}";
    }

    private string LocalizeReason(string reason, string? reasonData)
    {
        var vendingData = ParseVendingPurchaseData(reasonData);
        var cargoOrderData = ParseCargoPrivatePurchaseData(reasonData);
        return reason switch
        {
            "card-deposit" => Loc.GetString("cargo-funding-alloc-console-reason-card-deposit"),
            "card-withdrawal" => Loc.GetString("cargo-funding-alloc-console-reason-card-withdrawal"),
            "payroll" => Loc.GetString("cargo-funding-alloc-console-reason-payroll", ("job", LocalizeJob(reasonData))),
            "starting-payroll" => Loc.GetString("cargo-funding-alloc-console-reason-starting-payroll"),
            "vending-purchase" => Loc.GetString("cargo-funding-alloc-console-reason-vending-purchase", ("item", LocalizeVendingItem(vendingData.ItemId))),
            "cargo-private-purchase" => Loc.GetString("cargo-funding-alloc-console-reason-cargo-private-purchase", ("order", cargoOrderData.OrderId ?? Loc.GetString("cargo-funding-alloc-console-economy-unknown")), ("product", LocalizeCargoProduct(cargoOrderData.ProductId))),
            "cargo-private-purchase-refund" => Loc.GetString("cargo-funding-alloc-console-reason-cargo-private-purchase-refund", ("order", cargoOrderData.OrderId ?? Loc.GetString("cargo-funding-alloc-console-economy-unknown")), ("product", LocalizeCargoProduct(cargoOrderData.ProductId))),
            _ => Loc.GetString("cargo-funding-alloc-console-reason-generic", ("reason", reason)),
        };
    }

    private static (string? ItemId, string? DepartmentId) ParseVendingPurchaseData(string? reasonData)
    {
        if (string.IsNullOrWhiteSpace(reasonData))
            return (null, null);

        var split = reasonData.Split('|', 2, StringSplitOptions.TrimEntries);
        return split.Length == 2 ? (split[0], split[1]) : (reasonData, null);
    }

    private static (string? OrderId, string? ProductId) ParseCargoPrivatePurchaseData(string? reasonData)
    {
        if (string.IsNullOrWhiteSpace(reasonData))
            return (null, null);

        string? orderId = null;
        string? productId = null;
        var entries = reasonData.Split('|', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        foreach (var entry in entries)
        {
            var pair = entry.Split(':', 2, StringSplitOptions.TrimEntries);
            if (pair.Length != 2)
                continue;

            switch (pair[0])
            {
                case "order":
                    orderId = pair[1];
                    break;
                case "product":
                    productId = pair[1];
                    break;
            }
        }

        return (orderId, productId);
    }

    private string LocalizeVendingItem(string? itemId)
    {
        if (string.IsNullOrWhiteSpace(itemId))
            return Loc.GetString("cargo-funding-alloc-console-economy-unknown");

        if (_prototypeManager.TryIndex<EntityPrototype>(itemId, out var proto))
            return Loc.GetString(proto.Name);

        return Loc.GetString("cargo-funding-alloc-console-economy-unknown");
    }

    private string LocalizeCargoProduct(string? productId)
    {
        if (string.IsNullOrWhiteSpace(productId))
            return Loc.GetString("cargo-funding-alloc-console-economy-unknown");

        if (_prototypeManager.TryIndex<EntityPrototype>(productId, out var proto))
            return Loc.GetString(proto.Name);

        return Loc.GetString("cargo-funding-alloc-console-economy-unknown");
    }

    private string LocalizeJob(string? jobId)
    {
        if (string.IsNullOrWhiteSpace(jobId))
            return Loc.GetString("cargo-funding-alloc-console-economy-unknown");

        if (_prototypeManager.TryIndex<JobPrototype>(jobId, out var job))
            return Loc.GetString(job.Name);

        return Loc.GetString("cargo-funding-alloc-console-economy-unknown");
    }

    private string LocalizeDepartmentCode(string? departmentId)
    {
        if (string.IsNullOrWhiteSpace(departmentId))
            return Loc.GetString("cargo-funding-alloc-console-economy-unknown");

        if (_prototypeManager.TryIndex<CargoAccountPrototype>(departmentId, out var proto))
            return Loc.GetString(proto.Code);

        return Loc.GetString("cargo-funding-alloc-console-economy-unknown");
    }

    private static string FormatDuration(TimeSpan time)
    {
        return $"{(int) time.TotalHours:D2}:{time.Minutes:D2}:{time.Seconds:D2}";
    }

    private void RefreshUi()
    {
        if (_station == null)
            return;

        BuildEntries();
        UpdateButtonDisabled();
    }
    // Orion-End

    // Orion-Edit-Start
    private void BuildEntries()
    {
        if (!_entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank))
            return;

        HelpLabel.Text = _allowPrimaryCutAdjustment
            ? Loc.GetString("cargo-funding-alloc-console-label-help-adjustible")
            : Loc.GetString("cargo-funding-alloc-console-label-help-non-adjustible",
                ("percent", (int) (bank.PrimaryCut * 100)));

        foreach (var control in _distributionControls)
        {
            control.Orphan();
        }

        _distributionControls.Clear();
        _spinBoxes.Clear();
        _balanceLabels.Clear();

        _primaryCut = bank.PrimaryCut;
        _lockboxCut = bank.LockboxCut;

        LockboxCut.OverrideValue(100 - (int) (_lockboxCut * 100));
        PrimaryCut.OverrideValue((int) (_primaryCut * 100));

        LockboxCut.IsValid = val => val is >= 0 and <= 100;
        PrimaryCut.IsValid = val => val is >= 0 and <= 100;

        LockboxCut.Visible = _lockboxCutEnabled;
        LockboxCutLabel.Visible = _lockboxCutEnabled;
        PrimaryCut.Visible = _allowPrimaryCutAdjustment;
        PrimaryCutLabel.Visible = _allowPrimaryCutAdjustment;

        var accounts = EditableAccounts(bank).OrderBy(p => p.Key);
        var revenueDistribution = bank.RevenueDistribution;
        foreach (var (account, balance) in accounts)
        {
            var proto = _prototypeManager.Index(account);

            var accountName = new RichTextLabel
            {
                Modulate = proto.Color,
                Margin = new Thickness(0, 0, 10, 0),
            };

            accountName.SetMarkup($"[bold]{Loc.GetString(proto.Name)}[/bold]");

            var code = new RichTextLabel
            {
                Text = $"[font=\"Monospace\"]{Loc.GetString(proto.Code)}[/font]",
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(5, 0),
            };

            var balanceLabel = new RichTextLabel
            {
                Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", balance)),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(5, 0),
            };

            var cutSpinBox = new SpinBox
            {
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
                Value = (int) ((revenueDistribution.TryGetValue(account, out var pct) ? pct : 0) * 100),
                IsValid = val => val is >= 0 and <= 100,
            };

            cutSpinBox.ValueChanged += _ => UpdateButtonDisabled();

            EntriesContainer.AddChild(accountName);
            EntriesContainer.AddChild(code);
            EntriesContainer.AddChild(balanceLabel);
            EntriesContainer.AddChild(cutSpinBox);

            _spinBoxes.Add(cutSpinBox);
            _balanceLabels.Add(account, balanceLabel);
            _distributionControls.UnionWith([accountName, code, balanceLabel, cutSpinBox]);
        }
    }
    // Orion-Edit-End

    // Orion-Edit-Start
    private void UpdateButtonDisabled()
    {
        if (!_entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank))
            return;

        var sum = _spinBoxes.Sum(s => s.Value);
        var incorrectSum = sum != 100;

        var differs = false;
        var revenueDistribution = bank.RevenueDistribution;
        var accounts = EditableAccounts(bank)
            .OrderBy(p => p.Key)
            .Select(p => p.Key)
            .ToList();

        for (var i = 0; i < accounts.Count; i++)
        {
            var currentPercent = _spinBoxes[i].Value;
            var expectedPercent = (int) Math.Round((revenueDistribution.TryGetValue(accounts[i], out var pct) ? pct : 0) * 100);

            if (currentPercent == expectedPercent)
                continue;

            differs = true;
            break;
        }

        differs = differs || _primaryCut != bank.PrimaryCut || _lockboxCut != bank.LockboxCut;

        SaveButton.Disabled = !differs || incorrectSum;

        var diff = sum - 100;
        SaveAlertLabel.Visible = incorrectSum;
        SaveAlertLabel.SetMarkup(Loc.GetString(
            "cargo-funding-alloc-console-label-save-fail",
            ("pos", Math.Sign(diff)),
            ("val", Math.Abs(diff))));
    }
    // Orion-Edit-End

    public void Update(FundingAllocationConsoleBuiState state)
    {
        _station = _entityManager.GetEntity(state.Station);

        // Orion-Edit-Start
        if (ShouldRebuildEntries())
            BuildEntries();
        // Orion-Edit-End

        BuildEconomy(state); // Orion
        UpdateButtonDisabled();
    }

    // Orion-Start
    private bool ShouldRebuildEntries()
    {
        if (_station == null || !_entityManager.TryGetComponent<StationBankAccountComponent>(_station, out var bank))
            return false;

        var accounts = EditableAccounts(bank)
            .OrderBy(p => p.Key)
            .Select(p => p.Key)
            .ToList();

        if (_entriesStation != _station || _entriesAccounts.Count != accounts.Count)
        {
            _entriesStation = _station;
            _entriesAccounts = accounts;
            return true;
        }

        for (var i = 0; i < accounts.Count; i++)
        {
            if (_entriesAccounts[i].Equals(accounts[i]))
                continue;

            _entriesAccounts = accounts;
            return true;
        }

        return false;
    }
    // Orion-End

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_bankQuery.TryComp(_station, out var bank))
            return;

        foreach (var (account, label) in _balanceLabels)
        {
            label.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", bank.Accounts[account]));
        }
    }
}
