# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  requirements:
    - !type:AnyOfRequirement # Amour edit - Discord OR playtime
      requirements:
        - !type:DiscordLinkRequirement
        - !type:OverallPlaytimeRequirement
          time: 3600 # 1 hr
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hop
  guides: # goobstation
#  - Bartender # Orion-Edit: Removed because dont have this SOP
  - Drinks
  goobcoins: 10 #Goob content
  # Orion-Start
  salary: 55
  payrollDepartmentAccount: Service
  # Orion-End
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics

- type: startingGear
  id: BartenderGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: BartenderPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: BartenderChameleonOutfit
  job: Bartender
  equipment:
    head: ClothingHeadHatTophat
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedBlack
    outerClothing: ClothingOuterArmorBasicSlim
    gloves: ClothingHandsGlovesColorBlack
