# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:AnyOfRequirement # RW edit - Discord OR playtime
      requirements:
        - !type:DiscordLinkRequirement
        - !type:OverallPlaytimeRequirement
          time: 3600 # 1 hr
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-hop
  guides: # goobstation
  # RW-Edit-Start
  # - SpaceLaw # Disabled until guide is created
  # RW-Edit-End
#  - LegalSOP # RW-Edit: Removed because dont have this SOP
  goobcoins: 10 #Goob content
  # RW-Start
  salary: 50
  payrollDepartmentAccount: Service
  # RW-End
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance
  special: # Goobstation - Everyone knows lawyers are soulless.
  - !type:AddComponentSpecial
    components:
    - type: Condemned
      soulOwnedNotDevil: true

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw

- type: chameleonOutfit
  id: LawyerChameleonOutfit
  job: Lawyer
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
