# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Visitor
  name: job-name-visitor
  description: job-description-visitor
  playTimeTracker: JobVisitor
  canBeAntag: false
  icon: JobIconVisitor
  setPreference: false
  overrideConsoleVisibility: true
  # Orion-Start
  salary: 25
  payrollFromStationBudget: false
  # Orion-End
  access:
  - Maintenance
  extendedAccess:
  - External
