using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._RW.UserInterface.Windows;

//
// License-Identifier: AGPL-3.0-or-later
//

[GenerateTypedNameReferences]
public sealed partial class PremiumPassWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public PremiumPassWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        PurchaseButton.OnPressed += OnButtonPress;
    }

    private void OnButtonPress(BaseButton.ButtonEventArgs args)
    {
        PurchaseButton.Visible = false;
        PurchasedButton.Visible = true;
    }
}
