using Content.Client.UserInterface.Controls;
using Content.Shared._RW.ChameleonStamp;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.OptionButton;

namespace Content.Client._RW.ChameleonStamp;

[GenerateTypedNameReferences]
public sealed partial class ChameleonStampWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private EntityUid? _owner;
    private EntityUid? _preview;
    private ChameleonStampSystem _chameleonStampSystem;

    public ChameleonStampWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _chameleonStampSystem = _entMan.System<ChameleonStampSystem>();

        StampColorOptionButton.OnItemSelected += ColorOptionButton_OnItemSelected;
        StampSpriteOptionButton.OnItemSelected += StampSpriteOptionButton_OnItemSelected;
        StampStateOptionButton.OnItemSelected += StateOptionButton_OnItemSelected;
    }

    public void UpdateVisuals()
    {
        if (!_entMan.TryGetComponent<ChameleonStampComponent>(_owner, out var chameleonStamp))
            return;

        if (!_chameleonStampSystem.ValidatePreset(chameleonStamp.SelectedStampColorPrototype, out var stampColorPrototype, out var stampColorComponent))
            return;

        if (!_chameleonStampSystem.ValidatePreset(chameleonStamp.SelectedStampStatePrototype, out var stampStatePrototype, out var stampStateComponent))
            return;

        if (!_chameleonStampSystem.ValidatePreset(chameleonStamp.SelectedStampSpritePrototype, out var stampSpritePrototype, out var stampSpriteComponent))
            return;

        var i = 0;

        StampColorOptionButton.Clear();
        StampSpriteOptionButton.Clear();
        StampStateOptionButton.Clear();

        foreach (var proto in _chameleonStampSystem.GetAllPresets())
        {
            this.StampColorOptionButton.AddItem(_proto.Index(proto).Name, i);
            StampColorOptionButton.SetItemMetadata(i, proto.Id);
            if (proto == chameleonStamp.SelectedStampColorPrototype)
                StampColorOptionButton.Select(i);

            this.StampSpriteOptionButton.AddItem(_proto.Index(proto).Name, i);
            StampSpriteOptionButton.SetItemMetadata(i, proto.Id);
            if (proto == chameleonStamp.SelectedStampSpritePrototype)
                StampSpriteOptionButton.Select(i);

            this.StampStateOptionButton.AddItem(_proto.Index(proto).Name, i);
            StampStateOptionButton.SetItemMetadata(i, proto.Id);
            if (proto == chameleonStamp.SelectedStampStatePrototype)
                StampStateOptionButton.Select(i);

            i++;
        }

        if (_preview != null)
        {
            _entMan.DeleteEntity(_preview.Value);
            _preview = null;
        }

        _preview = _entMan.Spawn(chameleonStamp.SelectedStampSpritePrototype, MapCoordinates.Nullspace);

        this.StampMetaDataName.PlaceHolder = Loc.GetString(stampSpritePrototype.Name);
        this.StampMetaDataDescription.PlaceHolder = Loc.GetString(stampSpritePrototype.Description);
        this.StampedNameLineEdit.PlaceHolder = Loc.GetString(stampSpriteComponent.StampedName);

        this.StampMetaDataName.Text = string.IsNullOrEmpty(chameleonStamp.CustomName) ? string.Empty : Loc.GetString(chameleonStamp.CustomName);
        this.StampMetaDataDescription.Text = string.IsNullOrEmpty(chameleonStamp.CustomDescription) ? string.Empty : Loc.GetString(chameleonStamp.CustomDescription);
        this.StampedNameLineEdit.Text = string.IsNullOrEmpty(chameleonStamp.StampedName) ? string.Empty : Loc.GetString(chameleonStamp.StampedName);

        StampColorSelector.Color = chameleonStamp.CustomStampColor.HasValue ? chameleonStamp.CustomStampColor.Value : stampColorComponent.StampedColor;

        SpritePreview.SetEntity(_preview);
    }

    private void StateOptionButton_OnItemSelected(ItemSelectedEventArgs obj)
    {
        var meta = StampStateOptionButton.GetItemMetadata(obj.Id);
        if (meta is null)
            return;

        if (!_proto.Index<EntityPrototype>((string) meta).TryGetComponent<SpriteComponent>(out _))
            return;

        StampStateOptionButton.Select(obj.Id);
    }

    private void StampSpriteOptionButton_OnItemSelected(ItemSelectedEventArgs obj)
    {
        var meta = StampSpriteOptionButton.GetItemMetadata(obj.Id);
        if (meta is null)
            return;

        if (!_proto.Index<EntityPrototype>((string) meta).TryGetComponent<SpriteComponent>(out var presetSprite))
            return;

        if (!_entMan.TryGetComponent<SpriteComponent>(_preview, out var previewSprite))
            return;

        previewSprite.CopyFrom(presetSprite);
        StampSpriteOptionButton.Select(obj.Id);

        if (!_chameleonStampSystem.ValidatePreset((string) meta, out var stampSpritePrototype, out var stampSpriteComponent))
            return;

        this.StampMetaDataName.PlaceHolder = Loc.GetString(stampSpritePrototype.Name);
        this.StampMetaDataDescription.PlaceHolder = Loc.GetString(stampSpritePrototype.Description);
        this.StampedNameLineEdit.PlaceHolder = Loc.GetString(stampSpriteComponent.StampedName);
    }

    private void ColorOptionButton_OnItemSelected(ItemSelectedEventArgs obj)
    {
        var meta = StampColorOptionButton.GetItemMetadata(obj.Id);
        if (meta is null)
            return;

        if (!_proto.Index<EntityPrototype>((string) meta).TryGetComponent<StampComponent>(out var stamp))
            return;

        StampColorSelector.Color = stamp.StampedColor;
        StampColorOptionButton.Select(obj.Id);
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
        UpdateVisuals();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && _preview != null)
        {
            _entMan.DeleteEntity(_preview.Value);
            _preview = null;
        }

        base.Dispose(disposing);
    }
}
