// SPDX-License-Identifier: MIT

using Content.Client.Administration.Managers;
using Content.Client._RW.GameFlowControl;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class RoundTab : Control
    {
        [Dependency] private readonly IClientAdminManager _adminManager = default!;
        [Dependency] private readonly IPlayerManager _playerManager = default!;

        public RoundTab()
        {
            RobustXamlLoader.Load(this);
        }

        private GameFlowControlSystem? _gameFlowControl;

        protected override void EnteredTree()
        {
            base.EnteredTree();
            IoCManager.InjectDependencies(this);
            _gameFlowControl = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<GameFlowControlSystem>();

            if (_gameFlowControl != null)
                _gameFlowControl.OnStateChanged += UpdateButtonState;
            _adminManager.AdminStatusUpdated += UpdateButtonState;
            UpdateButtonState();
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            if (_gameFlowControl != null)
                _gameFlowControl.OnStateChanged -= UpdateButtonState;
            _adminManager.AdminStatusUpdated -= UpdateButtonState;
        }

        private void UpdateButtonState()
        {
            if (_gameFlowControl == null)
                return;

            // Only show/enable if user has Spawn flag
            var hasSpawn = _adminManager.HasFlag(AdminFlags.Spawn);
            GameFlowControlBtn.Visible = hasSpawn;

            if (hasSpawn)
            {
                var occupier = _gameFlowControl.Occupier;
                var selfCkey = _playerManager.LocalSession?.Name;

                // Disable if occupied by someone else (not null and not us)
                GameFlowControlBtn.Disabled = occupier != null && occupier != selfCkey;
            }
        }
    }
}