using Content.Client.UserInterface.Controls;
using Content.Shared._RW.Brainrot;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RW.Brainrot;

[GenerateTypedNameReferences]
public sealed partial class BrainrotPanelWindow : FancyWindow
{
    private readonly BrainrotPanelEui _eui;

    public BrainrotPanelWindow(BrainrotPanelEui eui)
    {
        _eui = eui;
        RobustXamlLoader.Load(this);

        AddBtn.OnPressed += _ => SendAddMsg();
        AddInput.OnTextEntered += _ => SendAddMsg();
    }

    private void SendAddMsg()
    {
        var text = AddInput.Text.Trim();
        if (string.IsNullOrEmpty(text))
            return;

        _eui.SendMessage(new AddBrainrotTriggerMsg(text));
        AddInput.Text = string.Empty;
    }

    public void UpdateState(BrainrotPanelEuiState state)
    {
        TriggersContainer.DisposeAllChildren();

        foreach (var trigger in state.CustomTriggers)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                HorizontalExpand = true
            };

            var label = new Label
            {
                Text = trigger,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center
            };

            var deleteBtn = new Button
            {
                Text = Loc.GetString("brainrot-panel-delete"),
                VerticalAlignment = VAlignment.Center
            };

            deleteBtn.OnPressed += _ =>
            {
                _eui.SendMessage(new RemoveBrainrotTriggerMsg(trigger));
            };

            row.AddChild(label);
            row.AddChild(deleteBtn);

            TriggersContainer.AddChild(row);
        }
    }
}
