using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RW.Discord;

[GenerateTypedNameReferences]
public sealed partial class DiscordLinkWindow : FancyWindow
{
    public DiscordLinkWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
