using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RW.ChatTrigger.UI;

[GenerateTypedNameReferences]
public sealed partial class GrammarnaziBotWindow : FancyWindow
{
    public Action? OnSendAnyway;

    public GrammarnaziBotWindow()
    {
        RobustXamlLoader.Load(this);
        MessageLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("chat-trigger-grammarnazi-message")));
        CancelButton.OnPressed += _ => Close();
        SendAnywayButton.OnPressed += _ =>
        {
            OnSendAnyway?.Invoke();
            Close();
        };
    }

    public void SetDescription(string description)
    {
        DescriptionLabel.SetMessage(FormattedMessage.FromMarkupPermissive(description));
    }
}
