# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  requirements:
    - !type:AnyOfRequirement # Amour edit - Discord OR playtime
      requirements:
        - !type:DiscordLinkRequirement
        - !type:OverallPlaytimeRequirement
          time: 7200 # 2 hrs
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  guides: [ Science ] # goobstation
  goobcoins: 20 #Goob content
  # Orion-Start
  salary: 80
  payrollDepartmentAccount: Science
  # Orion-End
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistGear
  equipment:
    ears: ClothingHeadsetScience
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ScientistChameleonOutfit
  job: Scientist
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRnd
    gloves: ClothingHandsGlovesLatex
