// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Diagnostics.CodeAnalysis;
using Content.Client.Guidebook;
using Content.Client.Guidebook.Richtext;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideFoodIngredientGroupEmbed : BoxContainer, IDocumentTag
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;

    public GuideFoodIngredientGroupEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Stop;
    }

    public GuideFoodIngredientGroupEmbed(bool populate) : this()
    {
        if (populate)
            Populate();
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        Populate();
        control = this;
        return true;
    }

    private void Populate()
    {
        GroupContainer.RemoveAllChildren();

        var foodGuide = _entitySystemManager.GetEntitySystem<FoodGuideDataSystem>();
        var addedRecipes = new HashSet<string>();

        foreach (var entity in foodGuide.GetGuideIngredients())
        {
            foreach (var recipe in foodGuide.GetMicrowaveRecipes(entity.ID))
            {
                if (addedRecipes.Add(recipe.ID))
                    GroupContainer.AddChild(new GuideMicrowaveEmbed(recipe));
            }

            if (foodGuide.GetMicrowaveRecipes(entity.ID).Count > 0)
                continue;

            var hasNonMicrowaveSource = false;
            foreach (var source in foodGuide.GetNonPlantSources(entity.ID))
            {
                if (source.Kind is FoodEntitySourceKind.MixingReaction
                    or FoodEntitySourceKind.SliceFrom
                    or FoodEntitySourceKind.RollFrom)
                {
                    hasNonMicrowaveSource = true;
                    break;
                }
            }

            if (hasNonMicrowaveSource)
                GroupContainer.AddChild(new GuideFoodIngredientEmbed(entity));
        }
    }
}
