// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Diagnostics;
using System.Linq;
using Content.Client.Chemistry.EntitySystems;
using Content.Client.Guidebook;
using System.Numerics;
using Content.Client.Guidebook.RichText;
using Content.Client.UserInterface.ControlExtensions;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls.FancyTree;
using Content.Client.UserInterface.Systems.Info;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reaction;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;

namespace Content.Client.Guidebook.Controls;

[GenerateTypedNameReferences]
public sealed partial class GuidebookWindow : FancyWindow, ILinkClickHandler, IGuidebookCrossReferenceNavigator, IAnchorClickHandler
{
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;
    [Dependency] private readonly IResourceManager _resourceManager = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> _entries = new();
    private readonly GuidebookCrossReferenceIndex _crossReferences = new();
    private GuideEntry? _currentGuideEntry;
    private List<ProtoId<GuideEntryPrototype>>? _treeRootEntries;
    private ProtoId<GuideEntryPrototype>? _treeForceRoot;
    private bool _suppressSelectionReload;
// RW end

    private readonly ISawmill _sawmill;

    public ProtoId<GuideEntryPrototype> LastEntry;

    public GuidebookWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = Logger.GetSawmill("Guidebook");

        Tree.OnSelectedItemChanged += OnSelectionChanged;

        SearchBar.OnTextChanged += _ =>
        {
            HandleFilter();
        };

        // RW start
        HomeButton.OnPressed += _ =>
        {
            if (_currentGuideEntry != null)
                ShowGuide(_currentGuideEntry, resetState: true); // RW
        };
        // RW end
    }

    public void HandleClick(string link)
    {
        if (!_entries.TryGetValue(link, out var entry))
            return;

        if (Tree.TryGetIndexFromMetadata(entry, out var index))
        {
            Tree.ExpandParentEntries(index.Value);
            Tree.SetSelectedIndex(index);
        }
        else
            ShowGuide(entry);
    }

    // RW start
    public void NavigateToCrossReferenceTarget(IGuidebookCrossReference reference)
    {
        if (reference.TargetPrototype is not { } target)
            return;

        _crossReferences.TryRevealAndScroll(target, Scroll, UserInterfaceManager);
    }
    // RW end

    public void HandleAnchor(IPrototypeLinkControl prototypeLinkControl)
    {
        var prototype = prototypeLinkControl.LinkedPrototype;
        if (prototype == null)
            return;

        var (linkableControls, _) = GetLinkableControlsAndLinks(EntryContainer);
        foreach (var linkableControl in linkableControls)
        {
            if (linkableControl.RepresentedPrototype != prototype)
                continue;

            if (linkableControl is not Control control)
                return;

            // Check if the target item is currently filtered out
            if (!control.Visible)
                control.Visible = true;

            UserInterfaceManager.DeferAction(() =>
            {
                if (control.GetControlScrollPosition() is not {} position)
                    return;

                Scroll.HScrollTarget = position.X;
                Scroll.VScrollTarget = position.Y;
            });

            break;
        }
    }

    private void OnSelectionChanged(TreeItem? item)
    {
        if (item != null && item.Metadata is GuideEntry entry)
        {
            // RW start
            if (_suppressSelectionReload
                || (_currentGuideEntry?.Id == entry.Id && EntryContainer.ChildCount > 0))
            {
                ReturnContainer.Visible = entry.RuleEntry;
                return;
            }

            SaveCurrentPageState();
            _currentGuideEntry = entry;
            ShowGuide(entry);
            // RW end

            ReturnContainer.Visible = entry.RuleEntry; // RW
        }
        else
            ClearSelectedGuide();
    }

    public void ClearSelectedGuide()
    {
        Placeholder.Visible = true;
        EntryContainer.Visible = false;
        SearchContainer.Visible = false;
        EntryContainer.RemoveAllChildren();
        // RW start
        _crossReferences.Clear();
        _currentGuideEntry = null;
        // RW end
    }

    // RW start
    public void SaveCurrentPageState()
    {
        if (_currentGuideEntry == null)
            return;

        GuidebookPageStateStorage.States[_currentGuideEntry.Id] = new GuidebookPageState(
            Scroll.GetScrollValue(),
            SearchBar.Text ?? string.Empty,
            CollectExpandedCollapsibles(EntryContainer),
            CollectRevealedEntryAnchors(EntryContainer, SearchBar.Text ?? string.Empty)); // RW
    }

    private void ShowGuide(GuideEntry entry, bool resetState = false)
    {
        var pageState = resetState
            ? GuidebookPageStateStorage.Empty
            : GuidebookPageStateStorage.States.GetValueOrDefault(entry.Id, GuidebookPageStateStorage.Empty);
        Placeholder.Visible = false;
        EntryContainer.Visible = true;
        EntryContainer.RemoveAllChildren();

        // RW start
        var textPath = entry.Text;
        if (entry is GuideEntryPrototype proto && proto.LocalizedText != null)
        {
            var culture = _loc.DefaultCulture?.Name;
            if (culture != null && proto.LocalizedText.TryGetValue(culture, out var path))
            {
                textPath = path;
            }
        }
        // RW end

        using var file = _resourceManager.ContentFileReadText(textPath);

        SearchContainer.Visible = entry.FilterEnabled;

        if (!_parsingMan.TryAddMarkup(EntryContainer, file.ReadToEnd()))
        {
            // The guidebook will automatically display the in-guidebook error if it fails

            _sawmill.Error($"Failed to parse contents of guide document {entry.Id}.");
        }

        LastEntry = entry.Id;

        // RW
        _crossReferences.BuildFromPage(EntryContainer);
        ApplyPageState(pageState);

        var (linkableControls, linkControls) = GetLinkableControlsAndLinks(EntryContainer);

        HashSet<IPrototype> availablePrototypeLinks = new();
        foreach (var linkableControl in linkableControls)
        {
            var prototype = linkableControl.RepresentedPrototype;
            if (prototype != null)
                availablePrototypeLinks.Add(prototype);
        }

        foreach (var linkControl in linkControls)
        {
            var prototype = linkControl.LinkedPrototype;
            if (prototype != null && availablePrototypeLinks.Contains(prototype))
                linkControl.EnablePrototypeLink();
        }
    }

    // RW
    private void ApplyPageState(GuidebookPageState state)
    {
        SearchBar.SetText(state.Search, invokeEvent: false);

        if (!string.IsNullOrEmpty(state.Search))
            HandleFilter();

        UserInterfaceManager.DeferAction(() =>
        {
            ApplyRevealedEntryAnchors(EntryContainer, state.RevealedEntryAnchors);
            ApplyCollapsibleStates(EntryContainer, state.ExpandedCollapsibles);
            Scroll.SetScrollValue(state.Scroll);
        });
    }

    private static HashSet<string> CollectRevealedEntryAnchors(Control root, string search)
    {
        var revealed = new HashSet<string>();

        if (string.IsNullOrWhiteSpace(search))
            return revealed;

        var query = search.Trim();
        foreach (var anchor in EnumerateEntryAnchors(root))
        {
            if (anchor is not Control { Visible: true } control)
                continue;

            if (control is not ISearchableControl searchable)
                continue;

            if (searchable.CheckMatchesSearch(query))
                continue;

            if (anchor.AnchorPrototype is { } proto)
                revealed.Add(proto.ID);
        }

        return revealed;
    }

    private static void ApplyRevealedEntryAnchors(Control root, HashSet<string> revealed)
    {
        if (revealed.Count == 0)
            return;

        foreach (var anchor in EnumerateEntryAnchors(root))
        {
            if (anchor.AnchorPrototype is not { } proto)
                continue;

            if (!revealed.Contains(proto.ID))
                continue;

            if (anchor is Control control)
                control.Visible = true;
        }
    }

    private static IEnumerable<IGuidebookEntryAnchor> EnumerateEntryAnchors(Control root)
    {
        foreach (var child in root.Children)
        {
            if (child is IGuidebookEntryAnchor anchor)
                yield return anchor;

            foreach (var nested in EnumerateEntryAnchors(child))
                yield return nested;
        }
    }

    private static HashSet<string> CollectExpandedCollapsibles(Control root)
    {
        var expanded = new HashSet<string>();

        foreach (var collapsible in EnumerateCollapsibles(root))
        {
            if (!IsCollapsibleExpanded(collapsible))
                continue;

            if (GetCollapsibleKey(collapsible) is { } key)
                expanded.Add(key);
        }

        return expanded;
    }

    private static void ApplyCollapsibleStates(Control root, HashSet<string> expanded)
    {
        foreach (var collapsible in EnumerateCollapsibles(root))
        {
            if (GetCollapsibleKey(collapsible) is not { } key)
                continue;

            collapsible.BodyVisible = expanded.Contains(key);
        }
    }

    private static IEnumerable<Collapsible> EnumerateCollapsibles(Control root)
    {
        foreach (var child in root.Children)
        {
            if (child is Collapsible collapsible)
                yield return collapsible;

            foreach (var nested in EnumerateCollapsibles(child))
                yield return nested;
        }
    }

    private static bool IsCollapsibleExpanded(Collapsible collapsible)
    {
        if (collapsible.BodyVisible)
            return true;

        var heading = GetCollapsibleHeading(collapsible);
        return heading is { Pressed: true };
    }

    private static CollapsibleHeading? GetCollapsibleHeading(Collapsible collapsible)
    {
        if (collapsible.Heading is CollapsibleHeading heading)
            return heading;

        foreach (var child in collapsible.Children)
        {
            if (child is CollapsibleHeading collapsibleHeading)
                return collapsibleHeading;
        }

        return null;
    }

    private static string? GetCollapsibleKey(Collapsible collapsible)
    {
        var sectionId = GetCollapsibleSectionId(collapsible);
        if (string.IsNullOrEmpty(sectionId))
            return null;

        if (collapsible.TryGetParentHandler<IGuidebookEntryAnchor>(out var anchor)
            && anchor.AnchorPrototype is { } anchorPrototype)
        {
            return $"{anchorPrototype.ID}|{sectionId}";
        }

        return sectionId;
    }

    private static string? GetCollapsibleSectionId(Collapsible collapsible)
    {
        for (var control = collapsible.Parent; control is not null; control = control.Parent)
        {
            if (!string.IsNullOrEmpty(control.Name))
                return control.Name;
        }

        var heading = GetCollapsibleHeading(collapsible);
        return heading?.Title ?? heading?.Label.Text;
    }
    // RW end

    public void UpdateGuides(
        Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> entries,
        List<ProtoId<GuideEntryPrototype>>? rootEntries = null,
        ProtoId<GuideEntryPrototype>? forceRoot = null,
        ProtoId<GuideEntryPrototype>? selected = null)
    {
        // RW start
        var keepPage = CanKeepCurrentPage(entries, rootEntries, forceRoot, selected);

        if (!keepPage)
        {
            _entries = entries;
            RepopulateTree(rootEntries, forceRoot);
            _treeRootEntries = rootEntries;
            _treeForceRoot = forceRoot;
            ClearSelectedGuide();
        }
        else
        {
            _entries = entries;
        }
        // RW end

        Split.State = SplitContainer.SplitState.Auto;
        if (entries.Count == 1)
        {
            TreeBox.Visible = false;
            Split.ResizeMode = SplitContainer.SplitResizeMode.NotResizable;
            selected = entries.Keys.First();
        }
        else
        {
            TreeBox.Visible = true;
            Split.ResizeMode = SplitContainer.SplitResizeMode.RespectChildrenMinSize;
        }

        // RW start
        if (keepPage)
        {
            EnsurePageVisible();
            SyncTreeSelection(selected);
            return;
        }
        // RW end

        if (selected != null)
        {
            var item = Tree.Items.FirstOrDefault(x => x.Metadata is GuideEntry entry && entry.Id == selected);
            Tree.SetSelectedIndex(item?.Index);
        }
    }

    // RW start
    private bool CanKeepCurrentPage(
        Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> entries,
        List<ProtoId<GuideEntryPrototype>>? rootEntries,
        ProtoId<GuideEntryPrototype>? forceRoot,
        ProtoId<GuideEntryPrototype>? selected)
    {
        if (selected == null || _currentGuideEntry?.Id != selected)
            return false;

        if (EntryContainer.ChildCount == 0)
            return false;

        if (_entries.Count != entries.Count)
            return false;

        foreach (var key in entries.Keys)
        {
            if (!_entries.ContainsKey(key))
                return false;
        }

        if (_treeForceRoot != forceRoot)
            return false;

        return TreeRootsMatch(_treeRootEntries, rootEntries);
    }

    private static bool TreeRootsMatch(
        List<ProtoId<GuideEntryPrototype>>? a,
        List<ProtoId<GuideEntryPrototype>>? b)
    {
        if (a == null && b == null)
            return true;

        if (a == null || b == null)
            return false;

        return a.SequenceEqual(b);
    }

    private void EnsurePageVisible()
    {
        Placeholder.Visible = false;
        EntryContainer.Visible = true;

        if (_currentGuideEntry != null)
            SearchContainer.Visible = _currentGuideEntry.FilterEnabled;
    }

    private void SyncTreeSelection(ProtoId<GuideEntryPrototype>? selected)
    {
        if (selected == null || _currentGuideEntry?.Id != selected)
            return;

        ReturnContainer.Visible = _currentGuideEntry.RuleEntry;

        if (Tree.SelectedItem?.Metadata is GuideEntry entry && entry.Id == selected)
            return;

        var item = Tree.Items.FirstOrDefault(x => x.Metadata is GuideEntry e && e.Id == selected);
        _suppressSelectionReload = true;
        Tree.SetSelectedIndex(item?.Index);
        _suppressSelectionReload = false;
    }
    // RW end

    private IEnumerable<GuideEntry> GetSortedEntries(List<ProtoId<GuideEntryPrototype>>? rootEntries)
    {
        if (rootEntries == null)
        {
            HashSet<ProtoId<GuideEntryPrototype>> entries = new(_entries.Keys);
            foreach (var entry in _entries.Values)
            {
                if (entry.Children.Count > 0)
                {
                    var sortedChildren = entry.Children
                        .Select(childId => _entries[childId])
                        .OrderBy(childEntry => childEntry.Priority)
                        .ThenBy(childEntry => Loc.GetString(childEntry.Name))
                        .Select(childEntry => new ProtoId<GuideEntryPrototype>(childEntry.Id))
                        .ToList();

                    entry.Children = sortedChildren;
                }

                entries.ExceptWith(entry.Children);
            }

            rootEntries = entries.ToList();
        }

        return rootEntries
            .Select(rootEntryId => _entries[rootEntryId])
            .OrderBy(rootEntry => rootEntry.Priority)
            .ThenBy(rootEntry => Loc.GetString(rootEntry.Name));
    }

    private void RepopulateTree(List<ProtoId<GuideEntryPrototype>>? roots = null,
        ProtoId<GuideEntryPrototype>? forcedRoot = null)
    {
        Tree.Clear();

        HashSet<ProtoId<GuideEntryPrototype>> addedEntries = new();

        var parent = forcedRoot == null ? null : AddEntry(forcedRoot.Value, null, addedEntries);
        foreach (var entry in GetSortedEntries(roots))
        {
            AddEntry(entry.Id, parent, addedEntries);
        }

        Tree.SetAllExpanded(true);
    }

    private TreeItem? AddEntry(ProtoId<GuideEntryPrototype> id,
        TreeItem? parent,
        HashSet<ProtoId<GuideEntryPrototype>> addedEntries)
    {
        if (!_entries.TryGetValue(id, out var entry))
            return null;

        if (!addedEntries.Add(id))
        {
            // TODO GUIDEBOOK Maybe allow duplicate entries?
            // E.g., for adding medicine under both chemicals & the chemist job
            Logger.Error($"Adding duplicate guide entry: {id}");
            return null;
        }

        var rulesProto = UserInterfaceManager.GetUIController<InfoUIController>().GetCoreRuleEntry();
        if (entry.RuleEntry && entry.Id != rulesProto.Id)
            return null;

        var item = Tree.AddItem(parent);
        item.Metadata = entry;
        var name = Loc.GetString(entry.Name);
        item.Label.Text = name;

        foreach (var child in entry.Children)
        {
            AddEntry(child, item, addedEntries);
        }

        return item;
    }

    private void HandleFilter()
    {
        if (Tree.SelectedItem != null && Tree.SelectedItem.Metadata is GuideEntry entry && entry.FilterEnabled)
        {
            var query = SearchBar.Text?.Trim() ?? string.Empty; // RW
            var foundElements = EntryContainer.GetSearchableControls();

            foreach (var element in foundElements)
            {
                element.SetHiddenState(true, query);
            }
        }
    }

    private static (List<IPrototypeRepresentationControl>, List<IPrototypeLinkControl>) GetLinkableControlsAndLinks(Control parent)
    {
        List<IPrototypeRepresentationControl> linkableList = new();
        List<IPrototypeLinkControl> linkList = new();

        // Goobstation edit: iteration over recursion.
        // we have too many chems.
        var stack = new Stack<Control>();
        stack.Push(parent);

        while (stack.Count > 0)
        {
            var current = stack.Pop();

            foreach (var child in current.Children)
            {
                if (child is IPrototypeLinkControl linkChild)
                    linkList.Add(linkChild);

                if (child is IPrototypeRepresentationControl linkableChild)
                    linkableList.Add(linkableChild);

                if (child.ChildCount > 0)
                    stack.Push(child);
            }
        }
        // Goob edit end.

        return (linkableList, linkList);
    }
}
