using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RW.CorticalBorer;

[GenerateTypedNameReferences]
public sealed partial class CorticalBorerForceSpeakWindow : FancyWindow
{
    public event Action<string>? OnForceSpeakButtonPressed;

    public CorticalBorerForceSpeakWindow()
    {
        RobustXamlLoader.Load(this);

        ForceHostSpeechButton.OnPressed += _ =>
        {
            var text = ForceHostSpeechInput.Text.Trim();
            if (string.IsNullOrEmpty(text))
                return;

            OnForceSpeakButtonPressed?.Invoke(text);
            ForceHostSpeechInput.Text = string.Empty;
        };
    }
}
