// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Inventory.Widgets;

[GenerateTypedNameReferences]
public sealed partial class InventoryGui : UIWidget
{
    public InventoryGui()
    {
        RobustXamlLoader.Load(this);

        var inventoryUIController = UserInterfaceManager.GetUIController<InventoryUIController>();
        inventoryUIController.RegisterInventoryBarContainer(InventoryHotbar);
        // Orion-Start
        inventoryUIController.RegisterExtraHotbarContainer(ExtraHotbar);
        // Orion-End

        LayoutContainer.SetGrowVertical(this, LayoutContainer.GrowDirection.Begin);
    }

    // Orion-Start
    public void ToggleExtraHotbarVisibility()
    {
        ExtraHotbar.Visible = !ExtraHotbar.Visible;
    }
    // Orion-End
}
