using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Amour.Ghost.Roles.UI;

[GenerateTypedNameReferences]
public sealed partial class SsdAmnesiacGhostRoleReturnWindow : FancyWindow
{
    public SsdAmnesiacGhostRoleReturnWindow()
    {
        RobustXamlLoader.Load(this);

        MessageLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("amour-ssd-amnesiac-return-text")));
        ConfirmButton.OnPressed += _ => Close();
    }
}
