using System.Linq;
using System.Numerics;
using Content.Client._RW.UserInterface.Systems.Chat.RichText;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

using Robust.Shared.IoC;

namespace Content.Client._RW.UserInterface.Systems.Chat.Controls;

[GenerateTypedNameReferences]
public sealed partial class EmojiPickerPopup : Popup
{
    public const float PopupWidth = 560f;
    public const float PopupHeight = 440f;

    private const float EmojiButtonSize = 36f;

    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly Dictionary<ChatEmojiCategory, Button> _categoryButtons = new();
    private ButtonGroup _categoryGroup = new(isNoneSetAllowed: false);
    private ChatEmojiCategory _selectedCategory = ChatEmojiCategory.Smileys;

    public event Action<string>? OnEmojiPicked;

    public EmojiPickerPopup()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        OnPopupOpen += OnPopupOpened;
        RebuildCategoryButtons();
        _selectedCategory = GetDefaultCategory();
        SelectCategory(_selectedCategory);
    }

    private void SelectCategory(ChatEmojiCategory category)
    {
        if (!_categoryButtons.ContainsKey(category))
            category = GetDefaultCategory();

        _selectedCategory = category;
        HeaderLabel.Text = GetCategoryName(category);
        PreviewLabel.SetMessage(
            FormattedMessage.FromUnformatted(Loc.GetString("hud-chatbox-emoji-preview-empty")));

        if (_categoryButtons.TryGetValue(category, out var selectedButton))
            selectedButton.Pressed = true;

        EmojiGrid.DisposeAllChildren();

        foreach (var emoji in ChatEmoji.EnumerateCategory(category, _prototypeManager))
        {
            var emojiButton = new Button
            {
                MinSize = new Vector2(EmojiButtonSize),
                ToolTip = $":{emoji.Alias}:"
            };

            emojiButton.AddChild(ChatEmojiRichText.CreatePickerTextureRect(_resourceCache, emoji));
            emojiButton.OnPressed += _ => OnEmojiPicked?.Invoke(emoji.InsertText);
            emojiButton.OnMouseEntered += _ => PreviewLabel.SetMessage(
                ChatEmojiRichText.BuildPreviewMessage(emoji));
            EmojiGrid.AddChild(emojiButton);
        }
    }

    private void OnPopupOpened()
    {
        RebuildCategoryButtons();

        if (!_categoryButtons.ContainsKey(_selectedCategory))
            _selectedCategory = GetDefaultCategory();

        SelectCategory(_selectedCategory);
    }

    private void RebuildCategoryButtons()
    {
        _categoryButtons.Clear();
        _categoryGroup = new ButtonGroup(isNoneSetAllowed: false);
        CategoryBox.DisposeAllChildren();

        foreach (var category in ChatEmoji.GetCategoryOrder(_prototypeManager))
        {
            var button = new Button
            {
                Group = _categoryGroup,
                MinSize = new Vector2(32f),
                ToolTip = GetCategoryName(category)
            };

            button.AddChild(
                ChatEmojiRichText.CreateCategoryTextureRect(_resourceCache, GetCategoryIcon(category)));
            button.OnPressed += _ => SelectCategory(category);
            _categoryButtons[category] = button;
            CategoryBox.AddChild(button);
        }
    }

    private ChatEmojiDefinition GetCategoryIcon(ChatEmojiCategory category)
    {
        if (category != ChatEmojiCategory.Custom)
            return ChatEmoji.GetCategoryIcon(category);

        return ChatEmoji.EnumerateCategory(ChatEmojiCategory.Custom, _prototypeManager).FirstOrDefault() is
            { Alias.Length: > 0 } custom
            ? custom
            : ChatEmoji.GetCategoryIcon(ChatEmojiCategory.Smileys);
    }

    private ChatEmojiCategory GetDefaultCategory()
    {
        return ChatEmoji.HasCustomEmojis(_prototypeManager)
            ? ChatEmojiCategory.Custom
            : ChatEmojiCategory.Smileys;
    }

    private static string GetCategoryName(ChatEmojiCategory category)
    {
        var locId = category switch
        {
            ChatEmojiCategory.Custom => "hud-chatbox-emoji-category-custom",
            ChatEmojiCategory.Smileys => "hud-chatbox-emoji-category-smileys",
            ChatEmojiCategory.Nature => "hud-chatbox-emoji-category-nature",
            ChatEmojiCategory.Food => "hud-chatbox-emoji-category-food",
            ChatEmojiCategory.Activities => "hud-chatbox-emoji-category-activities",
            ChatEmojiCategory.Travel => "hud-chatbox-emoji-category-travel",
            ChatEmojiCategory.Objects => "hud-chatbox-emoji-category-objects",
            ChatEmojiCategory.Symbols => "hud-chatbox-emoji-category-symbols",
            ChatEmojiCategory.Flags => "hud-chatbox-emoji-category-flags",
            _ => throw new ArgumentOutOfRangeException(nameof(category), category, null)
        };

        return Loc.GetString(locId);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            OnPopupOpen -= OnPopupOpened;

        base.Dispose(disposing);
    }
}
