using System.Linq;
using System.Numerics;
using Content.Client._RW.UserInterface.Systems.Chat.RichText;
using Content.Shared.Chat;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

using Robust.Shared.IoC;

namespace Content.Client._RW.UserInterface.Systems.Chat.Controls;

[GenerateTypedNameReferences]
public sealed partial class EmojiPickerPopup : Popup
{
    public const float PopupWidth = 600f;
    public const float PopupHeight = 440f;

    private const float EmojiButtonSize = 36f;
    private const float ResizeMargin = 8f;

    private DragMode _currentDrag = DragMode.None;
    private Vector2 _dragOffsetTopLeft;
    private Vector2 _dragOffsetBottomRight;

    private Vector2? _customPosition;
    private float _customWidth = PopupWidth;

    public float CustomWidth => _customWidth;

    private enum DragMode : byte
    {
        None = 0,
        Move = 1,
        Left = 2,
        Right = 3
    }

    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly Dictionary<ChatEmojiCategory, Button> _categoryButtons = new();
    private ButtonGroup _categoryGroup = new(isNoneSetAllowed: false);
    private ChatEmojiCategory _selectedCategory = ChatEmojiCategory.Smileys;

    public event Action<string>? OnEmojiPicked;

    public EmojiPickerPopup()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        MouseFilter = MouseFilterMode.Pass;

        CloseButton.OnPressed += _ => Close();
        OnPopupOpen += OnPopupOpened;
        RebuildCategoryButtons();
        _selectedCategory = GetDefaultCategory();
        SelectCategory(_selectedCategory);
    }

    private void SelectCategory(ChatEmojiCategory category)
    {
        if (!_categoryButtons.ContainsKey(category))
            category = GetDefaultCategory();

        _selectedCategory = category;
        HeaderLabel.Text = GetCategoryName(category);
        PreviewLabel.SetMessage(
            FormattedMessage.FromUnformatted(Loc.GetString("hud-chatbox-emoji-preview-empty")));

        if (_categoryButtons.TryGetValue(category, out var selectedButton))
            selectedButton.Pressed = true;

        EmojiGrid.DisposeAllChildren();

        foreach (var emoji in ChatEmoji.EnumerateCategory(category, _prototypeManager))
        {
            var emojiButton = new Button
            {
                MinSize = new Vector2(EmojiButtonSize),
                ToolTip = $":{emoji.Alias}:",
                StyleClasses = { StyleClass.ButtonSquare }
            };

            emojiButton.AddChild(ChatEmojiRichText.CreatePickerTextureRect(_resourceCache, emoji));
            emojiButton.OnPressed += _ => OnEmojiPicked?.Invoke(emoji.InsertText);
            emojiButton.OnMouseEntered += _ => PreviewLabel.SetMessage(
                ChatEmojiRichText.BuildPreviewMessage(emoji));
            EmojiGrid.AddChild(emojiButton);
        }
    }

    private void OnPopupOpened()
    {
        RebuildCategoryButtons();

        if (!_categoryButtons.ContainsKey(_selectedCategory))
            _selectedCategory = GetDefaultCategory();

        SelectCategory(_selectedCategory);
        RecalculateColumns();
    }

    private void RebuildCategoryButtons()
    {
        _categoryButtons.Clear();
        _categoryGroup = new ButtonGroup(isNoneSetAllowed: false);
        CategoryBox.DisposeAllChildren();

        foreach (var category in ChatEmoji.GetCategoryOrder(_prototypeManager))
        {
            var button = new Button
            {
                Group = _categoryGroup,
                MinSize = new Vector2(32f),
                ToolTip = GetCategoryName(category)
            };

            button.AddChild(
                ChatEmojiRichText.CreateCategoryTextureRect(_resourceCache, GetCategoryIcon(category)));
            button.OnPressed += _ => SelectCategory(category);
            _categoryButtons[category] = button;
            CategoryBox.AddChild(button);
        }
    }

    private ChatEmojiDefinition GetCategoryIcon(ChatEmojiCategory category)
    {
        if (category != ChatEmojiCategory.Custom)
            return ChatEmoji.GetCategoryIcon(category);

        return ChatEmoji.EnumerateCategory(ChatEmojiCategory.Custom, _prototypeManager).FirstOrDefault() is
            { Alias.Length: > 0 } custom
            ? custom
            : ChatEmoji.GetCategoryIcon(ChatEmojiCategory.Smileys);
    }

    private ChatEmojiCategory GetDefaultCategory()
    {
        return ChatEmoji.HasCustomEmojis(_prototypeManager)
            ? ChatEmojiCategory.Custom
            : ChatEmojiCategory.Smileys;
    }

    private static string GetCategoryName(ChatEmojiCategory category)
    {
        var locId = category switch
        {
            ChatEmojiCategory.Custom => "hud-chatbox-emoji-category-custom",
            ChatEmojiCategory.Smileys => "hud-chatbox-emoji-category-smileys",
            ChatEmojiCategory.Nature => "hud-chatbox-emoji-category-nature",
            ChatEmojiCategory.Food => "hud-chatbox-emoji-category-food",
            ChatEmojiCategory.Activities => "hud-chatbox-emoji-category-activities",
            ChatEmojiCategory.Travel => "hud-chatbox-emoji-category-travel",
            ChatEmojiCategory.Objects => "hud-chatbox-emoji-category-objects",
            ChatEmojiCategory.Symbols => "hud-chatbox-emoji-category-symbols",
            ChatEmojiCategory.Flags => "hud-chatbox-emoji-category-flags",
            _ => throw new ArgumentOutOfRangeException(nameof(category), category, null)
        };

        return Loc.GetString(locId);
    }

    public new void Open(UIBox2 box, Vector2? altPos = null)
    {
        var targetBox = box;
        var size = new Vector2(_customWidth, targetBox.Height);
        var position = _customPosition ?? targetBox.TopLeft;

        if (UserInterfaceManager != null)
        {
            var rootSize = UserInterfaceManager.RootControl.Size;
            var maxX = Math.Max(0f, rootSize.X - _customWidth);
            var maxY = Math.Max(0f, rootSize.Y - targetBox.Height);
            position.X = Math.Clamp(position.X, 0f, maxX);
            position.Y = Math.Clamp(position.Y, 0f, maxY);
        }

        targetBox = UIBox2.FromDimensions(position, size);
        base.Open(targetBox, altPos);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIClick)
        {
            return;
        }

        _currentDrag = GetDragModeFor(args.RelativePosition);

        if (_currentDrag != DragMode.None)
        {
            _dragOffsetTopLeft = args.PointerLocation.Position / UIScale - Position;
            _dragOffsetBottomRight = Position + Size - args.PointerLocation.Position / UIScale;
            args.Handle();
        }
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Function != EngineKeyFunctions.UIClick)
        {
            return;
        }

        _dragOffsetTopLeft = _dragOffsetBottomRight = Vector2.Zero;
        _currentDrag = DragMode.None;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (Parent == null)
            return;

        if (_currentDrag == DragMode.Move)
        {
            var globalPos = args.GlobalPosition;
            globalPos = Vector2.Clamp(globalPos, Vector2.Zero, Parent.Size);
            var newPos = globalPos - _dragOffsetTopLeft;

            var maxX = Math.Max(0f, Parent.Size.X - Size.X);
            var maxY = Math.Max(0f, Parent.Size.Y - Size.Y);
            newPos.X = Math.Clamp(newPos.X, 0f, maxX);
            newPos.Y = Math.Clamp(newPos.Y, 0f, maxY);

            _customPosition = newPos;
            PopupContainer.SetPopupOrigin(this, _customPosition.Value);
            return;
        }

        if (_currentDrag == DragMode.None)
        {
            var cursor = CursorShape.Arrow;
            var previewDragMode = GetDragModeFor(args.RelativePosition);

            if (previewDragMode == DragMode.Left || previewDragMode == DragMode.Right)
            {
                cursor = CursorShape.HResize;
            }

            DefaultCursorShape = cursor;
        }
        else
        {
            var left = Position.X;
            var right = Position.X + Size.X;

            if (_currentDrag == DragMode.Left)
            {
                left = Math.Min(args.GlobalPosition.X - _dragOffsetTopLeft.X, right - MinSize.X);
                left = Math.Max(0f, left);
                _customWidth = right - left;
            }
            else if (_currentDrag == DragMode.Right)
            {
                right = Math.Max(args.GlobalPosition.X + _dragOffsetBottomRight.X, left + MinSize.X);
                right = Math.Min(Parent.Size.X, right);
                _customWidth = right - left;
            }

            if (_currentDrag == DragMode.Left)
            {
                _customPosition = new Vector2(left, Position.Y);
                PopupContainer.SetPopupOrigin(this, _customPosition.Value);
            }

            InvalidateMeasure();
            InvalidateArrange();
        }
    }

    protected override void MouseExited()
    {
        base.MouseExited();

        if (_currentDrag == DragMode.None)
        {
            DefaultCursorShape = CursorShape.Arrow;
        }
    }

    private DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        if (relativeMousePos.X < ResizeMargin)
        {
            return DragMode.Left;
        }
        if (relativeMousePos.X > Size.X - ResizeMargin)
        {
            return DragMode.Right;
        }
        if (relativeMousePos.Y < 32f)
        {
            return DragMode.Move;
        }
        return DragMode.None;
    }

    protected override Vector2 MeasureOverride(Vector2 availableSize)
    {
        EmojiPopupPanel.Measure(availableSize);
        return new Vector2(_customWidth, EmojiPopupPanel.DesiredSize.Y);
    }

    protected override Vector2 ArrangeOverride(Vector2 finalSize)
    {
        EmojiPopupPanel.Arrange(new UIBox2(Vector2.Zero, finalSize));
        return finalSize;
    }

    protected override void Resized()
    {
        base.Resized();
        RecalculateColumns();
    }

    private void RecalculateColumns()
    {
        if (EmojiGrid == null)
            return;

        var parentWidth = EmojiGrid.Parent?.Size.X ?? 0f;
        var availableWidth = parentWidth > 16f
            ? parentWidth - 16f
            : (Size.X > 0 ? Size.X : PopupWidth) - 120f;

        const float buttonStep = 52f;
        var columns = (int) Math.Max(1, Math.Floor((availableWidth + 6f) / buttonStep));
        EmojiGrid.Columns = columns;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            OnPopupOpen -= OnPopupOpened;

        base.Dispose(disposing);
    }
}
