# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Mindcontrolled
  name: roles-antag-mindcontrolled-name
  antagonist: true
  setPreference: false
  objective: roles-antag-mindcontrolled-objective