// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client._Orion.Research.UI;
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Common.Research;
using Content.Goobstation.Shared.Research;
using Content.Shared._Orion.Research;
using Content.Shared._Orion.Research.Prototypes;
using Content.Shared.Access.Systems;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Goobstation.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleMenu : FancyWindow
{
    public Action<string>? OnTechnologyCardPressed;
    public Action? OnServerButtonPressed;
    // Orion-Start
    private FancyResearchConsoleLogWindow? _journalWindow;
    private ResearchConsoleBoundInterfaceState? _lastState;
    // Orion-End

    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!; // Orion

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;

    /// <summary>
    /// Console entity
    /// </summary>
    private EntityUid Entity; // Orion-Edit: Was public

    /// <summary>
    /// Currently selected tech
    /// Exsists for better UI refreshing
    /// </summary>
    private ProtoId<TechnologyPrototype>? _currentTech; // Orion-Edit

    /// <summary>
    /// All technologies and their availablity
    /// </summary>
    public Dictionary<string, ResearchAvailability> List = new();

    /// <summary>
    /// Cached research points
    /// </summary>
//    public int Points = 0; // Orion-Edit

    /// <summary>
    /// Is tech currently being dragged
    /// </summary>
    private bool _draggin;

    /// <summary>
    /// Global position that all tech relates to.
    /// For dragging mostly
    /// </summary>
    private Vector2 _position = new(45, 250); // Orion-Edit
    private float _zoom = 1f;
    private const float MinZoom = 0.5f;
    private const float MaxZoom = 2f;
    private const float ZoomSpeed = 0.125f;

    public FancyResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();
        StaticSprite.SetFromSpriteSpecifier(new SpriteSpecifier.Rsi(new("_Goobstation/Interface/rnd-static.rsi"), "static"));
        StaticSprite.DisplayRect.CanShrink = true;
        StaticSprite.DisplayRect.Stretch = TextureRect.StretchMode.Scale;

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        JournalButton.OnPressed += _ => ToggleJournalWindow(); // Orion
        DragContainer.OnKeyBindDown += OnKeybindDown;
        DragContainer.OnKeyBindUp += OnKeybindUp;
        RecenterButton.OnPressed += _ => Recenter();

        UpdatePanels(List);
        Recenter();
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
    }

    public void UpdatePanels(Dictionary<string, ResearchAvailability> dict)
    {
        DragContainer.RemoveAllChildren();
        List = dict;

        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);

            var control = new FancyResearchConsoleItem(proto, _sprite, _prototype, tech.Value); // Orion-Edit: _prototype
            DragContainer.AddChild(control);
            control.SetScale(_zoom); // Orion

            // Set position for all tech, relating to _position
            LayoutContainer.SetPosition(control, _position + proto.Position * 150 * _zoom);
            control.SelectAction += SelectTech;

            if (tech.Key == _currentTech) // Orion-Edit
                SelectTech(proto, tech.Value);
        }
    }

    // Orion-Start
    private bool ShouldShowDisciplineProgress(ResearchConsoleBoundInterfaceState state, TechDisciplinePrototype discipline)
    {
        return state.VisibleTechnologies.Any(technologyId => _prototype.Index(technologyId).Discipline == discipline.ID) ||
               state.AvailableTechnologies.Any(technologyId => _prototype.Index(technologyId).Discipline == discipline.ID) ||
               state.ResearchedTechnologies.Any(technologyId => _prototype.Index(technologyId).Discipline == discipline.ID);
    }
    // Orion-End

    public void UpdateInformationPanel(ResearchConsoleBoundInterfaceState state) // Orion-Edit
    {
//        Points = points; // Orion-Edit
        _lastState = state; // Orion

        var amountMsg = new FormattedMessage();
        // Orion-Edit-Start
        var networkId = !string.IsNullOrWhiteSpace(state.NetworkId)
            ? FormattedMessage.EscapeText(state.NetworkId)
            : Loc.GetString("research-machine-common-none");
        amountMsg.AddMarkupOrThrow($"{Loc.GetString("research-console-network-label")} [color=white]{networkId}[/color]");
        // Orion-Edit-End

        // Orion-Start
        foreach (var balance in state.PointBalances)
        {
            amountMsg.PushNewline();
            var type = GetLocalizedPointType(balance.Type);
            amountMsg.AddMarkupOrThrow($"[color=lightgreen]{type}[/color]: {balance.Amount}");
        }
        // Orion-End
        ResearchAmountLabel.SetMessage(amountMsg);

        UpdateJournalWindow(state); // Orion

        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        TierDisplayContainer.RemoveAllChildren();
        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index(disciplineId); // Orion-Edit

            // Orion-Start
            if (!ShouldShowDisciplineProgress(state, discipline))
                continue;
            // Orion-End

            var tier = SharedResearchSystemExtensions.GetTierCompletionPercentage(database, discipline, _prototype); // Orion-Edit

            // i'm building the small-ass control here to spare me some mild annoyance in making a new file
            var texture = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center,
            };
            var label = new RichTextLabel();
            texture.Texture = _sprite.Frame0(discipline.Icon);
            label.SetMessage(Loc.GetString("research-console-tier-percentage", ("perc", tier)));

            var control = new BoxContainer
            {
                Children =
                {
                    texture,
                    label,
                    new Control
                    {
                        MinWidth = 10,
                    },
                },
            };
            TierDisplayContainer.AddChild(control);
        }
    }

    // Orion-Start
    private string GetLocalizedPointType(string type)
    {
        var key = $"research-point-type-{type.ToLowerInvariant()}";
        return _loc.TryGetString(key, out var localized) ? localized : type;
    }

    private string GetLocalizedLogCategory(string category)
    {
        var key = NormalizeLogCategoryKey(category);
        return _loc.TryGetString(key, out var localized) ? localized : category;
    }

    private static string NormalizeLogCategoryKey(string category)
    {
        const string prefix = "research-log-category-";

        if (category.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
            return category.ToLowerInvariant();

        var normalized = category.Trim().Replace("_", "-").Replace(" ", "-").ToLowerInvariant();
        return $"{prefix}{normalized}";
    }

    private void ToggleJournalWindow()
    {
        if (_journalWindow == null)
        {
            _journalWindow = new FancyResearchConsoleLogWindow();
            _journalWindow.OnClose += () => _journalWindow = null;
        }

        if (_journalWindow.IsOpen)
            _journalWindow.Close();
        else
            _journalWindow.OpenCentered();

        if (_lastState != null)
            UpdateJournalWindow(_lastState);
    }

    private void UpdateJournalWindow(ResearchConsoleBoundInterfaceState state)
    {
        if (_journalWindow == null)
            return;

        var experimentEntries = new List<Control>();
        foreach (var experiment in state.Experiments)
        {
            if (!_prototype.TryIndex<ResearchExperimentPrototype>(experiment.Id, out var proto))
                continue;

            experimentEntries.Add(BuildExperimentEntry(proto, experiment));
        }

        if (experimentEntries.Count == 0)
        {
            experimentEntries.Add(new Label
            {
                Text = Loc.GetString("research-console-experiments-empty"),
                Modulate = Color.Gray,
            });
        }

        var logsMessage = new FormattedMessage();
        if (state.Logs.Count == 0)
        {
            logsMessage.AddMarkupOrThrow($"[color=gray]{Loc.GetString("research-console-logs-empty")}[/color]");
        }
        else
        {
            foreach (var log in state.Logs)
            {
                if (!logsMessage.IsEmpty)
                    logsMessage.PushNewline();

                var category = GetLocalizedLogCategory(log.Category);
                logsMessage.AddMarkupOrThrow($"[color=gray]{FormattedMessage.EscapeText(category)}[/color] ");
                logsMessage.AddText(log.Message);
            }
        }

        _journalWindow.SetExperimentEntries(experimentEntries);
        _journalWindow.SetLogsMessage(logsMessage);
    }

    private Control BuildExperimentEntry(ResearchExperimentPrototype proto, ResearchConsoleExperimentData experiment)
    {
        var stateText = experiment.State switch
        {
            ResearchExperimentState.Active => Loc.GetString("research-console-experiment-state-active"),
            ResearchExperimentState.Available => Loc.GetString("research-console-experiment-state-available"),
            ResearchExperimentState.Completed => Loc.GetString("research-console-experiment-state-completed"),
            ResearchExperimentState.Skipped => Loc.GetString("research-console-experiment-state-skipped"),
            _ => Loc.GetString("research-console-experiment-state-unavailable"),
        };

        var rewardText = GetExperimentRewardSummary(proto);

        var stateLabel = new RichTextLabel
        {
            HorizontalExpand = true,
            MaxWidth = 540,
        };

        var rewardLabel = new RichTextLabel
        {
            HorizontalExpand = true,
            MaxWidth = 540,
        };

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 2,
            Margin = new Thickness(6),
            Children =
            {
                stateLabel,
                new Label
                {
                    Text = Loc.GetString(proto.Name),
                    ClipText = false,
                    HorizontalExpand = true,
                },
                new Label
                {
                    Text = $"{experiment.Progress}/{experiment.Target}",
                    Modulate = Color.LightGray,
                },

                rewardLabel,
            },
        };

        var stateMessage = new FormattedMessage();
        stateMessage.AddMarkupOrThrow($"[color=lightblue]{FormattedMessage.EscapeText(stateText)}[/color]");
        stateLabel.SetMessage(stateMessage);

        var rewardMessage = new FormattedMessage();
        rewardMessage.AddMarkupOrThrow($"[color=lightgreen]{FormattedMessage.EscapeText(rewardText)}[/color]");
        rewardLabel.SetMessage(rewardMessage);

        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#23232A"),
                BorderColor = Color.FromHex("#4A4A56"),
                BorderThickness = new Thickness(1),
            },
            HorizontalExpand = true,
            Children = { content },
        };
    }

    private string GetExperimentRewardSummary(ResearchExperimentPrototype experiment)
    {
        var parts = new List<string>();
        var reward = experiment.Reward;

        if (reward.ResearchPoints != 0)
            parts.Add(Loc.GetString("research-console-experiment-reward-points", ("type", GetLocalizedPointType("general")), ("amount", reward.ResearchPoints)));

        foreach (var pointReward in reward.PointRewards)
        {
            var pointType = GetLocalizedPointType(pointReward.Type);
            parts.Add(Loc.GetString("research-console-experiment-reward-points", ("type", pointType), ("amount", pointReward.Amount)));
        }

        if (reward.FlatDiscount > 0)
            parts.Add(Loc.GetString("research-console-experiment-reward-flat-discount", ("amount", reward.FlatDiscount)));

        if (reward.PercentageDiscount > 0)
            parts.Add(Loc.GetString("research-console-experiment-reward-percent-discount", ("percent", MathF.Round(reward.PercentageDiscount * 100f, 1))));

        var discountedTechnologies = new List<string>();
        foreach (var technology in _prototype.EnumeratePrototypes<TechnologyPrototype>())
        {
            if (!technology.DiscountExperimentCosts.TryGetValue(experiment.ID, out var discount) || discount <= 0)
                continue;

            discountedTechnologies.Add(Loc.GetString("research-console-experiment-reward-technology-discount-entry",
                ("technology", Loc.GetString(technology.Name)),
                ("amount", discount)));
        }

        if (discountedTechnologies.Count > 0)
        {
            parts.Add(Loc.GetString("research-console-experiment-reward-technology-discounts",
                ("technologies", string.Join(", ", discountedTechnologies))));
        }

        if (reward.UnlockExperiments.Count > 0)
            parts.Add(Loc.GetString("research-console-experiment-reward-unlock-experiments", ("count", reward.UnlockExperiments.Count)));

        if (reward.RevealTechnologies.Count > 0)
            parts.Add(Loc.GetString("research-console-experiment-reward-reveal-technologies", ("count", reward.RevealTechnologies.Count)));

        var technologiesUnlockedByCompletion = new List<string>();
        foreach (var technology in _prototype.EnumeratePrototypes<TechnologyPrototype>())
        {
            if (!technology.RequiredExperiments.Contains(experiment.ID))
                continue;

            technologiesUnlockedByCompletion.Add(Loc.GetString(technology.Name));
        }

        if (technologiesUnlockedByCompletion.Count > 0)
        {
            parts.Add(Loc.GetString("research-console-experiment-reward-unlocked-technologies",
                ("technologies", string.Join(", ", technologiesUnlockedByCompletion))));
        }

        if (reward.InfrastructureUnlock)
            parts.Add(Loc.GetString("research-console-experiment-reward-infrastructure"));

        return parts.Count == 0
            ? Loc.GetString("research-console-experiment-reward-none")
            : string.Join(", ", parts);
    }
    // Orion-End

    #region Drag handle
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_draggin)
            return;

        _position += args.Relative;

        // Move all tech
        foreach (var child in DragContainer.Children)
        {
            LayoutContainer.SetPosition(child, child.Position + args.Relative);
        }
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        var oldZoom = _zoom;

        if (args.Delta.Y > 0)
            _zoom += ZoomSpeed;
        else
            _zoom -= ZoomSpeed;

        _zoom = Math.Clamp(_zoom, MinZoom, MaxZoom);

        if (MathHelper.CloseTo(oldZoom, _zoom))
            return;

        foreach (var child in DragContainer.Children)
        {
            if (child is not FancyResearchConsoleItem research)
                continue;

            var pos = research.Prototype.Position * 150;
            LayoutContainer.SetPosition(child, _position + pos * _zoom);
            research.SetScale(_zoom);
        }
        args.Handle();
    }

    /// <summary>
    /// Raised when LMB is pressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = true;
    }

    /// <summary>
    /// Raised when LMB is unpressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return _draggin ? DragMode.None : base.GetDragModeFor(relativeMousePos);
    }

    #endregion

    /// <summary>
    /// Selects a tech prototype and opens info panel
    /// </summary>
    /// <param name="proto">Tech proto</param>
    /// <param name="availability">Tech availablity</param>
    private void SelectTech(TechnologyPrototype proto, ResearchAvailability availability) // Orion-Edit: Was public
    {
        InfoContainer.RemoveAllChildren();
        if (!_player.LocalEntity.HasValue)
            return;

        // Orion-Edit-Start
        _currentTech = proto.ID;
        var lockReason = GetLockReason(proto);
        _entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database);
        var control = new FancyTechnologyInfoPanel(proto, _accessReader.IsAllowed(_player.LocalEntity.Value, Entity), availability, lockReason, _sprite, _prototype, database);
        // Orion-Edit-End
        control.BuyAction += args => OnTechnologyCardPressed?.Invoke(args.ID);
        InfoContainer.AddChild(control);
    }

    // Orion-Start
    private ResearchTechnologyLockReason GetLockReason(TechnologyPrototype proto)
    {
        return !_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database)
            ? ResearchTechnologyLockReason.None
            : Content.Shared.Research.Systems.SharedResearchSystem.GetTechnologyLockReason(database, proto);
    }
    // Orion-End

    /// <summary>
    /// Sets <see cref="_position"/> to its default value
    /// </summary>
    private void Recenter() // Orion-Edit: Was public
    {
        _position = new(45, 250);
        foreach (var item in DragContainer.Children)
        {
            if (item is not FancyResearchConsoleItem research)
                continue;

            LayoutContainer.SetPosition(item, _position + research.Prototype.Position * 150 * _zoom);
        }
    }

    public override void Close()
    {
        base.Close();

        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
        // Orion-Start
        _journalWindow?.Close();
        _journalWindow = null;
        // Orion-End
    }

    private sealed partial class DisciplineButton(TechDisciplinePrototype proto) : Button
    {
        public TechDisciplinePrototype Proto = proto;
    }
}
