// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Goobstation.Common.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleItem : LayoutContainer
{
    // Public fields
    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype, ResearchAvailability>? SelectAction;
    private ResearchAvailability _availability; // RW-Edit: Was public

    // Some visuals
    private Color _color; // RW-Edit
    private Color _borderColor; // RW-Edit
    private Color _hoveredColor; // RW-Edit

    public FancyResearchConsoleItem(TechnologyPrototype proto, SpriteSystem sprite, IPrototypeManager prototypeManager, ResearchAvailability availability) // RW-Edit
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _availability = availability; // RW-Edit
        Prototype = proto;

        ResearchDisplay.Texture = sprite.Frame0(proto.Icon);

        // RW-Start
        if (prototypeManager.TryIndex(proto.Discipline, out var discipline))
            DisciplineDisplay.Texture = sprite.Frame0(discipline.Icon);
        // RW-End

        Button.OnPressed += Selected;
        Button.OnDrawModeChanged += UpdateColor;

        (_color, _hoveredColor, _borderColor) = availability switch // RW-Edit
        {
            ResearchAvailability.Researched => (Color.DarkOliveGreen, Color.PaleGreen, Color.LimeGreen),
            ResearchAvailability.Available => (Color.FromHex("#7c7d2a"), Color.FromHex("#ecfa52"), Color.FromHex("#e8fa25")),
            ResearchAvailability.PrereqsMet => (Color.FromHex("#6b572f"), Color.FromHex("#fad398"), Color.FromHex("#cca031")),
//            ResearchAvailability.Unavailable => (Color.DarkRed, Color.PaleVioletRed, Color.Crimson), // RW-Edit
            _ => (Color.DarkRed, Color.PaleVioletRed, Color.Crimson),
        };

        UpdateColor();
    }

    private void UpdateColor()
    {
        var panel = (StyleBoxFlat) Panel.PanelOverride!;
        panel.BackgroundColor = Button.IsHovered ? _hoveredColor : _color; // RW-Edit

        panel.BorderColor = _borderColor; // RW-Edit
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        Button.OnPressed -= Selected;
    }

    private void Selected(BaseButton.ButtonEventArgs args)
    {
        SelectAction?.Invoke(Prototype, _availability); // RW-Edit
    }

    public void SetScale(float scale)
    {
        // RW-Edit-Start
        NodeContainer.SetSize = new Vector2(80 * scale, 80 * scale);

        var badgeSize = new Vector2(20 * scale, 20 * scale);
        DisciplineBadge.SetSize = badgeSize;
        SetPosition(DisciplineBadge, Vector2.Zero);
        DisciplineDisplay.SetSize = badgeSize;
        // RW-Edit-End
    }
}

public sealed class DrawButton : Button
{
    public event Action? OnDrawModeChanged;

    protected override void DrawModeChanged()
    {
        OnDrawModeChanged?.Invoke();
    }
}
