// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.Lathe;
using Content.Client.Research;
using Content.Client.Research.UI;
using Content.Goobstation.Common.Research;
using Content.Shared._Orion.Research;
using Content.Shared._Orion.Research.Prototypes;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Goobstation.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyTechnologyInfoPanel : Control
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!; // Orion

    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype>? BuyAction;

    public FancyTechnologyInfoPanel(TechnologyPrototype proto, bool hasAccess, ResearchAvailability availability, ResearchTechnologyLockReason lockReason, SpriteSystem sprite, IPrototypeManager prototype, TechnologyDatabaseComponent? database = null) // Orion-Edit
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var lathe = _ent.System<LatheSystem>();
        var research = _ent.System<ResearchSystem>();
        Prototype = proto;

        TechnologyNameLabel.Text = Loc.GetString(proto.Name);
        DisciplineTexture.Texture = sprite.Frame0(_proto.Index(proto.Discipline).Icon);
        TechnologyTexture.Texture = sprite.Frame0(proto.Icon);

        InitializePrerequisites(proto, research, sprite, lockReason, prototype); // Orion-Edit

        InitializeRecipeUnlocks(proto, lathe, sprite);

        ResearchButton.ToolTip = !hasAccess
            ? Loc.GetString("research-console-no-access-popup")
            : null;

        ResearchButton.Text = availability == ResearchAvailability.Researched
            ? Loc.GetString("research-console-menu-server-researched-button")
            : ResearchButton.Text;

        Color? color = availability switch
        {
            ResearchAvailability.Researched => Color.LimeGreen,
            ResearchAvailability.PrereqsMet => Color.Crimson,
            ResearchAvailability.Unavailable => Color.Crimson,
            _ => null,
        };

        // Orion-Edit-Start
        var costMessage = new FormattedMessage();
        costMessage.AddMarkupOrThrow($"[bold]{Loc.GetString("research-console-tech-cost-title")}[/bold]");
        var finalCosts = database == null
            ? proto.PointCosts
            : research.GetTechnologyFinalPointCostsForUi(database, proto);
        foreach (var cost in proto.PointCosts)
        {
            costMessage.PushNewline();
            var pointType = LocalizePointType(cost.Type);
            var match = finalCosts.FirstOrDefault(v => v.Type == cost.Type);
            var finalCost = match == default ? cost.Amount : match.Amount;
            if (finalCost >= cost.Amount)
            {
                costMessage.AddMarkupOrThrow($"• [color=lightgreen]{pointType}[/color]: [color=orchid]{cost.Amount}[/color]");
                continue;
            }

            var discountPercent = cost.Amount > 0
                ? (cost.Amount - finalCost) * 100f / cost.Amount
                : 0f;

            costMessage.AddMarkupOrThrow($"• [color=lightgreen]{pointType}[/color]: [font size=10][color=lightgray]{ToStrikethrough(cost.Amount.ToString())}[/color][/font] [color=orchid]{finalCost}[/color] [color=yellow]([bold]{discountPercent:0.#}%[/bold])[/color]");
        }

        TechnologyCostLabel.SetMessage(costMessage, defaultColor: color);
        // Orion-Edit-End

        ResearchButton.Disabled = !hasAccess || availability != ResearchAvailability.Available;
        ResearchButton.OnPressed += Bought;
    }

    private void InitializePrerequisites(TechnologyPrototype proto, ResearchSystem research, SpriteSystem sprite, ResearchTechnologyLockReason lockReason, IPrototypeManager prototype) // Orion-Edit
    {
        // Orion-Edit-Start
        RequiredExperimentsContainer.RemoveAllChildren();
        var hasRequiredExperiments = false;

        foreach (var experimentId in proto.RequiredExperiments)
        {
            if (!prototype.TryIndex<ResearchExperimentPrototype>(experimentId, out var experiment))
                continue;

            var experimentLabel = new RichTextLabel
            {
                HorizontalExpand = true,
                MaxWidth = 400,
            };

            experimentLabel.SetMessage($"• {Loc.GetString(experiment.Name)}");
            RequiredExperimentsContainer.AddChild(experimentLabel);
            hasRequiredExperiments = true;
        }

        if (lockReason == ResearchTechnologyLockReason.MissingExperiments && hasRequiredExperiments)
        {
            MissingExperimentsLabel.Visible = true;
            var warningMessage = new FormattedMessage();
            warningMessage.AddMarkupOrThrow(Loc.GetString("research-console-tech-missing-experiments"));
            MissingExperimentsLabel.SetMessage(warningMessage);
        }
        else
        {
            MissingExperimentsLabel.Visible = false;
            MissingExperimentsLabel.SetMessage(string.Empty);
        }

        RequiredExperimentsBlock.Visible = hasRequiredExperiments;

        RequiredTechContainer.RemoveAllChildren();
        var shouldDisplayRequiredTechnologies = lockReason == ResearchTechnologyLockReason.MissingPrerequisites;
        if (shouldDisplayRequiredTechnologies)
        {
            foreach (var techId in proto.TechnologyPrerequisites)
            {
                if (!_proto.TryIndex(techId, out var tech))
                    continue;

                var description = research.GetTechnologyDescription(tech, true, false, true);
                RequiredTechContainer.AddChild(new MiniTechnologyCardControl(tech, _proto, sprite, description));
            }
        }

        var hasRequiredTechnologies = shouldDisplayRequiredTechnologies && RequiredTechContainer.ChildCount > 0;

        RequiredTechnologiesSection.Visible = hasRequiredTechnologies;

        var hasAnyRequirements = hasRequiredExperiments || hasRequiredTechnologies;
        NoPrereqLabel.Visible = !hasAnyRequirements;
        PrereqsContainer.Visible = hasAnyRequirements;
        // Orion-Edit-End
    }

    // Orion-Start
    private string LocalizePointType(string type)
    {
        var key = $"research-point-type-{type.ToLowerInvariant()}";
        return _loc.TryGetString(key, out var localized) ? localized : type;
    }

    private static string ToStrikethrough(string value)
    {
        const char strike = '\u0336';
        return string.Concat(value.Select(character => $"{character}{strike}")) + '\u200B';
    }
    // Orion-End

    private void InitializeRecipeUnlocks(TechnologyPrototype proto, LatheSystem lathe, SpriteSystem sprite)
    {
        UnlocksContainer.RemoveAllChildren();
        var hasRecipeUnlocks = false; // Orion
        foreach (var recipeId in proto.RecipeUnlocks)
        {
            var recipe = _proto.Index(recipeId);
            UnlocksContainer.AddChild(new MiniRecipeCardControl(proto, recipe, _proto, sprite, lathe));
            hasRecipeUnlocks = true; // Orion
        }

        // Orion-Start
        var hasGenericUnlocks = proto.GenericUnlocks.Count > 0;
        var hasVisibleUnlocks = hasRecipeUnlocks || hasGenericUnlocks;

        EmptyUnlocksStripe.Visible = !hasVisibleUnlocks;
        EmptyUnlocksLabel.Text = !hasVisibleUnlocks
            ? Loc.GetString("research-console-tech-empty-unlocks")
            : string.Empty;
        // Orion-End
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        ResearchButton.OnPressed -= Bought;
    }
    private void Bought(BaseButton.ButtonEventArgs args)
    {
        BuyAction?.Invoke(Prototype);
    }

}
