using System;
using Content.Shared._RW.Jukebox;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client._RW.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class RwJukeboxSongEntry : Control
{
    public RwJukeboxSong? Song { get; private set; }

    private RwJukeboxSongEntry()
    {
        RobustXamlLoader.Load(this);
    }

    public RwJukeboxSongEntry(RwJukeboxSong song, Action<RwJukeboxSong> callback) : this()
    {
        Song = song;
        SongNameLabel.Text = Song.SongName;
        PlaySongButton.OnPressed += _ => callback.Invoke(Song);
    }
}
