using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared._RW.Jukebox;
using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._RW.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class RwJukeboxMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    private readonly RwJukeboxSystem _jukeboxSystem;
    private readonly AudioSystem _audioSystem;

    private readonly EntityUid _jukeboxEntity;
    private readonly RwJukeboxComponent _component;

    private readonly List<RwJukeboxSongEntry> _defaultSongsEntries = new();
    private readonly List<RwJukeboxSongEntry> _tapeSongsEntries = new();

    private bool _playState;
    private float _lockTimer;

    public event Action? PlayPausePressed;
    public event Action? StopPressed;
    public event Action? EjectPressed;
    public event Action<bool>? RepeatToggled;
    public event Action<float>? SetPlaybackPosition;
    public event Action<float>? SetVolume;

    private bool _repeatButtonHeld;

    public RwJukeboxMenu(EntityUid jukeboxEntity, RwJukeboxComponent component)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _jukeboxSystem = _entityManager.System<RwJukeboxSystem>();
        _audioSystem = _entityManager.System<AudioSystem>();

        _jukeboxEntity = jukeboxEntity;
        _component = component;

        TabContainer.SetTabTitle(DefaultSongsTab, "Прямо с завода");
        TabContainer.SetTabTitle(TapeSongsTab, "Песенки с кассеты");

        PlayButton.OnPressed += _ => PlayPausePressed?.Invoke();
        StopButton.OnPressed += _ => StopPressed?.Invoke();
        EjectButton.OnPressed += _ => EjectPressed?.Invoke();

        RepeatButton.OnButtonDown += _ => _repeatButtonHeld = true;
        RepeatButton.OnButtonUp += _ => _repeatButtonHeld = false;
        RepeatButton.OnToggled += args => RepeatToggled?.Invoke(args.Pressed);

        PlaybackSlider.OnReleased += _ => OnPlaybackSliderReleased();
        VolumeSlider.OnReleased += _ => OnVolumeSliderReleased();

        PopulateDefaultSongsContainer(DefaultSongsContainer);
        PopulateTapeSongsContainer(TapeSongsContainer);

        RepeatButton.Pressed = _component.Playing;
        SetPlayPauseButton(_component.PlayingSongData != null && !_component.Paused, force: true);
    }

    private void OnPlaybackSliderReleased()
    {
        SetPlaybackPosition?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    private void OnVolumeSliderReleased()
    {
        SetVolume?.Invoke(VolumeSlider.Value / 100f);
        _lockTimer = 0.5f;
    }

    private void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;
        PlayButton.Text = playing ? "Пауза" : "Играть";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
        {
            _lockTimer -= args.DeltaSeconds;
        }

        PlaybackSlider.Disabled = _lockTimer > 0f;
        VolumeSlider.Disabled = _lockTimer > 0f;

        // Update current song display
        if (_component.PlayingSongData != null)
        {
            CurrentSongLabel.Text = _component.PlayingSongData.SongName ?? "---";
            var current = _component.PlayingSongData.PlaybackPosition;
            var total = _component.PlayingSongData.ActualSongLengthSeconds;
            DurationLabel.Text = $"{TimeSpan.FromSeconds(current):mm\\:ss} / {TimeSpan.FromSeconds(total):mm\\:ss}";

            if (!PlaybackSlider.Grabbed && _lockTimer <= 0f)
            {
                PlaybackSlider.MaxValue = total;
                PlaybackSlider.SetValueWithoutEvent(current);
            }
        }
        else
        {
            CurrentSongLabel.Text = "---";
            DurationLabel.Text = "00:00 / 00:00";
            PlaybackSlider.SetValueWithoutEvent(0f);
        }

        VolumeNumberLabel.Text = $"{VolumeSlider.Value:0.##}%";
        if (!VolumeSlider.Grabbed && _lockTimer <= 0f)
        {
            VolumeSlider.SetValueWithoutEvent(_component.Volume * 100f);
        }

        if (!_repeatButtonHeld && RepeatButton.Pressed != _component.Playing)
            RepeatButton.Pressed = _component.Playing;

        SetPlayPauseButton(_component.PlayingSongData != null && !_component.Paused);
    }

    private void PopulateDefaultSongsContainer(BoxContainer defaultSongsContainer)
    {
        defaultSongsContainer.DisposeAllChildren();
        _defaultSongsEntries.Clear();

        foreach (var proto in _protoManager.EnumeratePrototypes<JukeboxPrototype>())
        {
            var song = new RwJukeboxSong
            {
                SongName = proto.Name,
                SongPath = proto.Path.Path
            };

            var songEntry = new RwJukeboxSongEntry(song, RequestSongPlay);
            _defaultSongsEntries.Add(songEntry);
        }

        _defaultSongsEntries.Sort((x, y) => string.Compare(x.Song?.SongName, y.Song?.SongName, StringComparison.Ordinal));

        foreach (var defaultSongsEntry in _defaultSongsEntries)
        {
            defaultSongsContainer.AddChild(defaultSongsEntry);
        }
    }

    private void PopulateTapeSongsContainer(BoxContainer tapeSongsContainer)
    {
        tapeSongsContainer.DisposeAllChildren();
        _tapeSongsEntries.Clear();

        var tapes = _component.TapeContainer.ContainedEntities.ToList();

        foreach (var tapeUid in tapes)
        {
            if (_entityManager.TryGetComponent<RwTapeComponent>(tapeUid, out var tape))
            {
                foreach (var song in tape.Songs)
                {
                    var songEntry = new RwJukeboxSongEntry(song, RequestSongPlay);
                    _tapeSongsEntries.Add(songEntry);
                }
            }
        }

        foreach (var tapeSongsEntry in _tapeSongsEntries)
        {
            tapeSongsContainer.AddChild(tapeSongsEntry);
        }
    }

    private void RequestSongPlay(RwJukeboxSong song)
    {
        _jukeboxSystem.RequestSongToPlay(_jukeboxEntity, _component, song);
    }
}
