using System.Collections.Generic;
using System.Text.RegularExpressions;
using Content.Shared._RW;
using Content.Shared._RW.Jukebox;
using Content.Shared.Popups;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._RW.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class RwTapeCreatorMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IFileDialogManager _fileDialogManager = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    private readonly SharedPopupSystem _popupSystem;

    private double _maxFileSize;
    private double _currentFileSize;
    private readonly List<byte> _songBytes = new();
    private RwTapeCreatorComponent _component;

    private bool _awaitingUploadResponse;

    private const double BytesToMegabytes = 1.0d / (1024d * 1024d);

    public RwTapeCreatorMenu(RwTapeCreatorComponent component)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _popupSystem = _entityManager.System<SharedPopupSystem>();

        _cfg.OnValueChanged(RwCVars.MaxJukeboxSongSizeInMb, x => _maxFileSize = x, true);

        _component = component;

        LoadSongButton.OnPressed += TryLoadSong;
        UploadSong.OnPressed += OnUploadButtonPressed;
    }

    private void OnUploadButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        if (!CanUploadSong())
            return;

        var input = SongNameField.Text;

        const string pattern = @"[^a-zA-Zа-яА-ЯёЁ ]+";
        var songName = Regex.Replace(input, pattern, "");
        songName = Regex.Replace(songName, @"\s+", " ").Trim();
        if (string.IsNullOrWhiteSpace(songName))
        {
            _popupSystem.PopupEntity("Имя песни не должно быть пустым.", _component.Owner);
            return;
        }

        var msg = new RwJukeboxSongUploadRequest
        {
            SongName = songName,
            SongBytes = new List<byte>(_songBytes),
            TapeCreatorUid = _entityManager.GetNetEntity(_component.Owner)
        };

        _entityManager.EntityNetManager?.SendSystemNetworkMessage(msg);

        _awaitingUploadResponse = true;
        _popupSystem.PopupEntity("Начинается запись на кассету...", _component.Owner);
    }

    public void HandleUploadResponse(bool success, string? message)
    {
        if (!_awaitingUploadResponse)
            return;

        _awaitingUploadResponse = false;

        if (success)
        {
            _currentFileSize = 0;
            _songBytes.Clear();
            SongNameField.Clear();
            _popupSystem.PopupEntity(message ?? "Запись на кассету завершена.", _component.Owner);
        }
        else
        {
            _popupSystem.PopupEntity(message ?? "Ошибка записи на кассету.", _component.Owner);
        }
    }

    private async void TryLoadSong(BaseButton.ButtonEventArgs obj)
    {
        var fileFilter = new FileDialogFilters(new FileDialogFilters.Group("ogg"));
        var file = await _fileDialogManager.OpenFile(fileFilter);

        if (Disposed || file == null)
            return;

        _currentFileSize = file.Length * BytesToMegabytes;

        if (_currentFileSize > _maxFileSize)
        {
            _songBytes.Clear();
            _currentFileSize = 0;
            _popupSystem.PopupEntity($"Файл слишком большой! Лимит: {_maxFileSize} МБ", _component.Owner);
            return;
        }

        _songBytes.Clear();
        _songBytes.AddRange(file.CopyToArray());
        _popupSystem.PopupEntity("Песня загружена в буфер.", _component.Owner);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        CoinsLabel.Text = _component.CoinBalance.ToString();
        UploadSong.Disabled = !CanUploadSong();
    }

    private bool CanUploadSong()
    {
        return !_awaitingUploadResponse
               && SongNameField.Text.Length > 0
               && _songBytes.Count > 0
               && _component.CoinBalance > 0
               && _component.InsertedTape.HasValue
               && !_component.Recording;
    }
}
