name: Mark and Close Stale Pull Requests

on:
  workflow_dispatch:
  schedule:
    # Runs daily at midnight UTC.
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      # Currently we are not planning on marking issues as stale, so this permission is read only.
      # Just gonna leave this in here in case we need it in the future.
      issues: read
      pull-requests: write # Required to add labels, comment, close PRs.

    steps:
      - name: Mark and Close Stale Pull Requests
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # --- Ignore Issues ---
          # Set to -1 so we never mark issues as stale.
          days-before-issue-stale: -1

          # --- Pull Request Specific Settings ---
          # Number of days of inactivity before a Pull Request becomes stale (currently 2 weeks)
          days-before-pr-stale: 14

          # Number of days of inactivity after being marked stale before a Pull Request is closed (2 more weeks)
          days-before-pr-close: 14

          # Label to use when marking a PR as stale
          stale-pr-label: 'Note: Stale'

          # Comment to post when marking a PR as stale
          stale-pr-message: |
            Этот пулл-реквест был автоматически помечен как старый потому что в нём не было никакой активности уже 14 дней. Он будет автоматически закрыт ещё через 14 дней, если новой активности не появится.

            Если нужно чтобы он оставался открытым без активности, достаточно оставить любой комментарий, и метка будет убрана.
          # Comment to post when closing a stale PR
          close-pr-message: |
            Этот пулл-реквест был автоматически закрыт, потому что оставался без активности 28 дней.

            Если изменения еще актуальны, пулл-реквест можно открыть снова, попросив разработчика, или сделать полностью новый пулл-реквест.
          # Pull Requests with these labels will never be considered stale

          # Set to true to ignore PRs in a milestone (defaults to false)
          exempt-all-pr-milestones: true

          # Remove stale label from PRs on update (default is true)
          remove-pr-stale-when-updated: true

          ascending: true
